### ISSUE TITLE
The login process

### ISSUE THREAD

**Issue by UmberFunk** [myflashlab/facebook-ANE#1]
Hello,

I have tested your extension on iOS and Android. You have very good documentation and easy setup process. 

We plan to switch to commercial extension for Facebook in future to be sure we will get updates and support. Currently we are using FreshPlanet Facebook ANE.

We have spotted 2 issues:

1) After signing in for first time, when app is removed from memory and booted up again, the login is not done silently. It shows up a rotating circle on Android and on iOS switching to Facebook app for 1 second and then switching back to the app. I'm sure this issue will disturb users and there should be a way to sign in silently. We have experience with different ANE-s and most of them sign in at init without showing up anything.

2) Minor issue: Extension requests Android SDK. I spotted that BAT files run just ADT, which doesn't need Andrid SDK. Is this SDK needed for packager to work or we can remove it?

Best regards,
Irakli

**Comment by myflashlab** [comment]
1) when you sign in users for the first time, you dont have to log them out
again. (You may mimic the logout though) but if you logout from the SDK
which makes the FB token invalid, then logging back in again causes that
behavior. This is how FB SDK works.

2) that's our FlashDevelop sample project with it's own settings.

On Thursday, August 13, 2015, UmberFunk <notifications@github.com> wrote:

> Hello,
>
> I have tested your extension on iOS and Android. You have very good
> documentation and easy setup process.
>
> We plan to switch to commercial extension for Facebook in future to be
> sure we will get updates and support. Currently we are using FreshPlanet
> Facebook ANE.
>
> We have spotted 2 issues:
>
> 1) After signing in for first time, when app is removed from memory and
> booted up again, the login is not done silently. It shows up a rotating
> circle on Android and on iOS switching to Facebook app for 1 second and
> then switching back to the app. I'm sure this issue will disturb users and
> there should be a way to sign in silently. We have experience with
> different ANE-s and most of them sign in at init without showing up
> anything.
>
> 2) Minor issue: Extension requests Android SDK. I spotted that BAT files
> run just ADT, which doesn't need Andrid SDK. Is this SDK needed for
> packager to work or we can remove it?
>
> Best regards,
> Irakli
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/facebook-ANE/issues/1>.
>


-- 
Sent from iPhone

**Comment by UmberFunk** [comment]
OK

P.S. I don't log them out. I just switch app OFF (simulating users possible actions or iOS freeing up of memory), then ON and log-in again. I'm using example provided on Github.

**Comment by UmberFunk** [comment]
P.P.S. Like button is very nice too.

Hope you can fix issue no. 1. I am sure there is a way to silently log-in at application init, after application restart (which might be caused by a lot of reasons).

Regards,
Irakli

**Comment by myflashlab** [comment]
Irakli, I'm pretty sure that the app won't switch to facebook unless you
have logged out the user. We are using it in our latest app!

On Friday, August 14, 2015, UmberFunk <notifications@github.com> wrote:

> P.P.S. Like button is very nice too.
>
> Hope you can fix issue no. 1. I am sure there is a way to silently log-in
> at application init, after application restart (which might be caused by a
> lot of reasons).
>
> Regards,
> Irakli
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/facebook-ANE/issues/1#issuecomment-130852319>
> .
>


-- 
Sent from iPhone

**Comment by UmberFunk** [comment]
Ok. I'll double-check my code in next several days and write back.

**Comment by UmberFunk** [comment]
I double-checked it again. If the app is switched off (e.g. removed from memory. It's frequent event) on IOS (WITHOUT PRESSING LOG OUT), after switching it ON again and pressing login button, it shows up Facebook app for 1-2 seconds and then switches back.

Guys, I'm telling you this, because I want your product to be improved. You don't even ask me any question. Maybe I'm doing something wrong (I don't think so, but anyway. I'm using example provided by you) or maybe I'm right and you didn't spotted this. I like your ANE, because it has Like button and share and plan to purchase it, but with this behavior it won't be suitable for us and I think also for most of developers. 

Thanks,
Irakli

**Comment by 22Round** [comment]
I am testing Facebook ANE-s too and agree Irakli, for user experience better silence login (as FreshPlanet ANE has)

**Comment by myflashlab** [comment]
@UmberFunk tomorrow will check this out with more attention... maybe the version in Github is older or something, anyway, will check and let you know.

**Comment by myflashlab** [comment]
Aha, i got it. I read your message again and now i know what mistake (not a
mistake actually) you made. Let me explain:

You said "after switching it ON again and pressing login button" that's the
point. You see, pressing the login button will send the permissions list
again to facebook and will renew your FB token and that makes the switch.

To avoid that in your project, simply check if the user is already logged
in or not by checking the token availability

    FB.logManager.token

If token is available then you don't have to ask for permissions again.

Please note that unlike freshplanet ANE, we tried to mimic the behavior of
our ANE very similar to how Facebook SDK works. And that made you a bit
confused.

We will make sure to put a notice on this use case so other people won't
get confused too. Thanks alot for reporting this.

Please test your project considering what I suggested above and tell me if
everything worked fine this time?



On Saturday, August 15, 2015, Vakhtangi Beridze <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> I am testing Facebook ANE-s too and agree Irakli, for user experience
> better silence login (as FreshPlanet ANE has)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/facebook-ANE/issues/1#issuecomment-131340509>
> .
>


-- 
Sent from iPhone

**Comment by UmberFunk** [comment]
Aaaawww... Got it. It's working. Thanks! 
I'll test it later on Android. Sure, it will work same on android.

You are welcome! Hope it may help.

I really like your ANE. I think we'll get back to it after some period. 

Best,
Irakli
