### ISSUE TITLE
Possible to have more than one app ID in manifest?

### ISSUE THREAD

**Issue by PippoApps** [myflashlab/facebook-ANE#102]
Hi, I am in need to connect the app to a different facebook app according to some user preferences. Is it possible in manifest to set more than one app id? 
Using another app id triggers a window with a cryptic error message.

**Comment by myflashlab** [comment]
I don't think that could be possible. Have you seen any native app doing that? or have you seen some native libraries explaining something like that?

**Comment by PippoApps** [comment]
Never heard of, that's why I am asking :) for debugging purposes would make it simpler for us to redirect to a different app ID according to device udid, but we will stick to different apps then. Thanks for your reply

**Comment by myflashlab** [comment]
Even in the newer version of this ANE released yesterday, we could not add such a feature! it makes thing too much complicated. so we had to ignore it. sorry.
