### ISSUE TITLE
Push notification received not firing handler

### ISSUE THREAD

**Issue by msmpro** [myflashlab/facebook-ANE#103]
Hi,

I'm updating from FB ANE v.4.17.1 to v.4.22.3 and everythings seems OK, but when I click on the received notifications, the APP is opened but the handler for push notification is not fired.
I'm using Milkman ANE for push notifications from a long time ago and it's working correctly until the last update for Facebook ANE 4.22.3. The app is correctly registred, I get the token and I receive the notification when my app is on background, but when I click it, the event is not dispatched to launch the assigned listener.

This problem is happening only on IOS.

I modified the app manifest with everything necessary for v4.22.3, but I used the v4.17.1 of FB ANE and I used the v4.0.0 of overraidAir.ane, and it's working correctly. But when I switch to v.4.22.3 and v.4.1.0 the hanlder to process the push notification data is not fired.

Any idea?
Thanks in advance

## Environment ##
* iOS Version: 9.3.5
* AIR SDK Version: 25 and 26

**Comment by Barney4242** [comment]
For me Facebook ANE "blocks" AIR SDK native .subscribe() function for iOS. Thus Facebook ANE can not be used with push notifications. If I comment FB.getInstance(xxx); I can use remoteNot.subscribe(subscribeOptions); and get the token. AIR SDK 26, 27

**Comment by myflashlab** [comment]
> We have updated the ANE to the latest SDK and a LOT has changed. for example like buttons and app invites have been deprecated but we have now added the GameRequest feature. Moreover, we have re-wrote the whole Actionscript part to be easier to work with. Please update yourself to the latest version and see how it goes. If you are still encountering any problem, please feel free to open a new issue and ask your questions. And by the way, when updating your app with the new ANE, make sure to read and follow the [new wiki documentations](https://github.com/myflashlab/facebook-ANE/wiki). Moreover, the asdoc has also moved to this package: http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/fb/package-detail.html

Also make sure to read the changelog to know what changes you need to make to your manifest. xml file.
