### ISSUE TITLE
Unable to create APK from Facebook(Android+IOS) Demo.as

### ISSUE THREAD

**Issue by TeamISE** [myflashlab/facebook-ANE#104]
I'v been on it for about a week and I still can't seem to export a working Apk. I have all the ANE (androidSupport-full.ane, overrideAir.ane, facebook.ane) and redid the xml and the error message I keep receiving when I begin to create APK say something like.
aapt tool failed:/private/var/folders/25/z8zzn3vn28d3q8l1sqnjff_w0000gn/T/f72abe79-37f7-421d-8d2e-a5d934d278a9/com.facebook-res/values/values.xml:131: error: Error retrieving parent for item: No resource found that matches the given name '.AppCompat.NoActionBar'. Im build from the Demo.as sample and I'm using Adobe CS6 air.sdk 26.

**Comment by myflashlab** [comment]
This error usually happens if you are missing the androidSupport ANE. ```<extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>```
but you are saying that the dependency is included in your project. 🤔 

Please post your manifest .xml file so we can have a look.

**Comment by TeamISE** [comment]
Thanks for the reply.

![screen shot 2017-10-07 at 8 50 52 am](https://user-images.githubusercontent.com/27572972/31308004-bbc33264-ab3c-11e7-8954-9dfda12670ea.png)

![screen shot 2017-10-07 at 8 48 25 am](https://user-images.githubusercontent.com/27572972/31307980-67c8af2c-ab3c-11e7-8c10-ff934a96a94b.png)
![screen shot 2017-10-07 at 8 48 25 am](https://user-images.githubusercontent.com/27572972/31307982-6c1c2fe0-ab3c-11e7-8d83-6cb5ff9c9b0c.png)
![screen shot 2017-10-07 at 8 48 25 am](https://user-images.githubusercontent.com/27572972/31307983-6f98276e-ab3c-11e7-849d-589d0fd2c71d.png)

**Comment by TeamISE** [comment]
![screen shot 2017-10-07 at 8 47 52 am](https://user-images.githubusercontent.com/27572972/31308038-550232e0-ab3d-11e7-8778-be0c38830ef2.png)

**Comment by myflashlab** [comment]
**NOTICE:** When posting codes, do NOT take screenshots. it's not easy to read them like this. simply use the beautiful markdown language provided by GitHub. learn more about it here: https://guides.github.com/features/mastering-markdown/

Anyhow, I think I found the problem. you are using the lite version of the androidSupport ANE. That's what I see in the first screenshot you sent. Please replace that with the full version.

**Comment by TeamISE** [comment]
Wow. It looks like that might have been the problem. Thanks so much
