### ISSUE TITLE
Login window appearing twice when requesting both READ and PUBLISH permissions.

### ISSUE THREAD

**Issue by PippoApps** [myflashlab/facebook-ANE#106]
Android 5.0, AIR 27
NO facebook app installed.

## Problem Description ##
Requesting only READ permissions at login everything works fine.
Requesting READ and PUBLISH permissions at startup, makes me log-in, accept permissions, but then log-in popup is triggered again. I login again, and overlay FB screens stays in loading mode forever. I click "back" on android or close login screen, and app logs in normally (login success event is called).

## Steps to Reproduce ##
1 - Initialize ANE.
2 - Request READ permissions
3 - Request PUBLISH permissions
4 - log-in normally
5 - BOOM - login screen appears again, and at second login stays loading indefinitely, until I close it or click back.

## Known Workarounds ##
Just request READ permissions and all will go fine.

**Comment by PippoApps** [comment]
Anybody home?

**Comment by PippoApps** [comment]
Guys, I convinced my boss to buy a club membership. 22 days ago I posted an issue, even pinged, and nobody replies. We are professional here, spending money on your products, and time is limited.

**Comment by myflashlab** [comment]
sorry for the delay. sometimes things get hectic. Anyway, please make sure you are not requesting read and write permissions together. as Facebook best practices suggests, you should first ask for read permissions first and then when ever your app needs the write permissions, you should ask users again. I hope this helps.

**Comment by PippoApps** [comment]
Thank you very much, no worries.
