### ISSUE TITLE
"No resource found" errors under AIR 27 / Android

### ISSUE THREAD

**Issue by chpla** [myflashlab/facebook-ANE#107]
## Environment ##
* Android API Version: ? (where can I see this?)
* AIR SDK Version: 27

## Problem Description ##
When trying to build in Animate CC, I get:

aapt tool failed:/private/var/folders/2m/wvvsjw_556x1nfb609n1rmnc0000gn/T/c948c8e2-6855-481b-9656-4beb23d3b0f9/com.facebook-res/values/values.xml:131: error: Error retrieving parent for item: No resource found that matches the given name '@style/Theme.AppCompat.NoActionBar'.

/private/var/folders/2m/wvvsjw_556x1nfb609n1rmnc0000gn/T/c948c8e2-6855-481b-9656-4beb23d3b0f9/com.facebook-res/values/values.xml:136: error: Error retrieving parent for item: No resource found that matches the given name '@style/Theme.AppCompat.Dialog'.

* Copy your manifest ```.xml``` file.
```xml
<manifest android:installLocation="auto">
				
				<uses-sdk android:targetSdkVersion="23"/>
				<uses-sdk android:minSdkVersion="15"/>
				
				<uses-permission android:name="android.permission.INTERNET"/>
				<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
				<uses-permission android:name="android.permission.GET_ACCOUNTS" />
				<uses-permission android:name="com.android.vending.BILLING" />
				<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
				<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
				<uses-permission android:name="android.permission.READ_PHONE_STATE" />
<application android:allowBackup="true" android:hardwareAccelerated="true">

						<!-- Facebook -->
						<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="\ 000000000"/>
						<activity android:name="com.facebook.FacebookActivity" android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation" android:theme="@android:style/Theme.Translucent.NoTitleBar" android:label="Blah" />
						<activity android:name="com.doitflash.facebook.access.MyLogin" android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation" android:theme="@style/Theme.Transparent" />
						<activity android:name="com.facebook.CustomTabMainActivity" />
						<activity
							android:name="com.facebook.CustomTabActivity"
							android:exported="true">
							<intent-filter>
								<action android:name="android.intent.action.VIEW" />
								<category android:name="android.intent.category.DEFAULT" />
								<category android:name="android.intent.category.BROWSABLE" />
								<data android:scheme="fb00dfs0fds0" />
							</intent-filter>
						</activity>
</application>
			</manifest>
```

## Steps to Reproduce ##
Try building .apk with Animate CC

**Comment by colouredFunk** [comment]
Same problem

**Comment by babakasol** [comment]
same problem with the latest version 
also have updated AIRSDK to 28.

**Comment by myflashlab** [comment]
The error message shows some Android dependencies are missing. This can happen when you have set your AIR SDK to lower versions. Although you maybe using AIR 27 or 28, you must also make sure your manifest is targeting AIR 27 or 28.

Besides, you should also make sure the required dependency ANEs are all available and implemented in your project.

**Comment by AlexUrrutia** [comment]
Same problem here, target: 28

**Comment by AlexUrrutia** [comment]
`aapt tool failed:/private/var/folders/8x/rtdgg9cd2l7_4t_2lfbb1s6w0000gn/T/04d10b21-0eb2-43c5-b31a-e56f33220477/com.facebook-res/values/values.xml:131: error: Error retrieving parent for item: No resource found that matches the given name '@style/Theme.AppCompat.NoActionBar'.
/private/var/folders/8x/rtdgg9cd2l7_4t_2lfbb1s6w0000gn/T/04d10b21-0eb2-43c5-b31a-e56f33220477/com.facebook-res/values/values.xml:136: error: Error retrieving parent for item: No resource found that matches the given name '@style/Theme.AppCompat.Dialog'.`

**Comment by AlexUrrutia** [comment]
This error is happening on AIR 27,28,29beta . ANE's used:  Google SignIn, AdMob, Facebook
Can't compile, Any ideas? 
IntelliJ

Manifest:
`<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<application xmlns="http://ns.adobe.com/air/application/28.0">
  <id>com.my.app</id>
  <versionNumber>2.0.27</versionNumber>
  <filename>ChatVideo2</filename>
  <description></description>
  <name>myApp</name>
  <copyright></copyright>
  <initialWindow>
    <content></content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <depthAndStencil>true</depthAndStencil>
    <visible>true</visible>
    <fullScreen>true</fullScreen>
    <autoOrients>true</autoOrients>
    <aspectRatio>portrait</aspectRatio>
    <renderMode>direct</renderMode>
  </initialWindow>
  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>false</allowBrowserInvocation>
  <icon>
    <image36x36>appicons/36.png</image36x36>
    <image48x48>appicons/48.png</image48x48>
    <image72x72>appicons/72.png</image72x72>
    <image96x96>appicons/96.png</image96x96>
    <image144x144>appicons/144.png</image144x144>
    <image192x192>appicons/192.png</image192x192>

  </icon>
  <android>
    <containsVideo>true</containsVideo>
    <manifestAdditions>
      <![CDATA[
     <manifest android:installLocation="auto">
        <uses-permission android:name="android.permission.INTERNET"/>
        <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
        <uses-permission android:name="android.permission.GET_ACCOUNTS" />
        <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
        <uses-permission android:name="android.permission.CAMERA"/>
        <uses-permission android:name="android.permission.RECORD_AUDIO"/>
        <uses-permission android:name="android.permission.DISABLE_KEYGUARD"/>
        <uses-permission android:name="android.permission.WAKE_LOCK"/>
        <uses-sdk android:minSdkVersion="16" android:targetSdkVersion="28"/>

		<application android:hardwareAccelerated="true" android:allowBackup="true">

       <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
       <activity android:name="com.google.android.gms.ads.AdActivity" android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize" android:theme="@android:style/Theme.Translucent"/>
<activity android:name="com.google.android.gms.auth.api.signin.internal.SignInHubActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar" android:excludeFromRecents="true" android:exported="false"/>
<service android:name="com.google.android.gms.auth.api.signin.RevocationBoundService" android:exported="true" android:permission="com.google.android.gms.auth.api.signin.permission.REVOCATION_NOTIFICATION"/>
<activity android:name="com.google.android.gms.common.api.GoogleApiActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar" android:exported="false"/>

<activity android:launchMode="standard">
						<intent-filter>
						 <action android:name="android.intent.action.MAIN"/>
						 <category android:name="android.intent.category.LAUNCHER"/>
							<action android:name="android.intent.action.VIEW" />
							<category android:name="android.intent.category.DEFAULT" />
							<category android:name="android.intent.category.BROWSABLE" />
                        <data android:scheme="air.my.app" />
						</intent-filter>
					</activity>


				
			<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="\ 160644522456"/>

			
			<activity android:name="com.facebook.FacebookActivity" android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation" android:theme="@android:style/Theme.Translucent.NoTitleBar" android:label="ChatVideo" />
			<activity android:name="com.doitflash.facebook.access.MyLogin" android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation" android:theme="@style/Theme.Transparent" />

			<activity android:name="com.facebook.CustomTabMainActivity" />
			<activity android:name="com.facebook.CustomTabActivity" android:exported="true">
				<intent-filter>
					<action android:name="android.intent.action.VIEW" />
					<category android:name="android.intent.category.DEFAULT" />
					<category android:name="android.intent.category.BROWSABLE" />
					<data android:scheme="fb160644522456" />
				</intent-filter>
			</activity>


			
			<provider android:authorities="com.facebook.app.FacebookContentProvider160644522456" android:name="com.facebook.FacebookContentProvider" android:exported="true"/>
			<activity android:name="com.doitflash.facebook.sharing.MyShare" android:theme="@style/Theme.Transparent" />

			
			<activity android:name="com.doitflash.facebook.invite.MyInvite" android:theme="@style/Theme.Transparent" />



		</application>
        </manifest>]]>
    </manifestAdditions>
  </android>
  <versionLabel></versionLabel>
  <extensions>

    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads.lite</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.auth</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.auth.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>

    <extensionID>com.myflashlab.air.extensions.admob</extensionID>
    <extensionID>com.myflashlab.air.extensions.google.signin</extensionID>
    <extensionID>com.myflashlab.air.extensions.facebook</extensionID>
  </extensions>
</application>`

**Comment by myflashlab** [comment]
> We have updated the ANE to the latest SDK and a LOT has changed. for example like buttons and app invites have been deprecated but we have now added the GameRequest feature. Moreover, we have re-wrote the whole Actionscript part to be easier to work with. Please update yourself to the latest version and see how it goes. If you are still encountering any problem, please feel free to open a new issue and ask your questions. And by the way, when updating your app with the new ANE, make sure to read and follow the [new wiki documentations](https://github.com/myflashlab/facebook-ANE/wiki). Moreover, the asdoc has also moved to this package: http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/fb/package-detail.html

Also make sure to read the changelog to know what changes you need to make to your manifest. xml file.
