### ISSUE TITLE
iOS app crashes calling facebook login.

### ISSUE THREAD

**Issue by PippoApps** [myflashlab/facebook-ANE#108]
## Environment ##
* iOS Version: 8.4.1
* AIR SDK Version: 27.0.0.124

## Problem Description ##
Same code works perfectly on Android. 
On iOS, application crashes as soon as I call login. Nothing from ANE gets traced using overrideAir debugger (which works on Android).

* Copy your manifest ```.xml``` file.
```xml

<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<!-- 
	Usage:

	To localize the description, use the following format for the description element.
	<description>
	<text xml:lang="en">English App description goes here</text>
	<text xml:lang="fr">French App description goes here</text>
	<text xml:lang="ja">Japanese App description goes here</text>
	</description>

	To localize the name, use the following format for the name element.
	<name>
	<text xml:lang="en">English App name goes here</text>
	<text xml:lang="fr">French App name goes here</text>
	<text xml:lang="ja">Japanese App name goes here</text>
	</name>
-->
<application xmlns="http://ns.adobe.com/air/application/27.0">
  <id>com.[privacy]</id>
  <versionNumber>0.1.6</versionNumber>
  <versionLabel/>
  <filename>Bunco Bonko</filename>
  <description/> 
  <name>Bunco Bonko</name>
  <copyright/>
  <initialWindow>  
    <content>BuncoBonko_Device_iOS.swf</content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <visible>true</visible>
    <fullScreen>true</fullScreen>
    <aspectRatio>landscape</aspectRatio>
    <renderMode>gpu</renderMode>
    <autoOrients>true</autoOrients></initialWindow>
  <icon>
    <image29x29>_icons/ios/logo_29x29.png</image29x29>
    <image57x57>_icons/ios/logo_57x57.png</image57x57>
    <image114x114>_icons/ios/logo_114x114.png</image114x114>
    <image512x512>_icons/ios/logo_512x512.png</image512x512>
    <image48x48>_icons/ios/logo_48x48.png</image48x48>
    <image72x72>_icons/ios/logo_72x72.png</image72x72>
    <image50x50>_icons/ios/logo_50x50.png</image50x50>
    <image58x58>_icons/ios/logo_58x58.png</image58x58>
    <image100x100>_icons/ios/logo_100x100.png</image100x100>
    <image144x144>_icons/ios/logo_144x144.png</image144x144>
    <image1024x1024>_icons/ios/logo_1024x1024.png</image1024x1024>
    <image40x40>_icons/ios/logo_40x40.png</image40x40>
    <image76x76>_icons/ios/logo_76x76.png</image76x76>
    <image80x80>_icons/ios/logo_80x80.png</image80x80>
    <image120x120>_icons/ios/logo_120x120.png</image120x120>
    <image152x152>_icons/ios/logo_152x152.png</image152x152>
    <image180x180>_icons/ios/logo_180x180.png</image180x180>
    <image60x60>_icons/ios/logo_60x60.png</image60x60>
    <image75x75>_icons/ios/logo_75x75.png</image75x75>
    <image87x87>_icons/ios/logo_87x87.png</image87x87>
    <image167x167>_icons/ios/logo_167x167.png</image167x167>
  </icon>
  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>true</allowBrowserInvocation>
  
   <iPhone>
    <!-- A list of plist key/value pairs to be added to the application Info.plist -->
    <InfoAdditions><![CDATA[
  <key>MinimumOSVersion</key>
  <string>8.0</string>
  
  <key>UIStatusBarStyle</key>
  <string>UIStatusBarStyleBlackOpaque</string>
  
  <key>UIRequiresPersistentWiFi</key>
  <string>NO</string>
  
  <key>FacebookAppID</key>
  <string>970119236382852</string>
  
  <key>FacebookDisplayName</key>
  <string>Bunco Bonko</string>
  
  <key>CFBundleURLTypes</key>
  <array>
    <dict>
      <key>CFBundleURLSchemes</key>
      <array>
        <string>fb970119236382852</string>
        <!-- Your application scheme. read here for more information: http://www.myflashlabs.com/open-adobe-air-app-browser-pass-parameters/ -->
        <string>air.com.doitflash.exfacebook2</string>
      </array>
    </dict>
  </array>
 
 <key>LSApplicationQueriesSchemes</key>
  <array>
    <string>fbapi</string>
    <string>fb-messenger-api</string>
    <string>fbauth2</string>
    <string>fbshareextension</string>
  </array>
  
  <key>NSPhotoLibraryUsageDescription</key>
  <string>My description about why I need this feature in my app</string>
  
  <key>UIDeviceFamily</key>
  <array>
    <string>1</string>
    <string>2</string>
  </array>
  <key>NSAppTransportSecurity</key>
  <dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
  </dict>
]]></InfoAdditions>
		
    <requestedDisplayResolution>high</requestedDisplayResolution>
  </iPhone>
  
  <extensions>
    <extensionID>com.myflashlab.air.extensions.facebook</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
  </extensions>
</application>


```
* Copy your Actionscript code.
```actionscript
FB.auth.requestPermission(Auth.WITH_READ_PERMISSIONS, _permissionsRead[0], _permissionsRead[1], _permissionsRead[2]);
```

## Steps to Reproduce ##
Just launch the app. As soon as requestPermission() is called, app crashes.

## Known Workarounds ##
No workarounds.

## Console Trace ##
428 [MainApp]		Preparing DEVICE facebook Login.
429 [MainApp]		
---------|----------------------------------------------------------------------------------------------------
WARNING |	Working on Facebook app: 970119236382852
---------|----------------------------------------------------------------------------------------------------
430 [ANEFacebook]		Initializing facebook app 970119236382852
431 [ANEFacebook]		Setting READ permissions: public_profile,user_friends,email
432 [ANEFacebook]		Loggin in to facebook...
433 [ANEFacebook]		Requesting READ permissions: public_profile,user_friends,email
Debug session terminated.

**Comment by PippoApps** [comment]
This is what comes from iOS console:
Nov 23 00:03:49 PippoFlash-iPhone5 Bunco Bonko[254] <Error>: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: object cannot be nil (key: logging_token)'
	*** First throw call stack:
	(0x22e0af8f 0x314bbc8b 0x22d267d3 0x90debf 0x90e299 0x90e22d 0x90cf19 0x1a2df1d 0x1a2a9f5 0x1a1f129 0x6b63a8 0x19fd030 0x9503b0 0x147d758 0x82f890 0x8398d7 0x839c79 0x839a1d 0x1480508 0x14815a4 0x190bec4 0x19228f0 0x82f890 0x8398d7 0x839c79 0x839a1d 0x83a023 0x808b8f 0x184af94 0x1922bd4 0x82f890 0x8398d7 0x839a1d 0x83a023 0x808b8f 0x184af94 0x18e7d18 0x82f890 0x8398d7 0x839c79 0x839a1d 0x1922d54 0x82f890 0x8398d7 0x839c79 0x839a1d 0x1456ce0 0x82f890 0x8398d7 0x839c79 0x839a1d 0x1457404 0x14285a4 0x82f890 0x8398d7 0x839a1d 0x85290d 0x193a0c8 0x18b9f88 0x82f890 0x8398d7 0x839c79 0x839a1d 0x1456e8c 0x82f890 0x8398d7 0x839c79 0x839a1d 0x1457404 0x14285a4 0x82f890 0x8398d7 0x839a1d 0x85290d 0x193a0c8 0x128a76c 0x82f890 0x8398d7 0x839c79 0x839a1d 0x85290d 0x14050e8 0x82f890 0x8398d7 0x839c79 0x839a1d 0x1405e98 0x14062b4 0x82f890 0x8398d7 0x839c79 0x839a1d 0x368c0c 0x36997c 0x3f6f54 0x1b82b0 0x1b96d8 0x92a74 0x25eec7db 0x25eec643 0x2adf3c07 0x23d89001 0x22dc002d 0x22dd05ab 0x22dd0547 0x22dceb49 0x22d1af31 0x22d1ad43 0x2a7f5201 0x264ec879 0x1f8a08 0x31a6daaf)

**Comment by myflashlab** [comment]
It seems like something is nil when arrived at the iOS side, are you sure these values are valid?
```_permissionsRead[0], _permissionsRead[1], _permissionsRead[2]```?

**Comment by PippoApps** [comment]
Yep they get traced just at the previous line:
433 [ANEFacebook]	Requesting READ permissions: public_profile,user_friends,email
Same code on Android works. I will try hardcoding strings or using the constants.

Might it be because I am using the default (yours) scheme?

**Comment by PippoApps** [comment]
Same outcome with this code:

```
Debug.warning(_debugPrefix, "Requesting permissions: " +  Permissions.email, Permissions.user_friends, Permissions.public_profile);
FB.auth.requestPermission(Auth.WITH_READ_PERMISSIONS, Permissions.email, Permissions.user_friends, Permissions.public_profile);
```
output before crash:

```
435 [ANEFacebook]		Requesting READ permissions: public_profile,user_friends,email
436 [ANEFacebook]		
---------|----------------------------------------------------------------------------------------------------
WARNING |	Requesting permissions: email, user_friends, public_profile
---------|----------------------------------------------------------------------------------------------------
Debug session terminated.
```

**Comment by PippoApps** [comment]
Any hint about what "logging_token" is?

**Comment by PippoApps** [comment]
![image](https://user-images.githubusercontent.com/29799572/33183358-dac59e8a-d077-11e7-8f96-f68c9bce57f0.png)
thank you!

**Comment by PippoApps** [comment]
On iOS 9.3.5 works perfectly. On 8.4.1 doesn't.

**Comment by myflashlab** [comment]
yeah, that's what it seems. on iOS 9+ works fine. It seems like something is going wrong on the FB SDK Side. Although this version of the SDK is supposed to support iOS 8 too. We're checking for more details... However, I don't think iOS 8 would be that important anymore according to stats:
![iOS 10, 9 and earlier](https://www.brightec.co.uk/sites/default/files/iOS%20Version%20breakdown%202017_03.png)

and even newer data: https://developer.apple.com/support/app-store/

**Comment by myflashlab** [comment]
oops, wrongly hit the close button!

**Comment by myflashlab** [comment]
> Any hint about what "logging_token" is?

When you login to Facebook, you will receive a token. This can be used with facebook Graph OR Firebase Auth ANE.

**Comment by myflashlab** [comment]
> We have updated the ANE to the latest SDK and a LOT has changed. for example like buttons and app invites have been deprecated but we have now added the GameRequest feature. Moreover, we have re-wrote the whole Actionscript part to be easier to work with. Please update yourself to the latest version and see how it goes. If you are still encountering any problem, please feel free to open a new issue and ask your questions. And by the way, when updating your app with the new ANE, make sure to read and follow the [new wiki documentations](https://github.com/myflashlab/facebook-ANE/wiki). Moreover, the asdoc has also moved to this package: http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/fb/package-detail.html

Also make sure to read the changelog to know what changes you need to make to your manifest. xml file.
