### ISSUE TITLE
iOS 9.3.5, no FB app, I can only login default user even after logout

### ISSUE THREAD

**Issue by PippoApps** [myflashlab/facebook-ANE#109]
Before opening a new issue, make sure you are using the latest available ANE. If the ANE is dependent on other libraries or dependencies, also make sure they are the latest versions.

## Environment ##
* iOS Version: 9.3.5
* AIR SDK Version: 27.0.0.124

## Problem Description ##
- There is no facebook app installed. 
- Facebook already has a user logged in in Safari. 
- When I request login, I do not get prompted for username/password, but I go directly to the screen "you have already accesses with facebook, continue?" with 2 choices: CONTINE, CANCEL.
- Hitting on cancel, closes Safari, and then reopens it again on the same exact page.
- I Hit CONTINUE, login the game with the user logged in Safari
- I hit logout, ANE has FB.auth.logout() called successfully.
- I am brought again to the same page with CONTINE or CANCEL.
**There is no way to login a different user other then the one logged in Safari**

* Copy your manifest ```.xml``` file.
```xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<!-- 
	Usage:

	To localize the description, use the following format for the description element.
	<description>
	<text xml:lang="en">English App description goes here</text>
	<text xml:lang="fr">French App description goes here</text>
	<text xml:lang="ja">Japanese App description goes here</text>
	</description>

	To localize the name, use the following format for the name element.
	<name>
	<text xml:lang="en">English App name goes here</text>
	<text xml:lang="fr">French App name goes here</text>
	<text xml:lang="ja">Japanese App name goes here</text>
	</name>
-->
<application xmlns="http://ns.adobe.com/air/application/27.0">
  <id>com.yappingmoose.buncobonko</id>
  <versionNumber>0.2.1</versionNumber>
  <versionLabel/>
  <filename>Bunco Bonko</filename>
  <description/> 
  <name>Bunco Bonko</name>
  <copyright/>
  <initialWindow>  
    <content>BuncoBonko_Device_iOS.swf</content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <visible>true</visible>
    <fullScreen>true</fullScreen>
    <aspectRatio>landscape</aspectRatio>
    <renderMode>gpu</renderMode>
    <autoOrients>true</autoOrients></initialWindow>
  <icon>
    <image29x29>_icons/ios/logo_29x29.png</image29x29>
    <image57x57>_icons/ios/logo_57x57.png</image57x57>
    <image114x114>_icons/ios/logo_114x114.png</image114x114>
    <image512x512>_icons/ios/logo_512x512.png</image512x512>
    <image48x48>_icons/ios/logo_48x48.png</image48x48>
    <image72x72>_icons/ios/logo_72x72.png</image72x72>
    <image50x50>_icons/ios/logo_50x50.png</image50x50>
    <image58x58>_icons/ios/logo_58x58.png</image58x58>
    <image100x100>_icons/ios/logo_100x100.png</image100x100>
    <image144x144>_icons/ios/logo_144x144.png</image144x144>
    <image1024x1024>_icons/ios/logo_1024x1024.png</image1024x1024>
    <image40x40>_icons/ios/logo_40x40.png</image40x40>
    <image76x76>_icons/ios/logo_76x76.png</image76x76>
    <image80x80>_icons/ios/logo_80x80.png</image80x80>
    <image120x120>_icons/ios/logo_120x120.png</image120x120>
    <image152x152>_icons/ios/logo_152x152.png</image152x152>
    <image180x180>_icons/ios/logo_180x180.png</image180x180>
    <image60x60>_icons/ios/logo_60x60.png</image60x60>
    <image75x75>_icons/ios/logo_75x75.png</image75x75>
    <image87x87>_icons/ios/logo_87x87.png</image87x87>
    <image167x167>_icons/ios/logo_167x167.png</image167x167>
  </icon>
  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>true</allowBrowserInvocation>
  
  






  <iPhone>
    <!-- A list of plist key/value pairs to be added to the application Info.plist -->
    <InfoAdditions><![CDATA[
  <key>MinimumOSVersion</key>
  <string>8.0</string>
  
  <key>UIStatusBarStyle</key>
  <string>UIStatusBarStyleBlackOpaque</string>
  
  <key>UIRequiresPersistentWiFi</key>
  <string>NO</string>
  
  <key>FacebookAppID</key>
  <string>970119236382852</string>
  
  <key>FacebookDisplayName</key>
  <string>Bunco Bonko</string>
  
  <key>CFBundleURLTypes</key>
  <array>
    <dict>
      <key>CFBundleURLSchemes</key>
      <array>
        <string>fb970119236382852</string>
        <string>air.com.yappingmoose.buncobonko</string>
      </array>
    </dict>
  </array>
 
 <key>LSApplicationQueriesSchemes</key>
  <array>
    <string>fbapi</string>
    <string>fb-messenger-api</string>
    <string>fbauth2</string>
    <string>fbshareextension</string>
  </array>
  
  <key>NSPhotoLibraryUsageDescription</key>
  <string>My description about why I need this feature in my app</string>
  
  <key>UIDeviceFamily</key>
  <array>
    <string>1</string>
    <string>2</string>
  </array>
  <key>NSAppTransportSecurity</key>
  <dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
  </dict>
]]></InfoAdditions>
		
    <requestedDisplayResolution>high</requestedDisplayResolution>
  </iPhone>
  
	 <extensions>
		<extensionID>com.myflashlab.air.extensions.billing</extensionID>
		<extensionID>com.myflashlab.air.extensions.facebook</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
	</extensions>
</application>

```
* Copy your Actionscript code.
```actionscript
FB.auth.requestPermission(Auth.WITH_READ_PERMISSIONS, _permissionsRead[0], _permissionsRead[1], _permissionsRead[2]);
```

## Steps to Reproduce ##
Just login. 

## Known Workarounds ##
None so far.

**Comment by myflashlab** [comment]
What you described seems to be the standard behavior. Facebook SDK is reading user login stats from the safariWindow. I don't think it would be possible to have user "B" logged into the app while user "A" is logged into facebook via safari already.

However, about this line: ```Hitting on cancel, closes Safari, and then reopens it again on the same exact page.``` Do you mean that the ANE is trying to login again after you hit the "cancel" button? let me look into that more carefully and get back to you.

**Comment by PippoApps** [comment]
Ok thanks. No worries, that's the app default behaviour, doesn't allow you to proceed unless you are logged. Therefore hitting cancel triggers login again, so that's what should happen.
On Android though, even though I am logged into Chrome, I can logout and in again.

**Comment by PippoApps** [comment]
Sorry for reopening this issue. We do need a way to logout from the app and let the user login with another account. Could you suggest a solution? Even with facebook app installed, we still get exactly the same behaviour.
You logout the ANE, and a page is opened only with "CONTINUE", and you can only re-login the same user. Doesn't really make sense to us to logout, if then the only user I can login is the same as before...

**Comment by PippoApps** [comment]
This SO question explains how to logout a user from facebook using a url and redirect again to a new page
https://stackoverflow.com/questions/6232771/facebook-logout-url

**Comment by PippoApps** [comment]
There is another very useful SO issue related to this:
https://stackoverflow.com/questions/30092610/facebook-logout-is-not-working-in-new-sdk-v-4-1-0-in-ios

**Comment by PippoApps** [comment]
I have found a solution:
1 - Logout from ane, logout from game server, clear cookies, caches, etc.
2 - Prompt user to logout from facebook app and safari
3 - Call blank url "https://www.facebook.com"
4 - App or safari opens with "back to..." button on top left
5 - User logs out
6 - Goes back to app with top left button
7 - Logs in again , this time he is prompted

This works both with FB app or without.
This is necessary, since Apple for online games requires a test user login. If tester is logged in facebook with another account, loggin out and another user is necessary in order to get store approval.

I hope this helps :)
cheers
