### ISSUE TITLE
FB.share only uses contentURL on Android.

### ISSUE THREAD

**Issue by bithorder** [myflashlab/facebook-ANE#113]
* Android Version: 7.1.1
* AIR SDK Version: 28
* ANE Version: V4.22.5

When calling FB.share() the shared post does not contains the contentDescription, contentTitle and imageURL. Only the contentURL appear to be shared.

No errors are reported, the callback function receives:
status: onSharingSuccess
msg: null

This was tested with both the facebook app installed and not.

**Comment by myflashlab** [comment]
This change has been made by facebook native SDK, There's nothing we can do about it. we have mentioned this in the [change logs](https://github.com/myflashlab/facebook-ANE#changelog).

> When using sharing a URL with FB.share(shareModel, onSharingResult);, the shareModel object can only have the contentURL property. Other properties are deprecated: (contentDescription, contentTitle and imageURL)
