### ISSUE TITLE
The documentation for call has weird deprecated statement.

### ISSUE THREAD

**Issue by bithorder** [myflashlab/facebook-ANE#114]
The documentation for Graph.call states that:
"Depricated and will be removed in future versions of this ANE, instead use the call method."
But there is no other method called "call", so I assume the statement is wrong.

http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/facebook/access/Graph.html

**Comment by myflashlab** [comment]
OH, good finding, it's just a miss-placement of asdoc from the old deperacated method. You should use the ```call``` method with no problem. I will fix this and get back to you on your other tickets also. Thanks.

**Comment by myflashlab** [comment]
This is fixed now.
