### ISSUE TITLE
FB.appInvite lacks documentation for the callback arguments.

### ISSUE THREAD

**Issue by bithorder** [myflashlab/facebook-ANE#115]
The documentation does not specify what arguments the callback function will receive, just 
"a function which will be called to report your invitation state."

http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/facebook/FB.html#appInvite()

**Comment by PippoApps** [comment]
Any news on this?

**Comment by myflashlab** [comment]
check the sample here: https://github.com/myflashlab/facebook-ANE/blob/master/AIR/src/Demo.as#L455-L476

**Comment by PippoApps** [comment]
Thank you. Isn't AppInvite deprecated by facebook?
"With the release of the Facebook SDK version 4.28.0, App Invites is deprecated. It will be supported until February 5, 2018."

**Comment by PippoApps** [comment]
In this page facebook says that app invites stopped working 3 days ago...
https://developers.facebook.com/docs/app-invites

**Comment by myflashlab** [comment]
> We have updated the ANE to the latest SDK and a LOT has changed. for example like buttons and app invites have been deprecated but we have now added the GameRequest feature. Moreover, we have re-wrote the whole Actionscript part to be easier to work with. Please update yourself to the latest version and see how it goes. If you are still encountering any problem, please feel free to open a new issue and ask your questions. And by the way, when updating your app with the new ANE, make sure to read and follow the [new wiki documentations](https://github.com/myflashlab/facebook-ANE/wiki). Moreover, the asdoc has also moved to this package: http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/fb/package-detail.html

Also make sure to read the changelog to know what changes you need to make to your manifest. xml file.
