### ISSUE TITLE
Unable to get provider com.facebook.FacebookContentProvider

### ISSUE THREAD

**Issue by AlexUrrutia** [myflashlab/facebook-ANE#119]
App works fine on Android 5+
App crashes on start on Android 4.4.2 

**java.lang.RuntimeException: Unable to get provider com.facebook.FacebookContentProvider: java.lang.ClassNotFoundException: Didn't find class "com.facebook.FacebookContentProvider"**

## Environment ##
* Android API Version: 19
* AIR SDK Version: 27,28,29

## Problem Description ##
Describe your problem in detail.
* Copy your manifest ```.xml``` file.
```xml

<activity android:hardwareAccelerated="false">
                <intent-filter>
                    <action android:name="android.intent.action.MAIN" />
                    <category android:name="android.intent.category.LAUNCHER" />
                </intent-filter>
                <intent-filter>
                    <action android:name="android.intent.action.VIEW" />
                    <category android:name="android.intent.category.BROWSABLE" />
                    <category android:name="android.intent.category.DEFAULT" />
                    <!-- Your application scheme. read here for more information: http://www.myflashlabs.com/open-adobe-air-app-browser-pass-parameters/ -->
                    <data android:scheme="air.com.myapp" />
                </intent-filter>
            </activity>
            
            <!--
                This is required by the Facebook ANE. replace the zeros with your actual Facebook App ID
                While doing that, notice the empty space after the "\ ". This is required because the ANE
                must see the value as an String.
            -->
            <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="\ XXXXXXXXXXXXXX"/>
            <!-- This is required by the Facebook ANE for logging in -->
            <activity android:name="com.facebook.FacebookActivity" android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation" android:theme="@android:style/Theme.Translucent.NoTitleBar" android:label="My App" />
            <activity android:name="com.doitflash.facebook.access.MyLogin" android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation" android:theme="@style/Theme.Transparent" />
            <activity android:name="com.facebook.CustomTabMainActivity" />
            <activity android:name="com.facebook.CustomTabActivity" android:exported="true">
                <intent-filter>
                    <action android:name="android.intent.action.VIEW" />
                    <category android:name="android.intent.category.DEFAULT" />
                    <category android:name="android.intent.category.BROWSABLE" />
                    <data android:scheme="fbXXXXXXXXXXXXXX" />
                </intent-filter>
            </activity>
            <!-- This is required by the Facebook ANE for sharing https://developers.facebook.com/docs/sharing/android -->
            <provider android:authorities="com.facebook.app.FacebookContentProviderXXXXXXXXXXXXXX" android:name="com.facebook.FacebookContentProvider" android:exported="true" />
            <activity android:name="com.doitflash.facebook.sharing.MyShare" android:theme="@style/Theme.Transparent" />
            <!-- This is required by the Facebook ANE for app invite feature -->
            <activity android:name="com.doitflash.facebook.invite.MyInvite" android:theme="@style/Theme.Transparent" />
		</application>
        </manifest>]]>
    </manifestAdditions>
  </android>
  <versionLabel></versionLabel>
  <extensions>
    
    <extensionID>com.myflashlab.air.extensions.facebook</extensionID>
    <extensionID>com.myflashlab.air.extensions.admob</extensionID>
    <extensionID>com.marpies.ane.onesignal</extensionID>
    <extensionID>com.myflashlab.air.extensions.google.signin</extensionID>
    <extensionID>com.myflashlab.air.extensions.udid</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads.lite</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.auth</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.auth.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.iid</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.gcm</extensionID>

    
  </extensions>
</application>
```
* ADB log:
```actionscript
java.lang.RuntimeException: Unable to get provider com.facebook.FacebookContentProvider: java.lang.ClassNotFoundException: Didn't find class "com.facebook.FacebookContentProvider
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.FacebookContentProvider" on path: DexPathList[[zip file "/data/app/air.com.chatapp-1.apk"]
```

## Steps to Reproduce ##
install apk on Android 4.4.+

**Comment by myflashlab** [comment]
We are in the progress of upgrading the FB ANE to the latest version. Please wait for this update to be completed.

**Comment by AlexUrrutia** [comment]
@myflashlab  How long until the update is released? the sample app compiles fine in Android 4.4, maybe some conflicts with other ANEs?

**Comment by myflashlab** [comment]
> How long until the update is released?

We are busily working on the new releases full-time. it's hard to predict as building ANEs makes unusual troubles all the time, but we're doing our best to finish as soon as possible.

> the sample app compiles fine in Android 4.4

That's an interesting point, will you be able to test and find out which of other ANEs are causing the possible conflict? that would help us speed up the process.

**Comment by AlexUrrutia** [comment]
@myflashlab it seems the problem is when I add the [GoogleSignIn-ANE](https://github.com/myflashlab/GoogleSignIn-ANE) and its dependencies

**Comment by AlexUrrutia** [comment]
More findings: the ANE that is preventing the app to start with the Facebook ANE is [**UDID ANE**](https://github.com/myflashlab/UDID-ANE) , if I remove it, then the app launch but gets the error, 
in this case, I'm using AdMob ANE and it shows the following error in the adb logcat:

```

TypeError: Error #1009: Cannot access a property or method of a null object reference.
at com.myflashlab.air.extensions.dependency::OverrideAir()
at com.myflashlab.air.extensions.dependency::OverrideAir()
com.myflashlab.air.extensions.admob::AdMob()
com.myflashlab.air.extensions.admob::AdMob$/init()
```

**Comment by AlexUrrutia** [comment]
**New findings:**  I tried to compile with Animate CC and it works on 4.4, I was using IntelliJ and the compiled apk won't start up on Android 4.4, so what might be the reason? any ideas on this?
Also, if the device running Android 4.4 don't have play services, AdMob won't show ads, and Google Sign in doesn't work, thanks

**Comment by myflashlab** [comment]
It seems like there must be something wrong happening on your compilation. but to be saying, we are using IntelliJ and have not faced any such problems. Anyhow:

> We have updated the ANE to the latest SDK and a LOT has changed. for example like buttons and app invites have been deprecated but we have now added the GameRequest feature. Moreover, we have re-wrote the whole Actionscript part to be easier to work with. Please update yourself to the latest version and see how it goes. If you are still encountering any problem, please feel free to open a new issue and ask your questions. And by the way, when updating your app with the new ANE, make sure to read and follow the [new wiki documentations](https://github.com/myflashlab/facebook-ANE/wiki). Moreover, the asdoc has also moved to this package: http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/fb/package-detail.html

Also make sure to read the changelog to know what changes you need to make to your manifest. xml file.

**Comment by hengway1989** [comment]
I have exactly issue like above, but after I downgrade androidSupport-V27.0.2-full.ane to androidSupport-V26.0.2-full.ane, the issue gone.

**Comment by myflashlab** [comment]
@hengway1989 we suggest using the latest version of AndroidSupport ANE, which is 27.0.2 at the moment. But, try adding the following attribute to your android ```<application ``` tag:

```xml
android:name="android.support.multidex.MultiDexApplication"
```
