### ISSUE TITLE
ios app crash

### ISSUE THREAD

**Issue by 4malik** [myflashlab/facebook-ANE#121]
Hello got next problem.
After success sign in i call 
``` javascript
static public function getProfile():void {
	Main.addRecord("FacebookManager getProfile");
	FB.graph.addEventListener(FBEvent.GRAPH_RESPONSE, getProfile_eventHandler);
	FB.graph.addEventListener(FBEvent.GRAPH_RESPONSE_ERROR, getProfile_eventHandler);
	FB.graph.call("https://graph.facebook.com/v2.8/me", URLRequestMethod.GET, new URLVariables("fields=id,birthday,email,first_name,last_name,name,picture&metadata=0"));
	Main.addRecord("FacebookManager getProfile call");
}
```

Main.addRecord - my text log.

On Development mode all warkds fine and i got next
![img-0879](https://user-images.githubusercontent.com/30479942/36897394-ce91a086-1e2f-11e8-96c3-d0c37779ccd3.JPG)

But on Production i got crash after FB.graph.call (sorry for bad quality - that a result of screen record)
![img-0881](https://user-images.githubusercontent.com/30479942/36897415-e47ca27e-1e2f-11e8-9f51-f242621a85ce.jpg)

One more strange thing is message from override air (on screenshot): FacebookANE(FbAppDelegate) initWithAlert. Tried to find out what is that but couldn't.

Air 27
updated all libs
used AN ELab
Ios 11.2.6

Thanks for help

**Comment by myflashlab** [comment]
1. Are you sure you are using a correct ```FB.hashKey``` on your production?
2. will you be able to send us the crash log also? use AndroidStudio/logcat. That information can better help us see when the problem happens on the native side.

**Comment by myflashlab** [comment]
oops, you said iOS... ignore my last message.

**Comment by 4malik** [comment]
i'm developing under windows. so can't get how to give you xcode crash logs.

**Comment by myflashlab** [comment]
We have updated the ANE to the latest SDK and a LOT has changed. for example like buttons and app invites have been deprecated. Moreover, we have re-wrote the whole Actionscript part to be easier to work with. Please update yourself to the latest version and see how it goes. If you are still encountering any problem, please feel free to open a new issue and ask your questions. And by the way, when updating your app with the new ANE, make sure to read and follow the [new wiki documentations](https://github.com/myflashlab/facebook-ANE/wiki). Moreover, the asdoc has also moved to this package: http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/fb/package-detail.html
