### ISSUE TITLE
Facebook invite not working

### ISSUE THREAD

**Issue by babakasol** [myflashlab/facebook-ANE#123]
using facebook ane 4.22.5 

## Environment ##
* AIR SDK Version:  28

## Problem Description ##
when calling the FB.appInvite function nothing is happening and even no status or error event

## Steps to Reproduce ##
logged in to app through facebook login clicked on facebook invite -> no output

**Comment by myflashlab** [comment]
Facebook invite is deprecated. The closest solution is sending Game Requests. We will be releasing Facebook ANE V4.30.0 by tomorrow. That version should have new features.
