### ISSUE TITLE
ios app crash (2)

### ISSUE THREAD

**Issue by 4malik** [myflashlab/facebook-ANE#124]
Hi. Opened again [](https://github.com/myflashlab/facebook-ANE/issues/121)
So the problem is: crash with facebook sign in in PRODUCTION. in Development mode it works fine.

With help of your support I could understand how to collect logs from device.
I attached logs here.

appId - com.elimotoday.driver
699 string: (com.elimotoday.driver); pid: 3563> crashed

[log1.txt](https://github.com/myflashlab/facebook-ANE/files/1886514/log1.txt)

**Comment by myflashlab** [comment]
Sorry for the late reply, it's just that the problem does not seem to be with the ANE. We are not able to duplicate this problem. we even tried with iOS 11.3 (noticed that you are using this version when checked your logs) adhoc build and it's still working just fine. Also, no other devs seem to be facing a similar problem. Besides, when the ANE starts initializing, it sends out some debugging notes we have put inside the ANE. They all include ```FB_ANE``` in their message. but your log does not contain ANY of such messages. This means that the app has stopped even before the ANE initializes. I think you must try to find the problem somewhere else. The first thing we would suggest is to make sure you are using the latest AIR SDK and while doing that, make sure you are using the correct FB framework files.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
