### ISSUE TITLE
framework file not packaged with ipa file

### ISSUE THREAD

**Issue by Xgamefactory** [myflashlab/facebook-ANE#125]
Hi,
We did exactly as your described copying framework file under stub folder inside air sdk
ipa file generated with no errors but there is no framework file inside the size of ipa file is same as before. Is there any additional arguments to pass adt ipa generation command ?

We are using lates mac os and ios sdk

**Comment by myflashlab** [comment]
static frameworks are not required to be added into .ipa. The dynamic ones need this. So as long as you are not seeing the ```ld:framework blablabla not found``` when compiling your project, you're fine.

**Comment by Xgamefactory** [comment]
yes but we built ane with here maps sdk which is dynamic framework approximately 500mb

**Comment by myflashlab** [comment]
I'm not sure what the question is. facebook iOS SDK is provided with static libraries and we are using these static libs for the ANE. just copying them to the ```lib/aot/stub``` folder of your AIR SDK is good enough.
