### ISSUE TITLE
iOs Facebook login window closes when DynamicLink is notified.

### ISSUE THREAD

**Issue by PippoApps** [myflashlab/facebook-ANE#128]
## Environment ##
* iOS Version: 9.3.5 and 10.3.3
* AIR SDK Version: 29

## Problem Description ##
Initialize all ANEs. Facebook login window is triggered.
As soon as empty dynamic link is received, facebook login window closes and a cancel event is triggered (around 20 seconds).

## Steps to Reproduce ##
Start app, wait for facebook login window to appear, do nothing, wait between 20 to 22 seconds, as soon as empty default DynamicLink is received, facebook window gets closed and a CANCEL is triggered.

Here is trace output:

FB_ANE> login with read permissions
40 [_PippoFlashBase]		Calling on all classes: onInit1()
**here facebook login window arrives
after 20 secs following trace comes out
and facebook window closes triggering a user cancel event**
FB_ANE> checkOverride_openURLOptions
FB_ANE> com.yappingmoose.buncobonko://google/link/?dismiss=1&is_weak_match=1
44 [ANEFacebook]		Login canceled by user.
45 [MainApp]		Facebook ANE login canceled: Login Cancelled by User

**Comment by myflashlab** [comment]
Something I don't understand is that why a dynamicLink would be invoked at all when user is loggin in facebook window!

Another confusing thing for me is that what is happening in those 20 seconds that you are waiting? the dynamiclink would be invoked if you are trying to open the app with a deep link, right?

Can you make a video screening clip to show us what is happening actually?

**Comment by PippoApps** [comment]
I have added 2 videos of the event.
[app schema]://google/link/?dismiss=1&is_weak_match=1
basically is a default event called by DynamicLinks when there is no dynamic link on first App launch. As explained by a google engineer:
![image](https://user-images.githubusercontent.com/29799572/39376801-38cf35e0-4a53-11e8-851b-266cf44dfe3c.png)

For some reason when FB_ANE receives it, closes fb login screen sending a cancel event.

Here's 2 videos:
https://drive.google.com/open?id=18Bkv7KOPAAT5KE4kTLEKoGLP3K2F3x17
https://drive.google.com/open?id=1t4oCBp_7ApSUBgZvgdNGsedEawqbpgsm

**Comment by PippoApps** [comment]
This thread explains the issue: https://github.com/firebase/firebase-ios-sdk/issues/233
Even though obviously is a different context.

**Comment by myflashlab** [comment]
Thanks for the videos, we were able to duplicate the problem but it is happening ONLY in debug mode and when we tested the release version, it was not closing the login window and everything was working as expected. However, we'll be sending you another version of hot fix to see if we can stop this even on the debug builds... please wait for that.

**Comment by PippoApps** [comment]
Thank you. Yeah since I found this I tested only debug builds... I'll come back to you asap.

**Comment by PippoApps** [comment]
Since I can anyway post a release with a workaround, the Android bug is more urgent since it crashes the app completely: https://github.com/myflashlab/facebook-ANE/issues/129

**Comment by myflashlab** [comment]
We have put a check for facebook to make sure this is not happening, it really feels like you are using an old version! we are not seeing this problem anylonger. anyhow, please test this version in debug and send us the logs: [facebook.ane.zip](https://github.com/myflashlab/facebook-ANE/files/1958510/facebook.ane.zip)

**Comment by PippoApps** [comment]
Thank you very much. I had the same feeling, that's why I deleted any trace of the old ane and tried to clear all animate/air caches. I will try to export from a different, virgin VM.

**Comment by PippoApps** [comment]
Yes!
Latest facebook ANE downloaded from here: https://github.com/myflashlab/facebook-ANE/issues/128#issuecomment-385144691 fixed this issue.

Is this the debug trace output with the info you added?
435 [ANEFacebook]		Calling Facebook.auth.login()
436 [TutorialMan]		Activated DPI compliant sizer. Device DPI:480, 72dpi size:20, computed size:50
437 [ContentBoxTouch]		Activating Touch Scroll with Tap prevention
438 [ContentBoxTouch]		Activating Touch Scroll with Tap prevention
439 [ContentBoxTouch]		Activating Touch Scroll with Tap prevention
440 [UAir]		Application SLEEP
FirebaseCore> disconnectFromGoogleApi
FirebaseCore> connectToGoogleApi > Connecting to google API
FirebaseCore> connectToGoogleApi > called GOOGLE_API_CLIENT.connect()
441 [UAir]		Application ACTIVE
FirebaseInvites> onActivityResult
FB_ANE> onActivityResult, requestCode: 64206 | resultCode: -1
$recentlyDeclined: 
$recentlyGranted: public_profile,publish_actions,user_friends,email
token: EAANyUXx5cIQBAPtPiWze4cs8xq3ex3HWIvwbTnAr4yBZAm5zR6IPGjqnP9chdyjpXsZCnXdf52TrlUVAjNOInb8ahHZAdZB6jcftNnEPrFZBfCoBLPZCgL3jPNfWm9ZCeVuEzqgNva7HYZAZAxPepKumfYQSlHQvk7eWc5hRjdOSYQiHow8D5g2xtH1GdLteiXK4fOchS1CP66MdOpMqIAGMXAD7sDl1TG7jg4ipEb1iZAsgZDZD
userId: 10154671859847269
declinedPermissions: 
grantedPermissions: public_profile,publish_actions,user_friends,email
expiration: Thu Jun 28 2018
lastRefresh: Sun Apr 29 2018
442 [MainApp]		Login successful with token: xx
443 [MainApp]		Loading user data from: https://graph.facebook.com/v2.5/me/?fields=id,name,email,picture.type(large)&access_token=xx
FirebaseCore> onConnected > GOOGLE_API_CONNECTION_SUCCESS

**Comment by myflashlab** [comment]
good, now, please get back to us about the Android problem also. Thanks.

**Comment by PippoApps** [comment]
On another note, latest ANELabs is 1.1.16, and exports facebook ane 4.30.0.
No new ANELabs or facebook ane versions are reported.
![image](https://user-images.githubusercontent.com/29799572/39406264-6373f6e8-4bb4-11e8-919e-915ffab7cdc0.png)

**Comment by PippoApps** [comment]
Ops sorry, this IS the android issue I posted in the wrong thread. Moving it.

**Comment by myflashlab** [comment]
Of course, we have not yet exported the new version into ANELAB channel. However, if you replace with [the latest V4.30.2](https://github.com/myflashlab/facebook-ANE/files/1958510/facebook.ane.zip) manually, ANELAB will see that:

<img width="753" alt="screen shot 2018-04-29 at 3 57 25 pm" src="https://user-images.githubusercontent.com/1692948/39406323-113f55f4-4bc6-11e8-8ed0-046888d0cb86.png">

**Comment by myflashlab** [comment]
As you see on the above screenshot, if you hit the "update" button, ANELAB will remove V4.30.2 and will replace it with the latest one known to ANELAB which is V4.30.0

On the other hand, if you click the "re-run-setup" button, ANELAB WILL install the hot version again on your project. We have made sure ANELAB works like this so devs can easily test hot versions we would release in GitHub for test versions :)

P.S   I know, it would have been better to call the ```UPDATE``` button ```DOWNGRADE``` :laughing:

**Comment by PippoApps** [comment]
eheheh
4.30.2 did fix the issue both in debug and adhoc! Thank you. This is great.
I see we both work on Sunday :)
I am going to export new builds, make my boss happy then go out and get drunk.
Have a great day!

**Comment by myflashlab** [comment]
For that, please contact us through https://www.myflashlabs.com/contact/
I know the website boys were talking about that the other day. talk with them about this
