### ISSUE TITLE
Logging in FB consistently crashes on Android: Didn't find class "bolts.AppLinks"

### ISSUE THREAD

**Issue by PippoApps** [myflashlab/facebook-ANE#129]
## Environment ##
* Android API Version: 23 - 6.0.1
* AIR SDK Version: 29.0.0.122

## Problem Description ##
Same code working on iOS.
Once I hit CONTINUE on facebook login screen, app crashes.
Also Firebase ANE are there. I tried not initializing firebase, same behavior.
This is the stack trace from firecase crash:

Exception java.lang.NoClassDefFoundError: Failed resolution of: Lbolts/AppLinks;
com.facebook.appevents.internal.SourceApplicationInfo$Factory.create (SourceApplicationInfo.java:131)
com.facebook.appevents.internal.ActivityLifecycleTracker.onActivityCreated (ActivityLifecycleTracker.java:131)
com.facebook.appevents.internal.ActivityLifecycleTracker$1.onActivityCreated (ActivityLifecycleTracker.java:77)
android.app.Application.dispatchActivityCreated (Application.java:217)
android.app.Activity.onCreate (Activity.java:945)
com.facebook.CustomTabActivity.onCreate (CustomTabActivity.java:46)
android.app.Activity.performCreate (Activity.java:6308)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1107)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2400)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2511)
android.app.ActivityThread.-wrap11 (ActivityThread.java)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1360)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:5480)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)
arrow_drop_down

Caused by java.lang.ClassNotFoundException: Didn't find class "bolts.AppLinks" on path: DexPathList[[zip file "/data/app/air.com.yappingmoose.buncobonko-1/base.apk"],nativeLibraryDirectories=[/data/app/air.com.yappingmoose.buncobonko-1/lib/arm, /data/app/air.com.yappingmoose.buncobonko-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]

## Known Workarounds ##
none

**Comment by PippoApps** [comment]
On this page: https://stackoverflow.com/questions/27915973/app-crashes-when-tested-on-mobile-android
It seems solution is:
Problem solved at my side. download bolts-android1.1.2 and put into \libs folder. then open the project properties-> java Build Path-> Project tab , Add Facebook SDK. (Facebook SDK libs must be attached with project

I am using ANELab 1.1.16

**Comment by myflashlab** [comment]
This is weird because since FB V4.27.0, Facebook has removed that from the dependencies! Today we noticed that although they removed it in documentations, they are still using it on GitHub. Anyhow, please replace your ANE with this hot version and see if it's fixed. If fine, we'll release it without the demo dialog inside the ANE. Thanks. 
[facebook.ane.zip](https://github.com/myflashlab/facebook-ANE/files/1957323/facebook.ane.zip)

**Comment by PippoApps** [comment]
Thank you! I'll try and let you know asap.

**Comment by PippoApps** [comment]
Sorry, bug is still there, in both debug and release.
Stack trace error sent to firebase crash looks like slightly different:

Exception java.lang.NoClassDefFoundError: Failed resolution of: Lbolts/AppLinks;
com.facebook.appevents.internal.SourceApplicationInfo$Factory.create (SourceApplicationInfo.java:131)
com.facebook.appevents.internal.ActivityLifecycleTracker.onActivityCreated (ActivityLifecycleTracker.java:131)
com.facebook.appevents.internal.ActivityLifecycleTracker$1.onActivityCreated (ActivityLifecycleTracker.java:77)
android.app.Application.dispatchActivityCreated (Application.java:195)
android.app.Activity.onCreate (Activity.java:922)
com.facebook.CustomTabActivity.onCreate (CustomTabActivity.java:46)
android.app.Activity.performCreate (Activity.java:6251)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1107)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2369)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2476)
android.app.ActivityThread.-wrap11 (ActivityThread.java)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1344)

Here's log cat recording from app chrashed:
- debug version
- firebase not initialized

https://drive.google.com/open?id=1bKfGSdJaClMW_hId03-UEfCAbVASRZbD

**Comment by PippoApps** [comment]
This seems to be the interesting part in logcat:

04-28 19:53:24.015 606:624 I/art]
Explicit concurrent mark sweep GC freed 48426(2MB) AllocSpace objects, 18(4MB) LOS objects, 33% free, 20MB/31MB, paused 1.251ms total 113.372ms

[04-28 19:53:24.258 606:620 W/ActivityManager]
  Force finishing activity air.com.yappingmoose.buncobonko/.AppEntry

[04-28 19:53:24.259 606:620 I/ActivityManager]
Killing 7411:air.com.yappingmoose.buncobonko/u0a139 (adj 2): user request after error

[04-28 19:53:24.288 606:2272 I/WindowState]
WIN DEATH: Window{1ac9dfc u0 air.com.yappingmoose.buncobonko/air.com.yappingmoose.buncobonko.AppEntry}

[04-28 19:53:24.288 606:2272 W/WindowManager]
Force-removing child win Window{fa4a39 u0 SurfaceView} from container Window{1ac9dfc u0 air.com.yappingmoose.buncobonko/air.com.yappingmoose.buncobonko.AppEntry}

[04-28 19:53:24.290 606:2272 W/WindowManager]
Force-removing child win Window{d2c50f5 u0 SurfaceView} from container Window{1ac9dfc u0 air.com.yappingmoose.buncobonko/air.com.yappingmoose.buncobonko.AppEntry}

[04-28 19:53:24.298 606:1233 W/WindowManager]
Failed looking up window
java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@fb71c01 does not exist
	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8736)
	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8727)
	at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1209)
	at android.os.BinderProxy.sendDeathNotice(Binder.java:558)

[04-28 19:53:24.298 606:1233 I/WindowState]
WIN DEATH: null

[04-28 19:53:24.299 606:1486 W/WindowManager]
Failed looking up window
java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@b8a3c85 does not exist
	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8736)
	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8727)
	at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1209)
	at android.os.BinderProxy.sendDeathNotice(Binder.java:558)

**Comment by myflashlab** [comment]
This shuldn't be happening! I double checked and we're sure the bolt library is added to the ANE. Are you sure you are using the new ANE? To check that, just open ANELAB and it should list the ANE name as ```Facebook V4.30.1``` you see that?

FYI: Considering that you are using the ANELAB, it's normal that the demo dialog is not showing up.

We're not able to duplicate the problem and we don't see a crash. will you send me your .apk file to run and see the error?

**Comment by PippoApps** [comment]
Yes!
Latest facebook ANE downloaded from here: #128 (comment) fixed this issue.
Thank you very much for your help.

Is this the debug trace output with the info you added?
435 [ANEFacebook]	Calling Facebook.auth.login()
440 [UAir]	Application SLEEP
FirebaseCore> disconnectFromGoogleApi
FirebaseCore> connectToGoogleApi > Connecting to google API
FirebaseCore> connectToGoogleApi > called GOOGLE_API_CLIENT.connect()
441 [UAir]	Application ACTIVE
FirebaseInvites> onActivityResult
FB_ANE> onActivityResult, requestCode: 64206 | resultCode: -1
$recentlyDeclined:
$recentlyGranted: public_profile,publish_actions,user_friends,email
token: xx
userId: 10154671859847269
declinedPermissions:
grantedPermissions: public_profile,publish_actions,user_friends,email
expiration: Thu Jun 28 2018
lastRefresh: Sun Apr 29 2018
442 [MainApp]	Login successful with token: xx
