### ISSUE TITLE
Info on ShareLinkContent

### ISSUE THREAD

**Issue by PippoApps** [myflashlab/facebook-ANE#131]
Hello there,
I can't find any info on Facebook docs regarding parameters used in ShareLinkContent (contentUrl, quote, hashtag, etc.).
Do you have any suggestion?
Thank you very much

**Comment by myflashlab** [comment]
https://developers.facebook.com/docs/reference/android/current/class/ShareContent.Builder/  
http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/fb/ShareContent.html

**Comment by PippoApps** [comment]
Thank you.
