### ISSUE TITLE
Suggestion to debug Facebook received invitations?

### ISSUE THREAD

**Issue by PippoApps** [myflashlab/facebook-ANE#133]
I am having an issue debugging on invoke in Facebook ANE. When I install myself a debug version of app on the device, facebook still sends me to app store, and the "OPEN" button is not available, but I have to download AppStore version. 
Did you ever face this situation? Can you invoke a development version of app using facebook invoke? 
Thank you

**Comment by myflashlab** [comment]
How about the adhoc version? if it's installed on your device?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
