### ISSUE TITLE
Game requests on device do not launch app on either Android or iOS

### ISSUE THREAD

**Issue by PippoApps** [myflashlab/facebook-ANE#134]
I am not sure wether this could be an ANE issue or a facebook app misconfiguration issue. Though, using firebase invitations it all works well.

When I send a GameRequest, it gets correctly sent, but this is the outcome:
iOS browser click on invite: open app store page from which I can install or open app (doen't open app directly).
iOS app: opens app center and says game does not exist for device
Android browser: notificaitons are not shown in feed (probably facebook choice for Android Chrome)
Android app: opens app centre page, but from there I can't do anything.

In any case, the app is not launched albeit installed. But from facebook docs:
"Game requests are one of Facebook's primary social channels, used for direct one-to-one communication between people. Requests on mobile are especially powerful as they generate a push notification through the Facebook app, and open directly into your game on either iOS or Android."

Thanks for your help

**Comment by myflashlab** [comment]
It's very probable that there's something wrong on the facebook configurations because this feature has been under many tests. https://github.com/myflashlab/facebook-ANE/wiki/05.-Game-Requests#receiving-game-requests

Maybe your Facebook app version on your device is too old? just a guess.

**Comment by PippoApps** [comment]
Thank you I'll check that.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
