### ISSUE TITLE
Auth.logout() not working on Android.

### ISSUE THREAD

**Issue by PippoApps** [myflashlab/facebook-ANE#135]
Android with or without Facebook app installed.
After first user login, calling logout(), and then login() again (even with a long timeout), ANE re-logins the last user.

**Comment by myflashlab** [comment]
This is by design I believe. you should use graph to logout fully if I'm not wrong... https://stackoverflow.com/questions/29305232/facebook-sdk-4-for-android-how-to-log-out-programmatically

**Comment by PippoApps** [comment]
ANE reports me as logged in, and returns my token. I prompt to change user, and before calling Facebook.auth.logout() I call graph API to logout from SDK 4 as in the link you kindly posted here.
Alas, SDK returns that I do not have an active token.

Calling graph, I get this feedback:
459 [ANEFacebook]		On android logout  {
   "error": {
      "message": "An active access token must be used to query information about the current user.",
      "type": "OAuthException",
      "code": 2500,
      "fbtrace_id": "GuA2/nFbWNp"
   }
}
https://graph.facebook.com/v2.5/me/permissions/?access%5Ftoken=[obscured]

Although I am already logged in and my token is returned by ANE beforehand. There is no parameter in Graph to set active token.

I have followed the info in link and call this method:
Facebook.graph.call("https://graph.facebook.com/v2.5/me/permissions/", URLRequestMethod.DELETE, new URLVariables(), onAndroidLogout);

**Comment by myflashlab** [comment]
I'm pretty sure this used to work fine before, I don't know which version and which graph version but I remember that code used to work! It seems like a Facebook Graph bug. 

Even when testing their graph explorer, it is working correctly. check this out https://developers.facebook.com/tools/explorer/?method=DELETE&path=me%2Fpermissions&version=v2.11 but when I use it in the app, it doesn't work.

So maybe this is a Facebook bug, or maybe AdobeAIR SDK bug with the ```DELETE``` request method... I don't know.

Anyhow, instead of using the ```DELETE``` request method, just use ```POST``` and then fake simulate the delete operation by passing a ```method=delete```. do it like below and you'll be fine.

```actionscript
Facebook.graph.call(
	"https://graph.facebook.com/v2.11/me/permissions",
	URLRequestMethod.POST,
	new URLVariables("method=delete"),
	function ($dataStr:String, $graphRequest:String):void
	{
		trace($graphRequest);
		trace($dataStr);
				
		Facebook.auth.logout();
		_accessToken = null;
				
		trace("user is logout");
	}
);
```

**Comment by PippoApps** [comment]
It does work, but it doesn't really log me out of facebook.
Just opens the permissions confirm page, but doesn't let me change user.
Should I remove single sign in?

**Comment by PippoApps** [comment]
It works now. but to completely logout user from app, with Single Sign On there are other steps involved:

1 - Once you retrieve user token ask user wether he wants to proceed with the logged in user.
![image](https://user-images.githubusercontent.com/29799572/40191511-0d95e5d6-5a02-11e8-91e7-9e63dc5d8a9d.png)
Hitting PROCEED you just continue using stored token and data.
Hitting CHANGE USER another prompt is required, sinc ein order to logout user from app, the same user must be logged out from Facebook app (if installed) or browser.

2 - Ask user to open app/browser to logout:
![image](https://user-images.githubusercontent.com/29799572/40191588-446f8ba2-5a02-11e8-876a-57506a7b1809.png)
If so, call graph API in order to logout user from facebook. On callback, logout user also from ANE calling Facebook.auth.logout(), and then just call in AIR the url "https://www.facebook.com" and either browser or facebook app will be opened (on iOS, there will be a button to go back to app on the top left. On Android, user has to go back to app manually.). In the same call, also open a prompt in AIR, that will give user the option to call Facebook.auth.login() again:
![image](https://user-images.githubusercontent.com/29799572/40191750-a8bcc110-5a02-11e8-94ad-80860c23192c.png)
Once the user is back to App (calling facebook url moved app to background), hitting on LOGIN the login process can start again. If user has logged out in app/browser, new login data will be requested, otherwise he will be again logged in as the same user.

Hope this saved some headache.

**Comment by myflashlab** [comment]
Loved your detailed tutorial, I'm sure others will find this VERY useful. Thanks.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
