### ISSUE TITLE
Crash on ios

### ISSUE THREAD

**Issue by ikuprin** [myflashlab/facebook-ANE#136]
Ios devices crashes when application come back in foreground after granting permissions in facebook application.

What is more: 
1. Small application (just code from examples) with all needed anes and functionality with the same manifest works as expected, but "big" crashes.
2. If I use ane from distriqt - it works normally, but if I just add to manifest this string 
    `<extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>`
application crashes after come back in foreground...

**Comment by myflashlab** [comment]
Read about these conflicts here, see if you can relate: https://github.com/myflashlab/Firebase-ANE/issues/163

**Comment by ikuprin** [comment]
Exact... overrideAir conflicts with appsflyer ane. Thanks for quick response!
