### ISSUE TITLE
Facebook app review

### ISSUE THREAD

**Issue by hengway** [myflashlab/facebook-ANE#139]
Hi, I am still using version V4.22.3 FB, and recently FB keep hint me to review my app to access below 4 info:
user_friends
user_link
user_gender
user_age_range

but i never use above info except email, so can I ignore the message, or should I upgrade to latest ANE, and select only the permission I need?

Thank you

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
