### ISSUE TITLE
AIR startup penalty

### ISSUE THREAD

**Issue by ikuprin** [myflashlab/facebook-ANE#141]
After implementing anes as described in your documentation I got significant penalty on AIR startup. Google Play  Console showed me in Pre-launch report that 8 of 10 test devices has performance warnings,..

So, I started looking for reason. Device: Galaxy A7 2017. AIR SDK 30.

Scout says: your AIR startup spent 9 seconds, and preparing ActionScript Bytecode - 2 seconds.
I made clean application that contains just extentions in android manifest and after some manipulations found that facebook-ANE + androidSupport-full spent almost 7 seconds for AIR startup and almost 1,5 seconds to preparing bytecode...

I repeated experiment with another facebook ane packets for AIR startup:
Distriqt with dependencies - 5 seconds
Marpies with dependencies - 4,5 seconds
Freshplanet with Distriqt appcompat libraries - 4 seconds
Milkman GoViral (has'nt dependencies) - 0,8 seconds.

After experiments I tried to combine anes for better performance. The best way was to use GoViral, but it conflicts with your Firebase ane. 
After some time I found the most acceptable combination in my situation - your Facebook-ANE without your androidSupport + 4 Distriqt dependencies ane: V4, CustomTabs, CardViewV7, AppCompatV7. This combination give me just 3,5 seconds penalty on AIR startup and not sufficient time of bytecode preparing.

All above - it's just info. Maybe I doing smth wrong, but maybe this info can help you to improve your product.

**Comment by myflashlab** [comment]
Thanks for the details, we have also recently noticed that the new versions of AndroidSupport ANE is taking longer to init. We are currently working on splitting that ANE into smaller parts so users don't have to include the whole package if not required.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
