### ISSUE TITLE
facebook Game request

### ISSUE THREAD

**Issue by BenQ12345** [myflashlab/facebook-ANE#142]
sir,
      I am using paid facebook Ane When I send a GameRequest, it gets correctly sent, with requestRecipients and requestid but notification message not send to another person. please send the solution for it.sir you are taking to much time to send reply.

**Comment by myflashlab** [comment]
Hi there, Before anything, I must say that I have been looking up your user name so I can somehow tell you that your emails are received but we are not able to reply them back! all emails being replied to your address just bounces back and is never sent through. I'm pretty sure there's something wrong with your email server or something We have been trying to send replies to this address with no luck! ```nikhilreddy590 (at) gamil com```. Then we noticed **gamil**, so thought that it must be a misspell. so we tried sending replies to ```nikhilreddy590 (at) gmail com``` but again it didn't go through! Thought to clear this with you first since you said that it takes us too much time to reply back :)

About your question, please note that game requests will be shown to users devices only if your facebook application is expecting that platform. For example, if a user is logged into her facebook account on her Android and iOS devices and also logged in via desktop browser, when you send a game request and your facebook settings are only set for Android, she will see the notification only on her Android device. This is how Facebook works by design. Now, try adding the iOS platform and send another game request. user will see it on iOS now.

**Comment by nikhilreddy123456** [comment]
I am Sorry for my inconvenience. Thank you for your reply

**Comment by nikhilreddy123456** [comment]
This is my facebook setting for Android but still i am not getting the output.
![photo](https://user-images.githubusercontent.com/39688242/43353135-01a3a2ca-924e-11e8-9621-439673d500cd.png)

**Comment by myflashlab** [comment]
Well, by default, AIR apps begin with ```air.``` but you have set your google package name as ```com.HFG.SpecialSquad```, which does not seem correct.

**Comment by nikhilreddy123456** [comment]
sir, 
    I changed Google package name change to air.com.HFG.SpecialSquard but still it is not working. 


function sendGameRequest():void
		{
	
			var requestContent:GameRequestContent = new GameRequestContent();
			requestContent.message = "I have successfully accomplished an Achievement Amazingly Fun!! :)";
			
			Facebook.games.requestDialog(requestContent, function ($isCanceled:Boolean, $error:Error, $result:Object):void
			{
				if($error)
				{
					notify("Facebogames.requestDialog $error: " + $error.message);
				}
				else
				{
					if($isCanceled)
					{
						notify("Facebogames.requestDialog canceled");
					}
					else
					{
						notify("Facebogames.requestDialog sent");
						if($result)
						{
							notify("facebook request sent:"+JSON.stringify($result));
							
						}
					}
				}
			});
		}

------------------------------xml-----------------------------------------------------------
 <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="\ fb1832433357043639"/>
			   <intent-filter>
                    <action android:name="android.intent.action.VIEW" />
                    <category android:name="android.intent.category.BROWSABLE" />
                    <category android:name="android.intent.category.DEFAULT" />
                    
                    <data android:scheme="air.com.HFG.SpecialSquad" />
                </intent-filter>
			    
        <activity
                android:name="com.facebook.FacebookActivity"
                android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
                android:theme="@android:style/Theme.Translucent.NoTitleBar"
                android:label="My App Name" />
				
				
				
				
				
		       <activity android:name="com.facebook.CustomTabMainActivity" />
               <activity android:name="com.facebook.CustomTabActivity" android:exported="true">
                <intent-filter>
                    <action android:name="android.intent.action.VIEW" />
                    <category android:name="android.intent.category.DEFAULT" />
                    <category android:name="android.intent.category.BROWSABLE" />
                    <data android:scheme="fb1832433357043639" />
                </intent-filter>
            </activity>
			<provider
                android:authorities="com.facebook.app.FacebookContentProvider1832433357043639"
                android:name="com.facebook.FacebookContentProvider"
                android:exported="true" />

**Comment by nikhilreddy123456** [comment]
============xml======================
<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="\ fb1832433357043639"/>
			   <intent-filter>
                    <action android:name="android.intent.action.VIEW" />
                    <category android:name="android.intent.category.BROWSABLE" />
                    <category android:name="android.intent.category.DEFAULT" />
                    
                    <data android:scheme="air.com.HFG.SpecialSquad" />
                </intent-filter>
			    
        <activity
                android:name="com.facebook.FacebookActivity"
                android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
                android:theme="@android:style/Theme.Translucent.NoTitleBar"
                android:label="My App Name" />
		<activity android:name="com.facebook.CustomTabMainActivity" />
               <activity android:name="com.facebook.CustomTabActivity" android:exported="true">
                <intent-filter>
                    <action android:name="android.intent.action.VIEW" />
                    <category android:name="android.intent.category.DEFAULT" />
                    <category android:name="android.intent.category.BROWSABLE" />
                    <data android:scheme="fb1832433357043639" />
                </intent-filter>
            </activity>
			<provider
                android:authorities="com.facebook.app.FacebookContentProvider1832433357043639"
                android:name="com.facebook.FacebookContentProvider"
                android:exported="true" />

**Comment by nikhilreddy123456** [comment]
=========xml=================

**Comment by nikhilreddy123456** [comment]
sir, please send the reply for Fb app request .Waiting for your reply

**Comment by nikhilreddy123456** [comment]
please send reply sir

**Comment by nikhilreddy123456** [comment]
sir waiting for your reply.

**Comment by nikhilreddy123456** [comment]
waiting for your reply.....

**Comment by nikhilreddy123456** [comment]
Waiting for ur reply.....

**Comment by nikhilreddy123456** [comment]
4 days back i send the message till now no response from your side.

**Comment by myflashlab** [comment]
hmm, :thinking: don't know what to suggest. could be many reasons, check this out for example. https://stackoverflow.com/questions/40448506/why-facebook-game-request-does-not-showing-up-on-recipient-profile

Another thing I should add that it seems like game requests would work normally if your app on Facebook console is categorized as a ```game```.

Other users are using this feature with no problem so, you need to try and provide more information for us to be able to better advice.

**Comment by nikhilreddy123456** [comment]
Hi, from my side everything is correct but my app is in Beta testing because of this game Request won't work.
![ipmsgclip_r_1533538420_0](https://user-images.githubusercontent.com/39688242/43701448-d6f5bdc4-9973-11e8-9b6b-7e842f06ff36.png)

**Comment by myflashlab** [comment]
Is notification delivered successfully on the iOS side?

**Comment by nikhilreddy123456** [comment]
Preparing for Android only.

**Comment by nikhilreddy123456** [comment]
Hi, from my side everything is correct but my app is in Beta testing because of this issue game Request won't work. Is this reason for this issue.

**Comment by myflashlab** [comment]
We confirm that the game request is delivered correctly to both, Android and iOS devices. We don't see a problem at all.

Just some thoughts but try logging out from your native facebook app **and also** logout from your facebook account on your device's browser. then try again and see how it goes.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
