### ISSUE TITLE
Share Dialog to share OpenGraph Story

### ISSUE THREAD

**Issue by Pavlysha** [myflashlab/facebook-ANE#144]
I use latest paid version of ane. Can I open Share Dialog to share OpenGraph Story?

Here is link to Facebook api

https://developers.facebook.com/docs/sharing/reference/share-dialog

**Comment by myflashlab** [comment]
Of course, check this out: https://github.com/myflashlab/facebook-ANE/wiki/03.-Share-Dialog

**Comment by Pavlysha** [comment]
I saw this wiki-page, but how can I share OpenGraphStory via Share Dialog?
I need to share exactly OpenGraphStory and I dont know how to do it, because Facebook.share.shareDialog can share only link.

**Comment by myflashlab** [comment]
Aha, you need "Open Graph Story" sharing. That is not yet implemented into the ANE. we'll consider to support that in future versions. If you need it fast and badly, you can [contact us](http://www.myflashlabs.com/contact/) to speed up the process.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
