### ISSUE TITLE
Could not find class 'android.view.autofill.AutofillManager'

### ISSUE THREAD

**Issue by Pavlysha** [myflashlab/facebook-ANE#146]
I use latest paid version of ane and latest version of androidSupport.ane and overrideAir.ane
AIR SDK Version: 30

I always getting this error when I try to login:
```
09-20 11:52:37.949: E/dalvikvm(2184): Could not find class 'android.view.autofill.AutofillManager', referenced from method com.facebook.internal.Utility.isAutofillAvailable
09-20 11:52:37.949: W/dalvikvm(2184): VFY: unable to resolve const-class 2880 (Landroid/view/autofill/AutofillManager;) in Lcom/facebook/internal/Utility;
09-20 11:52:37.949: W/dalvikvm(2184): VFY: unable to resolve const-class 2880 (Landroid/view/autofill/AutofillManager;) in Lcom/facebook/internal/Utility;
09-20 11:52:38.069: E/GooglePlayServicesUtil(2184): The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.
09-20 11:52:38.089: E/GooglePlayServicesUtil(2184): The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.
```

**Comment by myflashlab** [comment]
1. while using the latest version of AIR SDK, also make sure you are setting the AIR version number to that also. ```<application xmlns="http://ns.adobe.com/air/application/30.0">```
2. Add multidex to your app. to do that, simply add the following attribute to your Android's ```<application``` tag: ```android:name="android.support.multidex.MultiDexApplication"```

**Comment by myflashlab** [comment]
are you seeing this problem on all your devices? or only one specific device?

**Comment by Pavlysha** [comment]
This problem is seen on all of devices that we use for test

**Comment by myflashlab** [comment]
Ok, please post your manifest .xml file here and also send us a demo .apk so we can install and check here in our test devices.

**Comment by Pavlysha** [comment]
Here is android part

`<android>
    <manifestAdditions><![CDATA[<manifest android:installLocation="auto">
	<supports-screens android:smallScreens="false" android:normalScreens="true" android:largeScreens="true" android:xlargeScreens="true" />
	<uses-permission android:name="android.permission.GET_ACCOUNTS" />
	
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
	<uses-sdk android:targetSdkVersion="26" android:minSdkVersion="19" android:multiDexEnabled="true" />
	<uses-permission android:name="com.android.vending.BILLING" />
	<uses-permission android:name="android.permission.VIBRATE" />
	<uses-permission android:name="com.android.alarm.permission.SET_ALARM" />
	<uses-permission android:name="android.permission.SET_ORIENTATION" />
	<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
	<uses-feature android:required="true" android:name="android.hardware.touchscreen.multitouch" />
	<permission android:name="ru.nikitaonline.criminalreporter.permission.C2D_MESSAGE" android:protectionLevel="signature" />
	<uses-permission android:name="ru.nikitaonline.criminalreporter.permission.C2D_MESSAGE" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
	<uses-permission android:name="android.permission.WAKE_LOCK" />
	<uses-permission android:name="android.permission.VIBRATE" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
	<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
	
	
	<uses-permission android:name="com.sec.android.provider.badge.permission.READ" />
	<uses-permission android:name="com.sec.android.provider.badge.permission.WRITE" />
	
	<uses-permission android:name="com.htc.launcher.permission.READ_SETTINGS" />
	<uses-permission android:name="com.htc.launcher.permission.UPDATE_SHORTCUT" />
	
	<uses-permission android:name="com.sonyericsson.home.permission.BROADCAST_BADGE" />
	<uses-permission android:name="com.sonymobile.home.permission.PROVIDER_INSERT_BADGE" />
	
	<uses-permission android:name="com.anddoes.launcher.permission.UPDATE_COUNT" />
	
	<uses-permission android:name="com.majeur.launcher.permission.UPDATE_BADGE" />
	
	<uses-permission android:name="com.huawei.android.launcher.permission.CHANGE_BADGE" />
	<uses-permission android:name="com.huawei.android.launcher.permission.READ_SETTINGS" />
	<uses-permission android:name="com.huawei.android.launcher.permission.WRITE_SETTINGS" />
	
	<application android:hardwareAccelerated="true" android:allowBackup="true" android:name="android.support.multidex.MultiDexApplication">
		<activity>
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.BROWSABLE" />
				<category android:name="android.intent.category.DEFAULT" />
				
				
				<data android:scheme="ru.nikitaonline.criminalreporter" />
			</intent-filter>
		</activity>
		
		<meta-data android:name="com.google.android.gms.games.APP_ID" android:value="\ 981022685252" />
		<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="\ 514303092265670" />
		
		
		
		<activity 
			android:name="com.facebook.FacebookActivity"
			android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation" 
			android:theme="@android:style/Theme.Translucent.NoTitleBar" 
			android:label="True Reporter" 
		/>
		
		<activity android:name="com.facebook.CustomTabMainActivity" />
		<activity android:name="com.facebook.CustomTabActivity" android:exported="true">
			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.DEFAULT" />
				<category android:name="android.intent.category.BROWSABLE" />
				<data android:scheme="fb514303092265670" />
			</intent-filter>
		</activity>
		
		
		
		<activity android:name="com.vk.sdk.VKServiceActivity" android:label="ServiceActivity" android:theme="@style/VK.Transparent"/>
		
		<intent-filter>
			<action android:name="android.intent.action.BOOT_COMPLETED" />
			<action android:name="android.intent.action.QUICKBOOT_POWERON" />
			<action android:name="android.intent.action.VIEW" />
			<category android:name="android.intent.category.DEFAULT" />
			<category android:name="android.intent.category.BROWSABLE" />
			<data android:scheme="fb514303092265670" />
		</intent-filter>
		
		
		<provider 
			android:authorities="com.facebook.app.FacebookContentProvider514303092265670" 
			android:name="com.facebook.FacebookContentProvider" 
			android:exported="true" />
		
		
		
		<activity android:name="com.doitflash.inAppBilling.utils.MyPurchase" android:theme="@style/Theme.Transparent" />
		
		
		
		<activity
		  android:name="com.tapjoy.TJAdUnitActivity"
		  android:configChanges="orientation|keyboardHidden|screenSize"
		  android:hardwareAccelerated="true"
		  android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
		<activity
		  android:name="com.tapjoy.mraid.view.ActionHandler"
		  android:configChanges="orientation|keyboardHidden|screenSize" />
		<activity
		  android:name="com.tapjoy.mraid.view.Browser"
		  android:configChanges="orientation|keyboardHidden|screenSize" />
		<activity
		  android:name="com.tapjoy.TJContentActivity"
		  android:configChanges="orientation|keyboardHidden|screenSize"
		  android:theme="@android:style/Theme.Translucent.NoTitleBar"
		  android:hardwareAccelerated="true" />
		
		
		
		
		<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
		<meta-data android:name="onesignal_app_id" android:value="9a620e3b-ba0f-439f-bfba-2e1960e204ae" />
		<meta-data android:name="onesignal_google_project_number" android:value="str:905108644139" />
		<receiver android:name="com.onesignal.GcmBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND">
			<intent-filter>
				<action android:name="com.google.android.c2dm.intent.RECEIVE" />
				<category android:name="ru.nikitaonline.criminalreporter" />
			</intent-filter>
		</receiver>
		<receiver android:name="com.onesignal.NotificationOpenedReceiver" />
		<service android:name="com.onesignal.GcmIntentService" />
		<service android:name="com.onesignal.SyncService" android:stopWithTask="false" />
		<activity android:name="com.onesignal.PermissionsActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar" />
		<service android:name="com.onesignal.NotificationRestoreService" />
		<receiver android:name="com.onesignal.BootUpReceiver"></receiver>
		<receiver android:name="com.onesignal.UpgradeReceiver">
			<intent-filter>
				<action android:name="android.intent.action.MY_PACKAGE_REPLACED" />
			</intent-filter>
		</receiver>
		
		<receiver android:name="com.myflashlabs.localNotifi.Alarm" />
		<receiver android:name="com.myflashlabs.localNotifi.RebootRescheduleNotifications">
			<intent-filter>
					<action android:name="android.intent.action.BOOT_COMPLETED" />
			</intent-filter>
		</receiver>
	</application>
</manifest>]]></manifestAdditions>
  </android>`

and here is ANE's which we use:

`<extensions>
	<extensionID>com.myflashlab.air.extensions.localNotification</extensionID>  
    <extensionID>com.myflashlab.air.extensions.billing</extensionID>
    <extensionID>com.myflashlab.air.extensions.facebook</extensionID>
    <extensionID>com.myflashlab.air.extensions.gameServices</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.games</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.drive</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.plus</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.auth.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.location</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.analytics</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.analytics.impl</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.gcm</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.iid</extensionID>
	<extensionID>com.marpies.ane.vk</extensionID>  
    
    <extensionID>com.tapjoy.extensions</extensionID>
  </extensions>`

**Comment by myflashlab** [comment]
also include the part for the AIR. why not just copy paste the whole thing anyway? :)

Would it be possible that there are ANE conflicts? try removing/disabling other ANEs from other providers and see if if you are still seeing the same results?

**Comment by Pavlysha** [comment]
> try removing/disabling other ANEs from other providers and see if if you are still seeing the same results?
Still the same results.
Also i try to use androidSupport from other providers, but it didn't help

**Comment by Pavlysha** [comment]
I edited comment with android manifest, now application.txt contains full application.xml

**Comment by myflashlab** [comment]
will you be able to send us a demo apk to run on our test devices?

**Comment by Pavlysha** [comment]
I can't because our application still under development. I can try to make empty application for test, but i think it not the same.

**Comment by myflashlab** [comment]
Of course, just create a simple demo project and implement the ANE in it. anything that can throw the error message for us to see it. We are trying to gather more information to find a reason why it's giving you these error but we don't see them!

**Comment by Pavlysha** [comment]
I've created demo apk, but it work correctly. I think problem is that i'm using Starling in main application and don't use it in demo app. Can it be possible what Facebook window displayed under main application?

**Comment by myflashlab** [comment]
No, the error messages you mentioned cannot be related to Starling. There must be another problem in your app configuration.

**Comment by myflashlab** [comment]
The facebook login window is a native window and native windows will ALWAYS open on top of AIR content. I'm pretty sure the error message is not related to Starling. I'll be surprised if it was!

**Comment by Pavlysha** [comment]
Are there any other reasons why the window is not displayed? This problem appear only on android device.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
