### ISSUE TITLE
Problems seeing Facebook events and Access Token

### ISSUE THREAD

**Issue by LeapingSwan** [myflashlab/facebook-ANE#148]
Adobe Air 30.0
Facebook ANE v 4.35.0
Platform iOS

Hi,  this is moved from another thread.

Having just signed up to the club I am moving an app from the demo versions and starting to use ANE LAB to build the xml file.  I'm getting the following errors:
```
1046: Type was not found or was not a compile-time constant: AccessToken.
1046: Type was not found or was not a compile-time constant: FacebookEvents.
1046: Type was not found or was not a compile-time constant: FacebookEvents.
```

All this code worked fine before the Facebook ANE update.  On the other thread it was said that such problems are usually because the ANE is not installed correctly - I get that, what I can't find out is what's wrong with the installation and I thought this was what the ANE LAB did for me.

Although I get that it may be the the ANE is not installed properly could throw an error but the Facebook ANE  is listed in the xml so I'd have thought that these items should be recognised even if my own settings are incorrect.

My code is:
```actionscript
import com.myflashlab.air.extensions.fb.*;
import flash.events.InvokeEvent;

Facebook.init(FACEBOOK_APP_ID);
Facebook.listener.addEventListener(FacebookEvents.INIT, onAneInit);
Facebook.listener.addEventListener(FacebookEvents.INVOKE, onAneInvoke);


var permissions:Array = [Permissions.public_profile, 
Facebook.auth.login(false, permissions, loginCallback);



public static function loginCallback(bIsCanceled:Boolean, eError:Error, accessToken:AccessToken, recentlyDeclined:Array, recentlyGranted:Array):void
{
// More code here
}

public static function onAneInvoke(e:FacebookEvents):void
{
trace("INVOKE");
trace("onAneInvoke: " + decodeURIComponent(e.deeplink));
}

public static function onAneInit(e:FacebookEvents):void
{
trace("onAneInit ");
trace("FBtoken " + FBtoken);
trace("Facebook " + Facebook);
trace("Facebook.auth " + Facebook.auth.toString());
trace("Facebook.auth.currentAccessToken " + Facebook.auth.currentAccessToken);

   // More code
}
```

The xml file is:
```xml
<?xml version="1.0" encoding="utf-8" ?> 
<application xmlns="http://ns.adobe.com/air/application/30.0">
  <id>con.drumond.digital</id>
  <filename>XXXXXX</filename>
  <name>XXXXXX</name>
  <versionNumber>1.0.30</versionNumber>
  <versionLabel>1.0.30</versionLabel>
  <initialWindow>
    <content>XXXXXX.swf</content>
    <autoOrients>true</autoOrients>
    <aspectRatio>portrait</aspectRatio>
    <renderMode>cpu</renderMode>
    <fullScreen>true</fullScreen>
    <systemChrome>standard</systemChrome>
  </initialWindow>
  <icon>
    <image29x29>icons/icon29.png</image29x29>
    <image57x57>icons/icon57.png</image57x57>
    <image114x114>icons/icon114.png</image114x114>
    <image512x512>icons/icon512.png</image512x512>
    <image48x48>icons/icon48.png</image48x48>
    <image72x72>icons/icon72.png</image72x72>
    <image50x50>icons/icon50.png</image50x50>
    <image58x58>icons/icon58.png</image58x58>
    <image100x100>icons/icon100.png</image100x100>
    <image144x144>icons/icon144.png</image144x144>
    <image1024x1024>icons/icon1024.png</image1024x1024>
    <image40x40>icons/icon40.png</image40x40>
    <image76x76>icons/icon76.png</image76x76>
    <image80x80>icons/icon80.png</image80x80>
    <image120x120>icons/icon120.png</image120x120>
    <image152x152>icons/icon152.png</image152x152>
  </icon>
  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>false</allowBrowserInvocation>
  <supportedLanguages>en</supportedLanguages>
  <iPhone>
    <requestedDisplayResolution>high</requestedDisplayResolution>
    <InfoAdditions><![CDATA[
  <key>com.myflashlabs.aneLab.id</key>
  <string>ZZZZZZZZZZZZZZZZZZZZZ</string>
  <key>NSAppTransportSecurity</key>
  <dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
  </dict>
  <key>MinimumOSVersion</key>
  <string>9.0</string>
  <key>UIApplicationExitsOnSuspend</key>
  <false/>
  <key>FacebookDisplayName</key>
  <string>Riddles Park</string>
  <key>LSApplicationQueriesSchemes</key>
  <array>
    <string>fbapi</string>
    <string>fb-messenger-api</string>
    <string>fb-messenger-share-api</string>
    <string>fb-messenger</string>
    <string>fbauth2</string>
    <string>fbshareextension</string>
  </array>
  <key>FacebookAppID</key>
  <string>00000000000000</string>
  <key>CFBundleURLTypes</key>
  <array>
    <dict>
      <key>CFBundleURLSchemes</key>
      <array>
        <string>fb00000000000000</string>
        <string>err</string>
      </array>
    </dict>
    <dict>
      <key>CFBundleURLSchemes</key>
      <array>
        <string>fb00000000000000</string>
        <string>YYYYYYYYYYYYYYYYY</string>
      </array>
    </dict>
    <dict>
      <key>CFBundleURLSchemes</key>
      <array>
        <string>fb00000000000000</string>
        <string>TTTTTTTTTTTTTTTT</string>
      </array>
    </dict>
  </array>
  <key>NSPhotoLibraryUsageDescription</key>
  <string>To use your profile picture for friend challenges</string>
  <key>UIDeviceFamily</key>
  <array>
    <string>1</string>
    <string>2</string>
  </array>
]]></InfoAdditions>
    <Entitlements><![CDATA[
  <key>get-task-allow</key>
  <true/>
  <key>aps-environment</key>
  <string>development</string>
]]></Entitlements>
  </iPhone>
  <extensions>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
    <extensionID>com.myflashlab.air.extensions.admob</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
    <extensionID>com.myflashlab.air.extensions.facebook</extensionID>
    <extensionID>com.myflashlab.air.extensions.billing</extensionID>
    <extensionID>com.myflashlab.air.extensions.rateMe</extensionID>
  </extensions>
</application>
```
Thanks

Stephen

**Comment by myflashlab** [comment]
> On the other thread it was said that such problems are usually because the ANE is not installed correctly - I get that, what I can't find out is what's wrong with the installation and I thought this was what the ANE LAB did for me.

ANELAB will copy the frameworks and dependency ANEs and resources and finally modifies the manifest .xml file. it does not edit your IDE settings. For example an .fla file, we cannot edit an fla file to embed an ANE in it! it's simply not possible :) So, it's users job to make sure ANEs are embedded in their projects. [these videos](https://www.youtube.com/watch?v=Oubsb_3F3ec&list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O) might be helpful for this reason.


Ok, I had a look at your manifest file and I can see miss-setup there. first, the use of ```com.myflashlab.air.extensions.dependency.androidSupport``` which is wrong. and secondly, I am seeing more than one reference to ```CFBundleURLSchemes``` which is again wrong.

You said you are "moving an app from the demo versions"... well, that is surely the source of the problem. Ok, do this:

* clean your project:
    1. remove the ```<extensions>``` tag and anything in it.
    2. remove the ```<iPhone>``` tag and anything in it.
    3. go to the folder you are keeping all the ANE files for your project and delete all the ANEs.

Now, open up ANELAB software and start adding the ANEs one by one. When you're done. go to your IDE and make sure the added ANEs are implemented there.

Let us know how you go.

**Comment by LeapingSwan** [comment]
Sorry for the delay in com ing back to you on your response - I have been away for a week.

I have tried to clean the project and that has solved the problem.  

That said I did have to download and copy overrideAir to the project folder and add it in manually.  It was showing on ANELAB as a dependency so I thought it would be added for me but it was not.  Is that normal?

Thanks

Stephen

**Comment by myflashlab** [comment]
That's weird. The OverrideAir ANE should be added automatically! is it downloaded/updated through ANELAB? *As a general rule, you should always keep the ANELAB updated so the update window should always be empty with no notification about new ANEs to be downloaded**

I'm glad it worked anyhow.

**Comment by LeapingSwan** [comment]
Yes I thought it should work directly but it didn't.  I did check that ANELAB is fully up to date etc.  Anyway this is working now for me so I'll close the ticket, just wanted to make you aware in case anyone else has the same problem.
