### ISSUE TITLE
Unstable tracking init events on ios.

### ISSUE THREAD

**Issue by xoopx** [myflashlab/facebook-ANE#149]
I have next problems with fb ane, maybe anyone can tell why it's happening this way:
a. fb standart events, like launches and installs tracking not every time and I can't see any logic when it's tracking and when it's not.
b. when adding our own custom events, standart events stop showing at all.

**Comment by myflashlab** [comment]
probably [this link](https://developers.facebook.com/docs/analytics/debugging/) could be helpful or even asking in stackoverflow for more input? You know, the ANE job is to make the native library work on AIR and here we'd be able to help with ANE related stuff. Thanks.

**Comment by xoopx** [comment]
Hi, guys,

I'm not sure but there maybe a problem in your facebook ane. We've acquired previous version and also tried demo of new version, and we are getting only few of launches and installs, very small percent of these events is seeing in dashboard. But we later tried other fb ane and there we are getting all 100% of these events. Can you check your ane? Or maybe we need to know some hints with using it? We tried it on a simple clean air project, just аn ane was implemented.

**Comment by xoopx** [comment]
Hi, if you found any solution, please let me know, it's very urgent!

**Comment by xoopx** [comment]
Hi, if you found any solution, please let me know, it's very urgent!

**Comment by myflashlab** [comment]
We will update you a.s.a.p with more news.

**Comment by myflashlab** [comment]
Well, we've been doing some tests and we don't see a problem. events are coming through normally :thinking: One thing to mention is that custom events would arrive with a few minutes delay. And the launchApp events won't arrive if you are closing the app and reopening it too soon. But if the app is closed for a 10 or so minutes and then you open it again, the event will arrive to the console.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
