### ISSUE TITLE
“The extension context does not have a method with the name”

### ISSUE THREAD

**Issue by gotohell32434** [myflashlab/facebook-ANE#15]
This is the fourth error we could not get past. 

Some nonsense about more than one ANE library. Can't be fixed.

**Comment by myflashlab** [comment]
We are in the process of merging the company with new devs and we're
upgrading the ANEs. Please use the older versions and in a couple of days
we'll make the public announcement about the new great changes.

On Saturday, November 21, 2015, gotohell32434 <notifications@github.com>
wrote:

> This is the fourth error we could not get past.
>
> Some nonsense about more than one ANE library. Can't be fixed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/facebook-ANE/issues/15>.
>


-- 
Sent from iPhone

**Comment by UmberFunk** [comment]
@gotohell32434 What version do you use? Is that purchased newest version?

I had some problems too. Fixed some. Want to replace by recent version, but if issues reported by you are in recent, I'll stay with older.

**Comment by myflashlab** [comment]
try running on a real device not the simulator.
