### ISSUE TITLE
Problem w/ Share Dialog

### ISSUE THREAD

**Issue by douglasmccarroll** [myflashlab/facebook-ANE#150]
Hi MyFlashLabs,

I can't get the "share dialog" to work. See my code below.

When I call "Facebook.share.shareDialog(content, onFacebookShareDialogCallback);" I get an alert saying that the ANE is a demo but nothing else happens. No dialog appears and the callback function isn't called.

Douglas

## Environment ##
* Android Version: N/A - I'm testing this on iOS
* iOS Version: 12.0
* AIR Version: 31

```actionscript
   public static function facebookShare(resultCallback:Function):void {
      _facebookShareResultCallback = resultCallback;
      initializeFacebookIfNeeded();
      var content:ShareLinkContent = new ShareLinkContent();
      content.quote = Constant_AppConfiguration.SHARING__FACEBOOK_SHARE_TEXT;
      content.contentUrl = Constant_AppConfiguration.SHARING__FACEBOOK_SHARE_URL;
      Facebook.share.shareDialog(content, onFacebookShareDialogCallback);
   }

   private static function initializeFacebookIfNeeded():void {
      if (!_isFacebookExtensionInitialized) {
         Facebook.init("my_facebook_app_id");  
         _isFacebookExtensionInitialized = true;
      }
   }


```

**Comment by myflashlab** [comment]
Could you please provide more information? because the demo dialog should have been shown after you call the ```Facebook.init("00000000");``` method.

**Comment by douglasmccarroll** [comment]
> Could you please provide more information?

Okay, here's the source code for a minimal demo app - with just the code that is needed to display a button and attempt to open the share dialog.

I'm testing this on my iPhone. With this app, when I call shareDialog() the app crashes.

I'm not including my Facebook ID in the code because I assume that this is public, but I am using the ID when I test my code.

Thanks,

Douglas

[MinimalDemoApp.zip](https://github.com/myflashlab/facebook-ANE/files/2457396/MinimalDemoApp.zip)

**Comment by myflashlab** [comment]
well, you are missing some settings in your manifest. Please make sure you have read the [wiki docs](https://github.com/myflashlab/facebook-ANE/wiki/01.-Setup) and also compare your manifest/project with [the demo project](https://github.com/myflashlab/facebook-ANE/blob/master/AIR/Main-app.xml#L103-L113) we have here on GitHub.

I also noticed that you are calling the share API just immediately after initializing the ANE. This is very wrong! you must listen to

```actionscript
Facebook.listener.addEventListener(FacebookEvents.INIT, onAneInit);
```
And whenthe ANE/SDK is initialized, you should do other things...

**Comment by douglasmccarroll** [comment]
Hi MyFlashLab,

Thanks for your feedback. 

> you are calling the share API just immediately 
> after initializing the ANE. This is very wrong! 

That makes sense. 

May I suggest that you expand the comment in your demo code? Perhaps instead of saying:
  // Add these listeners right after initializing the ANE
You could perhaps say:
  // Add these listeners right after initializing the ANE and wait for the INIT event before making other calls to the ANE
  
> you are missing some settings in your manifest

Yes, I omitted the LSApplicationQueriesSchemes key, and have added that now.

With these two changes my code is now working fine.   :)

Also, FYI, there are two parts of your demo iOS manifest code that a) don't seem to make sense, and b) don't seem to be needed to use this ANE.

1.


<string>air.com.site.app</string>

The URL that you provide in the comment talks about how to pass parameters into an app through a browser, which doesn't seem applicable to a mobile app ... ?
			
2.

<key>NSPhotoLibraryUsageDescription</key>
<string>My description about why I need this feature in my app</string>

Perhaps I'm missing something, but the ANE seems to be working fine without these. If they aren't needed, I suggest that you remove them from the example code.

Best Regards,

Douglas

**Comment by myflashlab** [comment]
About point 1: The reason is to familiar a user with what is the purpose of ```<data android:scheme="[PACKAGE_NAME]" />```

About point 2: ```NSPhotoLibraryUsageDescription``` would be needed [when sharing content](https://developers.facebook.com/docs/sharing/ios). All features in the given link may not be present in the ANE at the moment.

**Comment by douglasmccarroll** [comment]
Hi,

Thanks for your response.

I just noticed that GitHup is stripping off the XML tags from what I posted. 

So, just to make sure that things are clear, here are images of the "point 1" and "point 2" code that I was referring to, plus your comments in your last post, plus my responses to those comments.

![image](https://user-images.githubusercontent.com/2406534/48487982-b2ede280-e7ed-11e8-86eb-e19d34b31228.png)

> About point 1: The reason is to familiar a user with what is the 
> purpose of `<data android:scheme="[PACKAGE_NAME]" />`

In my previous message, because of GitHubs trimming, it looked as though I was just asking about the use of "air.com.site.app".  I'm guessing that you (understandably - sorry for the confusion) thought that I was asking about another place where "air.com.site.app" is used. If so, the above image is the actual code that I'm asking about.

![image](https://user-images.githubusercontent.com/2406534/48488490-e1b88880-e7ee-11e8-99be-b42b34cdc836.png)

> About point 2: NSPhotoLibraryUsageDescription would be needed when sharing 
> content. All features in the given link may not be present in the ANE at the moment.

This makes sense. Perhaps instead of saying:

"My description about why I need this feature in my app"

... you could say ...

"Your description about why you need this feature in your app - and, BTW, you'll need this feature if you are going to allow users to share content"

I hope that this feedback is helpful. I think this sort of explanation might help you to avoid having to answer some questions from people like me.  :)

Best Regards,

Douglas

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
