### ISSUE TITLE
Android errors on Facebook ANE

### ISSUE THREAD

**Issue by LeapingSwan** [myflashlab/facebook-ANE#151]
## Environment ##
* Android Version: 26
* AIR Version: 30

Hi,

Having successfully used ANELAB to integrate with my iOS project I am now trying to do the same with the Android one.  I have created the xml via ANELAB.  I have then added the following ANE's to my project:
```
admob-V3.1.0
billing-V2.5.2
facebook-V4.35.0
firebase.core-V7.0.0
rateMe-V1.2.1
overrideAir
```
But on publishing I get the following errors:

<img width="423" alt="screen shot 2018-10-10 at 12 40 53" src="https://user-images.githubusercontent.com/39804662/46733975-cb685b80-cc89-11e8-9469-3b10e5083b51.png">

My xml is set out below.

Thanks

Stephen
```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<application xmlns="http://ns.adobe.com/air/application/30.0">
    <id>com.YYYYYYYYYYYYY</id>
    <versionNumber>1.0.19</versionNumber>
    <filename>XXXXXXXXXX</filename>
    <description></description>
    <name>XXXXXXXXXX</name>
    <copyright></copyright>
    <initialWindow>
        <content>XXXXXXXXXX.swf</content>
        <systemChrome>standard</systemChrome>
        <transparent>false</transparent>
        <visible>true</visible>
        <fullScreen>true</fullScreen>
        <autoOrients>true</autoOrients>
        <aspectRatio>portrait</aspectRatio>
        <renderMode>cpu</renderMode>
    </initialWindow>
    <customUpdateUI>false</customUpdateUI>
    <allowBrowserInvocation>false</allowBrowserInvocation>
    <icon>
        <image36x36>icons/icon36.png</image36x36>
        <image48x48>icons/icon48.png</image48x48>
        <image72x72>icons/icon72.png</image72x72>
        <image96x96>icons/icon96.png</image96x96>
        <image144x144>icons/icon144.png</image144x144>
        <image192x192>icons/icon192.png</image192x192>
        <image512x512>icons/icon512.png</image512x512>
    </icon>
    <versionLabel></versionLabel>
    <supportedLanguages>en</supportedLanguages>
    <android>
        <manifestAdditions><![CDATA[<manifest android:installLocation="auto" >
  <application android:name="android.support.multidex.MultiDexApplication">
    <activity>
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
      <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <data android:scheme="com.dumonddigital.riddlespark"/>
      </intent-filter>
    </activity>
    <receiver android:name="com.google.android.gms.measurement.AppMeasurementReceiver" android:enabled="true" android:exported="false"/>
    <service android:name="com.google.android.gms.measurement.AppMeasurementService" android:enabled="true" android:exported="false"/>
    <service android:name="com.google.android.gms.measurement.AppMeasurementJobService" android:enabled="true" android:exported="false" android:permission="android.permission.BIND_JOB_SERVICE"/>
    <receiver android:name="com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver" android:enabled="true" android:exported="true" android:permission="android.permission.INSTALL_PACKAGES">
      <intent-filter>
        <action android:name="com.android.vending.INSTALL_REFERRER"/>
      </intent-filter>
    </receiver>
    <provider android:name="com.google.firebase.provider.FirebaseInitProvider" android:authorities="air.com.dumonddigital.riddlespark.firebaseinitprovider" android:exported="false" android:initOrder="100"/>
    <service android:name="com.google.firebase.components.ComponentDiscoveryService">
      <meta-data android:name="com.google.firebase.components:com.google.firebase.iid.Registrar" android:value="com.google.firebase.components.ComponentRegistrar"/>
      <meta-data android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar" android:value="com.google.firebase.components.ComponentRegistrar"/>
    </service>
    <receiver android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver" android:exported="true" android:permission="com.google.android.c2dm.permission.SEND">
      <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
        <action android:name="com.google.android.c2dm.intent.REGISTRATION"/>
        <category android:name="air.com.dumonddigital.riddlespark"/>
      </intent-filter>
    </receiver>
    <service android:name="com.google.firebase.iid.FirebaseInstanceIdService" android:exported="true">
      <intent-filter android:priority="-500">
        <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
      </intent-filter>
    </service>
    <activity android:name="com.google.android.gms.common.api.GoogleApiActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar" android:exported="false"/>
    <activity android:name="com.google.android.gms.ads.AdActivity" android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize" android:theme="@android:style/Theme.Translucent"/>
    <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version"/>
    <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="\ 000000000000000"/>
    <activity android:name="com.facebook.FacebookActivity" android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation" android:theme="@android:style/Theme.Translucent.NoTitleBar" android:label="RiddlesDev"/>
    <activity android:name="com.facebook.CustomTabMainActivity"/>
    <activity android:name="com.facebook.CustomTabActivity" android:exported="true">
      <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="fb0000000000000000"/>
      </intent-filter>
    </activity>
    <provider android:authorities="com.facebook.app.FacebookContentProvider000000000000000" android:name="com.facebook.FacebookContentProvider" android:exported="true"/>
    <receiver android:name="com.facebook.CurrentAccessTokenExpirationBroadcastReceiver" android:exported="false">
      <intent-filter>
        <action android:name="com.facebook.sdk.ACTION_CURRENT_ACCESS_TOKEN_CHANGED"/>
      </intent-filter>
    </receiver>
    <provider android:name="com.facebook.marketing.internal.MarketingInitProvider" android:authorities="air.com.YYYYYYYYYYYYYYYYYY.MarketingInitProvider" android:exported="false"/>
    <activity android:name="com.doitflash.inAppBilling.utils.MyPurchase" android:theme="@style/Theme.Transparent"/>
    <meta-data android:name="com.myflashlabs.aneLab.id" android:value="V=Zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"/>
  </application>
  <uses-sdk android:minSdkVersion="19" android:targetSdkVersion="26"/>
  <uses-permission android:name="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE"/>
  <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE"/>
  <uses-permission android:name="air.com.YYYYYYYYYYYYYYYYYY.permission.C2D_MESSAGE"/>
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
  <uses-permission android:name="android.permission.WAKE_LOCK"/>
  <uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="com.android.vending.BILLING"/>
</manifest>]]></manifestAdditions>
    </android>
    <extensions>
        <extensionID>com.myflashlab.air.extensions.admob</extensionID>
        <extensionID>com.myflashlab.air.extensions.billing</extensionID>
        <extensionID>com.myflashlab.air.extensions.facebook</extensionID>
        <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
        <extensionID>com.myflashlab.air.extensions.rateMe</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    </extensions>
</application>
```

**Comment by myflashlab** [comment]
You are seeing this error because Android dependencies are not implemented in your project. the only dependency ANE added to your project is the overrideAir ane. If you are using ANELAB, these dependency ANEs should have been copied to your project! If I remember correctly you had said that even on the iOS side, you had to manually copy the overrideAIR ane to your project. There must be something going wrong in your computer then! :)

So, As a workaround, you can follow the manual instruction of ANEs and add the dependency ANEs so you can go ahead with your project.

but I think we should also try to understand why the dependency files are not being copied to your project. let's first check if any error logs has been generated? please send us the possible logs being generated in ```logs.txt``` which is in the folder named ```ANELAB_LOGS``` in your computer's *Documents* directory.

**Comment by LeapingSwan** [comment]
Ok can we go back to basics here and make sure I am doing this right.

I am moving from a manual set up with the demo version to the paid ANELAB.  As you asked me to with the iOS version I started by taking out the extensions tab and Android tab in my xml.  I then used ANELABS to rebuild the xml, choosing to add in the following ANEs that I want:

Firebase
Admob
InAppPayments
RateMe
Facebook

The ANELAB is copying a bunch of dependencies into my folder.  I had thought I only needed to add the master ANEs to the fla (I know you can't write to the fla) but I thought the master ANEs pulled in the dependencies.  I have now added in those dependency ANE's manually to the fla and the xml has updated accordingly.  Is that the process you would expect me to go through or is there something else?  I did have much of this working when I set it up manually but had nowhere near as many dependencies included (I think you have deprecated androidSupport and broken it down into several dependencies, right?).

That gets me past my previous issue and allows me to publish but the app crashes on launch. its the same code as the iOS one that works so I think the problem is with the set up of the xml.


The extensions tab is now as follows:

    <extensions>
        <extensionID>com.myflashlab.air.extensions.admob</extensionID>
        <extensionID>com.myflashlab.air.extensions.billing</extensionID>
        <extensionID>com.myflashlab.air.extensions.facebook</extensionID>
        <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
        <extensionID>com.myflashlab.air.extensions.rateMe</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.appcompatV7</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.arch</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.cardviewV7</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.core</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.customtabs</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.v4</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.bolts</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.analytics</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.analytics.impl</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.measurement.connector</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads.lite</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.stats</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
    </extensions>
</application>

So are all the dependencies you would expect there?

Thanks

Stephen

**Comment by myflashlab** [comment]
Aha, so you removed the Dependency ANEs. Ok, you should just let ANELAB do what it does. It will setup the manifest and add the ANEs to your "lib" folder. Later, you must implement all of those ANEs into your FLA.

I had a quick look at your dependencies and noticed that you are missing this one: ```<extensionID>com.myflashlab.air.extensions.dependency.firebase.measurement.connector.impl</extensionID>```

I'd suggest you not to try adding these dependencies manually. Just use ANELAB. Open up your ```.mal``` file and when your project opens in ANELAB, simply click on "re-setup" for each of the ANEs. this will make sure all the dependencies are at place. The final step is always to make sure all the ANEs are implemented in your IDE.

>  I have now added in those dependency ANE's manually to the fla and the xml has updated accordingly

When you add dependencies in AdobeAnimate, it will automatically change the manifest... You should stop this. in your AdobeAnimate settings, there's a checkbox where you can click on and tell the IDE that you are managing the manifest .xml file manually, so AdobeAnimate is not changing that. (Instead, you are using ANELAB to manage the manifest for you).

> I think you have deprecated androidSupport and broken it down into several dependencies, right?

Correct.

> That gets me past my previous issue and allows me to publish but the app crashes on launch

I pretty much think the crash is happening because of the missing dependency (or may other ones?) Nonetheless, please provide us with crash logs when they happen so we can give more feedback about them.

**Comment by LeapingSwan** [comment]
Hi,

No I never removed the Dependency ANE's - they were in the folder, I just hadn't realised that I needed to add them in the project - for some reason I had the impression that these were called from the main ANEs.  So I have corrected that.  I have used ANELAB to manage the while process except the bit where you need to add all these ANE's to the fla which I have done manually which I believe is required.  I understand that it's this part of adding the ANEs to the fla that adds them to the xml, right?

The issue with the missing ANE firebase.measurement.connector.impl ANE and one other (googlePlayServices.measurementBase) is very weird.  I have added them to my fla and can see them there but they are not getting through to the xml.  I tried deleting them and then re-adding them but that made no difference.  In the end if I add them manually to the xml and then make the xml read only I can publish without a crash.  I'll have to get deeper into my code to make sure each of them is working fully of course, but at least they are launching.

However if I now go back into ANELAB and try and re-open the project I get the message that I now have two or more identical ANEs and it tells me to remove them.  For some reason then two of the ANEs are being seen by the system as the same when they are not.

So it's working for now and let's me get on, but it does mean that if I have to update ANEs in the future I'll have to unlock the file, make the updates, manually amend the xml and re-lock it.

It also suggests to me that, though I do need those ANE's included, ANELAB and Animate CC are seeing two or more as being the same.

This is clearly no longer a Facebook ANE problem as such but potentially an ANELAB one.  Do you want to move it to the ANELAB thread?

My current (locked) xml extensions are as follows:

    <extensions>
        <extensionID>com.myflashlab.air.extensions.admob</extensionID>
        <extensionID>com.myflashlab.air.extensions.billing</extensionID>
        <extensionID>com.myflashlab.air.extensions.facebook</extensionID>
        <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
        <extensionID>com.myflashlab.air.extensions.rateMe</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.appcompatV7</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.arch</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.cardviewV7</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.core</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.customtabs</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.v4</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.bolts</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.analytics</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.analytics.impl</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.measurement.connector</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.firebase.measurement.connector.impl</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads.lite</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.measurementBase</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.stats</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
    </extensions>

The error log for some of the latest crashes is below (actually shows some from Monday but it was crashing on Tuesday and Wednesday as well but I can't see any log details for those - I think it was publishing by this point but crashing on launch of the app), though I think this will just show us that the dependency was not there as you suspected.  The real issue now being the interaction of the ANELAB, xml and Flash Animate.


V1.1.24 - Mon Oct 8 14:30:08 2018 UTC
TypeError: Error #1010
	at Function/findShortcodeValueFromManifest()
	at win.project.aneAction::AneActionPage/jsonSetupCheckShortcodes()
	at win.project.aneAction::AneActionPage/makeSureShortcodesAreEven()
	at win.project.aneAction::AneActionPage/writeManifest()
	at Function/onComplete()
	at flash.events::EventDispatcher/dispatchEvent()
	at win.project.aneAction::AskForIosSetup/toSubmit()
	at flash.events::EventDispatcher/dispatchEvent()
	at com.myflashlabs.tapale.button::ButtonBlock/onClick() 
V1.1.24 - Mon Oct 8 14:30:19 2018 UTC
TypeError: Error #1010
	at Function/findShortcodeValueFromManifest()
	at win.project.aneAction::AneActionPage/jsonSetupCheckShortcodes()
	at win.project.aneAction::AneActionPage/makeSureShortcodesAreEven()
	at win.project.aneAction::AneActionPage/writeManifest()
	at Function/onComplete()
	at flash.events::EventDispatcher/dispatchEvent()
	at win.project.aneAction::AskForIosSetup/toSubmit()
	at flash.events::EventDispatcher/dispatchEvent()
	at com.myflashlabs.tapale.button::ButtonBlock/onClick() 
V1.1.24 - Mon Oct 8 14:32:12 2018 UTC
TypeError: Error #1010
	at Function/findShortcodeValueFromManifest()
	at win.project.aneAction::AneActionPage/jsonSetupCheckShortcodes()
	at Function/onAneFileLoaded()
	at flash.events::EventDispatcher/dispatchEvent()
	at com.myflashlabs.ane::AneParser/onComplete()
	at flash.events::EventDispatcher/dispatchEvent()
	at deng.fzip::FZip/progressHandler() 
V1.1.24 - Mon Oct 8 14:32:37 2018 UTC
TypeError: Error #1010
	at Function/findShortcodeValueFromManifest()
	at win.project.aneAction::AneActionPage/jsonSetupCheckShortcodes()
	at win.project.aneAction::AneActionPage/makeSureShortcodesAreEven()
	at win.project.aneAction::AneActionPage/writeManifest()
	at Function/onComplete()
	at flash.events::EventDispatcher/dispatchEvent()
	at win.project.aneAction::AskForIosSetup/toSubmit()
	at flash.events::EventDispatcher/dispatchEvent()
	at com.myflashlabs.tapale.button::ButtonBlock/onClick()


Thanks

Stephen

**Comment by myflashlab** [comment]
What I am sure of is that if ANELAB is saying that it has detected identical ANEs, then it really means it has. there's no possible way that error message could have been shown if this was not the case.

Besides, the error log says that it has not been able to correctly read the manifest, that's probably because the manifest was not set correctly before. Yet, I see that you are using an older version of ANELAB, always make sure to keep the software updated.

Another thing you can always try when working with ANELAB, is to clean your project and let the software rebuild it for you.

1. go to the folder where you keep all the ANEs for your project and delete all the ANEs in there.
2. open your manifest .xml file and delete the tags: ```<android```, ```<ios``` and ```<extensions```.
3. Open your project in ANELAB and setup ANEs again.

One thing that puzzles me is that you said the ANEs tags where not added by ANELAB and they were added only after implementing them through AdobeAnimate. Well! That shouldn't have been the case because ANELAB adds the necessary tags automatically.

Ok, I'm closing the issue here as you said, it's no longer related to Facebook ANE. Thanks.
