### ISSUE TITLE
facebook ane for ads

### ISSUE THREAD

**Issue by BAAKILI1987** [myflashlab/facebook-ANE#153]
i look for facebook ads  ane for audience network  facebook ?
iss there one to purchase here ?

(the admob ane is not available)
thanks

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
