### ISSUE TITLE
Bug in IOS

### ISSUE THREAD

**Issue by navdeepyadav** [myflashlab/facebook-ANE#19]
I tried the demo version of facebook-ANE and i was willing to purchase this. So first i made a demo for both IOS and android.
As you mentioned in your post that it takes time to compile on windows 32-bit pc and it works fine on 64-bit. I tried with android first it worked like a charm there, than i decided ti build IOS version. I am really sorry to say that but its not working for IOS. I followed all the instruction mentioned by you in your post but even after waiting for 3hrs to compile, its unable to produce the IPA file, Its not giving any error, its just continuously on publishing. Can you figure me out what is happening wrong here

**Comment by myflashlab** [comment]
The compile time problem is on 32-bit windows and ONLY on the Android side.
The iOS version will compile in just a few seconds so you must have faced
another problem. We suggest you to recheck your project settings and also
make sure to run the demo project first to make sure everything is set
correctly.

On Friday, January 8, 2016, navdeepyadav <notifications@github.com> wrote:

> I tried the demo version of facebook-ANE and i was willing to purchase
> this So first i made a demo for both IOS and android
> As you mentioned in your post that it takes time to compile on windows
> 32-bit pc and it works fine on 64-bit I tried with android first it worked
> like a charm there, than i decided ti build IOS version I am really sorry
> to say that but its not working for IOS I followed all the instruction
> mentioned by you in your post but even after waiting for 3hrs to compile,
> its unable to produce the IPA file, Its not giving any error, its just
> continuously on publishing Can you figure me out what is happening wrong
> here
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/facebook-ANE/issues/19>.
>


-- 
Sent from iPhone

**Comment by navdeepyadav** [comment]
Here are the steps that i followed
1. Added two anes to my .Fla file, 
    a.commonDependenciesV4.0.ane
    b.facebook.ane
2. Got the source code from sample
3. Added the FB frame wrok to AIR SDK
4. Create a Fb app and added both IOS and android platform on developer console
5. Prepared the manifest ( infact copied from there and replaced my FB APP Id there)
6. In Flash CS6 get the certificate and went for deployment- Adhoc option
7. Clicked on publish

But still publishing is going for infinite time

**Comment by navdeepyadav** [comment]
Also it create some temp directories at the root of fla file which has lots files inside with the swf. 

I am still unable to get the IPA from this, Can you please let me know what is wrong here

**Comment by navdeepyadav** [comment]
I have spent half of my day over this and now i think that this one is not going to work for me, or may be the information provided here is not enough to build an IPA with this native extension. 

Every one can see here that its buggy for iOS, I am not going to use it anymore

**Comment by myflashlab** [comment]
Sorry to see you have faced such problems. Another thing to check is if you
are using Air SDK 20 in your project? Read here the possible problem that
Adobe is working on: https://forums.adobe.com/thread/2041879

On Friday, January 8, 2016, navdeepyadav <notifications@github.com> wrote:

> I have spent half of my day over this and now i think that this one is not
> going to work for me, or may be the information provided here is not enough
> to build an IPA with this native extension.
>
> Every one can see here that its buggy for iOS, I am not going to use it
> anymore
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/facebook-ANE/issues/19#issuecomment-169945245>
> .
>


-- 
Sent from iPhone
