### ISSUE TITLE
dublicate symbol_getEnumTitle in

### ISSUE THREAD

**Issue by 22Round** [myflashlab/facebook-ANE#2]
I have build issue, when I try to add commonDependenciesV3.0.ane or commonDependenciesV2.0.ane
compiler shows error

![publish_issue](https://cloud.githubusercontent.com/assets/5682469/9258393/547679cc-420c-11e5-908c-cb33c05520b1.jpg)

**Comment by myflashlab** [comment]
You need to "hide ane library symbols" when compiling on iOS. Read here:
http://help.adobe.com/en_US/flashbuilder/using/WSe4e4b720da9dedb5-2e7310a1136ab7c1811-8000.html#WSe4e4b720da9dedb52cb000931394dc3d45a-8000

On Thursday, August 13, 2015, Vakhtangi Beridze <notifications@github.com>
wrote:

> I have build issue, when I try to add commonDependenciesV3.0.ane or
> commonDependenciesV2.0.ane
> compiler shows error
>
> [image: publish_issue]
> <https://cloud.githubusercontent.com/assets/5682469/9258393/547679cc-420c-11e5-908c-cb33c05520b1.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/facebook-ANE/issues/2>.
>


-- 
Sent from iPhone
