### ISSUE TITLE
Terrible Customer Support!

### ISSUE THREAD

**Issue by hybridmindset** [myflashlab/facebook-ANE#20]
You completely missed the first part of my last post. I said the project you sent does not work when exporting a production build from flash builder. It only worked with a debug build. It is intermittent. That is not a flawlessly working ANE. Your documentation is lacking in many details. I don't need anyone to teach me how to use Adobe AIR. Just because you can run a generic project doesn't make it flawless. It should be able to work in a production environment in many scenarios. 

Furthermore you don't close an ongoing issue of a paying customer because you can't figure out the issue. Thats pretty rude!

**Comment by myflashlab** [comment]
Dear @hybridmindset I asked you to open a new ticket talking about specific problems you are facing when using the ANE so we can keep the issues pages clean and informative for other devs. It's not a good idea to spam this forum with non-tech related questions!
