### ISSUE TITLE
LogManager.WITH_PUBLISH_PERMISSIONS Crashing App

### ISSUE THREAD

**Issue by hybridmindset** [myflashlab/facebook-ANE#22]
How do I use the LogManager.WITH_PUBLISH_PERMISSIONS? 

Whenever I use it to request a "publish_actions" permission my app crashes. 

Should both LogManager.WITH_READ_PERMISSIONS and LogManager.WITH_PUBLISH_PERMISSIONS be passed to FB.logManager.requestPermission when their is a list of permissions with read and publish permission included?

**Comment by myflashlab** [comment]
Could you please tell us if you are facing this problem on Android or iOS or both?

**Comment by myflashlab** [comment]
As stated by Facebook, your app should use read permissions first for loging in the user.

```actionscript
FB.logManager.requestPermission(LogManager.WITH_READ_PERMISSIONS, Permissions.public_profile, Permissions.user_friends, Permissions.email);
```
 and then only when it's required, you should call

```actionscript
FB.logManager.requestPermission(LogManager.WITH_PUBLISH_PERMISSIONS, Permissions.publish_actions);
```

and for both methods, you will need to listen to the following listeners to know the result of your login process (permission request results)

```
FBEvent.LOGIN_DONE
FBEvent.LOGIN_CANCELED
FBEvent.LOGIN_ERROR
```

**Comment by hybridmindset** [comment]
@myflashlab Maybe I should clarify. I am logging in with only a few read permissions at first. Just like the Facebook documentation says. That is successful. Then after logging in I make an API call. When that api call comes back with an error I check if it is an error regarding a missing permission and then then resend the request for the missing permission which is "publish_actions" using:
FB.logManager.requestPermission(LogManager.WITH_PUBLISH_PERMISSIONS, "publish_actions");   (I do also include all the previous read permission from initial login because your documentation states that all permissions should be sent to requestPermission even when you are requesting additional permissions).  Whenever I do this the app crashes. If I request other permissions like "user_likes" the app works fine. "publish_actions" is considered an extended permission. I am trying to handle a missing permission use case.

This is happening on Android. I haven't tested iOS yet.

**Comment by myflashlab** [comment]
Thanks for the clarification. I should add that ```LogManager.WITH_READ_PERMISSIONS``` and ```LogManager.WITH_PUBLISH_PERMISSIONS``` are considered two sets of different permission types and in your app, you should consider them seperated from each other.

so, when using ```LogManager.WITH_READ_PERMISSIONS``` for the firs time, you can set the least number of permissions your app may require at first and then if you need to add more read permissions, you should call it again by adding the previous permissions + the new ones you wish to add.

BUT, if you are planing to add publish permissions with ```LogManager.WITH_PUBLISH_PERMISSIONS``` you must NOT include the read permission types. instead the command alone as follow.

```actionscript
FB.logManager.requestPermission(LogManager.WITH_PUBLISH_PERMISSIONS, Permissions.publish_actions);
```
Quick help notice: install Android studio and then look at the ADB log console there while running your app. if there are internal java errors, they will be logged there.

**Comment by hybridmindset** [comment]
@myflashlab thanks.
