### ISSUE TITLE
Facebook ID is wrong

### ISSUE THREAD

**Issue by navdeepyadav** [myflashlab/facebook-ANE#25]
I am calling the graph request from this extension and asking for facebook id, but it gives wrong facebook id, Other information is correct but facebook id is wrong.

Also few days ago i posted a issue that its not building for IOS and i got reply from you to build it from another AIR SDK instead of 20, I tried it with AIR SDK 19, but still the same thing

**Comment by myflashlab** [comment]
>I am calling the graph request from this extension and asking for facebook id, but it gives wrong facebook id

the extension is returning the json result from facebook servers without touching anything in it!

> its not building for IOS

we can't do blind guess problems! you should either send us an error message you are receiving or send us a demo project so we can see the problem.

yet, when running the Facebook ANE, you need to add the commondependencies ane to your project too and when you do that, you need to set the ```-hideAneLibSymbols``` to ```yes``` as explained in details here: http://help.adobe.com/en_US/flashbuilder/using/WSe4e4b720da9dedb5-2e7310a1136ab7c1811-8000.html#WSe4e4b720da9dedb52cb000931394dc3d45a-8000

**Comment by navdeepyadav** [comment]
![Uploading Screenshot_2016-01-19-18-04-281.png…]()
![Uploading Screenshot 2016-01-19 18.05.08.png…]()


I have uploaded the screenshots here for the real facebook id and what i am getting on phone

**Comment by navdeepyadav** [comment]
![screenshot_2016-01-19-18-04-281](https://cloud.githubusercontent.com/assets/16606299/12419204/8913cf72-beda-11e5-87d3-df30e1e5b5ec.png)
![screenshot 2016-01-19 18 05 08](https://cloud.githubusercontent.com/assets/16606299/12419236/bf7c4152-beda-11e5-96fc-17aea2caaf50.png)


I have uploaded the screenshots here for the real facebook id and what i am getting on phone
my real facebook id is "10204947938957364" and i am getting "10206654118170778"
I have tried with other facebook developers from my app, but still the same result

**Comment by myflashlab** [comment]
the default graph version the ANE works with is v2.3 are you setting the graph version correctly when calling the graph api? ```FB.graph.version = "v2.5";```

let me know if that helps?

**Comment by navdeepyadav** [comment]
What ever version i use, it won't change my facebook id in any version, I have tried to change the version but its still same result.

**Comment by myflashlab** [comment]
it seems like it's an internal facebook logic or something! why am I saying that? because both IDs are linked to the same facebook page. check it out for yourself:

https://www.facebook.com/10204947938957364
https://www.facebook.com/10206654118170778

they are both redirected to https://www.facebook.com/navdeep.yadav.142

anyway, in the ANE, we are just returning the Json reply from the graph directly to you, if they are changed, then it's something that Facebook is doing which as it seems, they are totally fine. they both go to the same location.

**Comment by navdeepyadav** [comment]
This is really a big issue with the facebook server itself, Otherwise its not possible to have two different facebook ids for same account. I need to handle this at my side

**Comment by myflashlab** [comment]
no, it's not a bug on Facebook's side! as the documentation says:

> Facebook will begin to issue app-scoped user IDs when people first log into an instance of your app coded against v2.0 of the API. With app-scoped IDs, the ID for the same user will be different between apps.

https://developers.facebook.com/docs/apps/upgrading
