### ISSUE TITLE
AIR SDK 18+ is not able to build the IOS

### ISSUE THREAD

**Issue by navdeepyadav** [myflashlab/facebook-ANE#27]
I have tried with AIR SDK 19 and 20, but still unable to produce the IOS build with the facebook- ANE, I would like to know if anyone has made IOS build with this. If any one has done this, please write here or post here the sample that work. I am following all the steps as mentioned in tutorial, added, all the required files, facebook frameworks to AIR SDK, modified the manifest.xml as mentioned, but still nothing works. I am waiting for more than hour but it always show the publishing as in my screenshot.
Somebody help me to get out of this problem

![screenshot 2016-01-21 12 39 41](https://cloud.githubusercontent.com/assets/16606299/12482750/5bd30ec6-c077-11e5-80d1-3d269277ed2c.png)

**Comment by myflashlab** [comment]
checkout this issue which might be a help to you: https://github.com/myflashlab/facebook-ANE/issues/24#issuecomment-172941126

also make sure to update yourself to the latest version of the ANE http://www.myflashlabs.com/urgent-fix-on-our-anes-required-for-air-sdk-v20-or-higher/

**Comment by myflashlab** [comment]
Just wondering if the problem is solved?
