### ISSUE TITLE
UIFileSharingEnabled incorrect value type for iOS

### ISSUE THREAD

**Issue by flashmandv** [myflashlab/facebook-ANE#28]
When I was uploading my packaged app to the Apple App Store - I got this error from the Application Loader:
"The value for the info.plist key UIFileSharingEnabled is not of the required type.."

I changed the value from <string>NO</string>  to <false /> and it worked.
I hope it does not break anything. 
Maybe you should update your documentation about this.

Thanks

**Comment by myflashlab** [comment]
Oh, thanks for pointing that out. That's actually related to our iOS
debugging processes. It's totally safe to be removed. We'll fix the demo
files as soon as possible though. Sorry for the misunderstanding and thanks
for reporting it.

On Monday, January 25, 2016, flashmandv <notifications@github.com> wrote:

> When I packaged my app and was uploading to Apple App Store - I got error
> "The value for the infoplist key UIFileSharingEnabled is not of the
> required type"
>
> I changed the value from NO to and it worked
> I hope it does not break anything
> Maybe you should update your documentation about this
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/facebook-ANE/issues/28>.
>


-- 
Sent from iPhone

**Comment by myflashlab** [comment]
documentation is now updated. Thanks for pointing out that.
