### ISSUE TITLE
FB.share(..) method shows activity which reappears

### ISSUE THREAD

**Issue by flashmandv** [myflashlab/facebook-ANE#29]
Hello,

I have another problem with the Facebook extension. When the share dialog appears - when I tap cancel and discard the sharing - the activity reappears again. Same thing happens even if I post the image - it posts it to my wall and the activity is reshown again.

Please help me as I have to make release of my game already.
Thanks

**Comment by myflashlab** [comment]
is this happening on Android or iOS? could you give us a sample .as file which we can run and duplicate the problem?

**Comment by flashmandv** [comment]
It happens in Android. I haven't tested on iOS yet. I just copied the share example from the docs and tested. It loops the activity. I will try on sample app and write back

**Comment by flashmandv** [comment]
Sorry I don't have time to setup new sample project. The reproduction is very simple.
When you are logged in, just execute this code:

```
var shareModel:ShareLink = new ShareLink();
shareModel.contentTitle = "Mystic Miracles";
shareModel.contentURL = "https://play.google.com/store/apps/details?id=air.net.boardgamesonline.FarmBuilder";
shareModel.imageURL = "http://boardgamesonline.net/assets/wonders/fb.jpg";
shareModel.contentDescription = "Come to play";
FB.share(shareModel, onSharingResult);
```
Then in the descriptor file add this


```
<activity android:name="com.facebook.FacebookActivity"          android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen"   android:theme="@style/Theme.Transparent" />
<activity android:name="com.doitflash.facebook.access.MyLogin"  android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen"   android:theme="@style/Theme.Transparent" />
		
		            
<provider android:authorities="com.facebook.app.FacebookContentProvider430348420477249" android:name="com.facebook.FacebookContentProvider" android:exported="true"/>
<activity android:name="com.doitflash.facebook.sharing.MyShare" android:theme="@style/Theme.Transparent" />


<activity android:name="com.doitflash.facebook.invite.MyInvite" android:theme="@style/Theme.Transparent" />

```

The used compiler is Flex 4.14.1 FP19 AIR 19

**Comment by myflashlab** [comment]
@flashmandv we're not able to see the problem and it's working just fine! we just made sure once again right now. try this demo https://github.com/myflashlab/facebook-ANE/tree/master/FD/dist and the sharing sample button there is just like your code here. do you have the same problem when running the sample apk there?

**Comment by myflashlab** [comment]
We would appreciate an update on this question.
