### ISSUE TITLE
Send gameRequest

### ISSUE THREAD

**Issue by UmberFunk** [myflashlab/facebook-ANE#3]
Hello,

We have bought this extension and integrated it into our game. The problem is that I can't find a way to call a gameRequest. Hope this feature is included, because this is must for us.

Can you help?

Regards,
Irakli

**Comment by UmberFunk** [comment]
I hadn't found this feature in your ANE, but I have built it myself using StageWebView. 

It was a surprise for me that stage web view opened request without requiring credentials. ou can use it and add it to your ANE. 

I have set listeners to listen to location change. If location isn't same as the requested url, webView shuts down, but before this it sends request to Facebook. Works on Android. Didn't tested it on iOS. 

NOTE: Pay attention to address. If Facebook redirects, webView will be closed. You can enter other possible too and compare. I don't know other possible variant. If you find it, make a note here.

Regards,
Irakli



```
var url:String = "https://m.facebook.com/v2.3/dialog/app_requests?"
+ "redirect_uri=" + REDIRECT_URL
+ "&access_token=" + YOUR_ACCEESS_TOKEN
+ "&message=" + MESSAGE
+ "&client_id=" FB_APP_ID

callWebView(url);
```

```
public function callWebView(url:String):void
{
	
	
	function webViewLocationChange(e:LocationChangeEvent):void
	{
		if (e.location != url) {
			closeWebView(null);
		}
	}
	
	function closeWebView(e:MouseEvent):void
	{
		webView.removeEventListener(LocationChangeEvent.LOCATION_CHANGE, webViewLocationChange);
		
		webView.stage = null;
		webView.viewPort = null;
		webView.dispose();
		webView = null;
		
	}
	
	
	webView = new StageWebView();
	webView.viewPort = new Rectangle( 0, 0, stage.stageWidth, stage.stageHeight/16*15); 
	webView.stage = stage;
	
	webView.addEventListener(LocationChangeEvent.LOCATION_CHANGE, webViewLocationChange);
	
	webView.loadURL( url );
	
}
```

**Comment by myflashlab** [comment]
sending game requiests/invites is in our to-do list for FB ANE next version.

**Comment by nanhuichen** [comment]
@UmberFunk 

Thanks for your solution.

**Comment by UmberFunk** [comment]
@nanhuichen

You're welcome. 

Hope it will help. I made some modifications to it since then. I'll try to paste the updates here, but I'm not sure I'll be able to do it soon, but I'll try.
