### ISSUE TITLE
Any Facebook story posting graph api example using POST method?

### ISSUE THREAD

**Issue by alokt** [myflashlab/facebook-ANE#31]
I'm trying to post face book custom object using graph api.  my final URL works fine if i test on debugger tool or browser but when i'm trying to use same api call from mobile i'm getting below error:

// sample graph api call
https://graph.facebook.com/me/$mycustom_action?action=$mystorypath&access_token=$myaccess_token
or 
https://graph.facebook.com/me/$mycustom_action?action=$mystorypath&access_token=$myaccess_token&method=POST

FB.graph.request( url, "POST");

{
    "error": {
      "message": "(#803) Some of the aliases you requested do not exist: v2.3https:",
      "type": "OAuthException",
      "code": 803,
	  "fbtrace_id": "HGRQGQmSVy/"
 	}
}

Tried to find any POST graph example but did not find. GET method works fine.

Thanks,
Alok

**Comment by myflashlab** [comment]
Tell me if I got you correctly, you're saying that if you are using POST instead of GET when requesting for a graph, the result will fail but the same request being sent by GET will return correctly?

If not, could you please add your code you are testing to https://github.com/myflashlab/facebook-ANE/blob/master/FD/src/SampleGraph.as so we can run and test it locally here?

**Comment by myflashlab** [comment]
as an additional information, please note that every request you make through ```FB.graph.request``` will be sent to the following address:

```actionscript
"https://graph.facebook.com/" + _version + node
```
if your error message says ```Some of the aliases you requested do not exist: v2.3https```

it means that your node is starting with https at the beginning which is not correct. you should not pass a complete URL to the request.

This is a quick guess anyway, but please send us your code and we'll be better be able to help you spot the problem.

**Comment by alokt** [comment]
Hey, Thanks for reply, yes i was adding "https://graph.facebook.com/", removed it, works perfectly now.

Thanks Again!
