### ISSUE TITLE
Switch between Air app and Facebook

### ISSUE THREAD

**Issue by alokt** [myflashlab/facebook-ANE#33]
I've implemented facebook-ANE with AIR 18 and it was working perfectly, then i've updated Adboe AIR to 20 and after update we've observed that when user does any facebook related operations, screen becomes white/black (iOS/Androdi) for a long period of time compared to integration with air 18.

Say, connect to facebook now shows 10-15 secs of white screen on iOS before it shows facebook details. This is very bad user experience.

Any suggestion or any known issues like this?

Thank You,

**Comment by myflashlab** [comment]
are you experiencing this on all your devices? we have tested with ```flex_sdk_4.6_air_sdk_20-204``` and it's fine. please tell me which exact version of SDK 20 you have tested on?

**Comment by alokt** [comment]
Well, not on all devices, so fart it is worst on iPhone 6. I'm using flex sdk 4.6 and air 20 downloaded from here.
http://www.adobe.com/devnet/air/air-sdk-download.html

**Comment by myflashlab** [comment]
Will check this out and update you a.s.a.p

**Comment by myflashlab** [comment]
We tested with Air SDK 20.0.260 and it's working normally! please checkout this article though: http://www.myflashlabs.com/adobe-air-facebook-sdk-opens-in-safari-problem-in-ios-9/

**Comment by alokt** [comment]
Thanks that helps. I'll do changes and see how it works.

**Comment by myflashlab** [comment]
How did it go?

**Comment by alokt** [comment]
Worked, post that you shared helped and issue is resolved.

Thanks,
