### ISSUE TITLE
Game Requests

### ISSUE THREAD

**Issue by Jorjon** [myflashlab/facebook-ANE#34]
Hi, I want to be able to send a Game Request using [Invitable API](https://developers.facebook.com/docs/games/services/gamerequests), to previously selected friends. I have done this functionality on Javascript and I can get the friend list with request() function, but I can't see an implementation of the Game Request functionality.

Is it possible to do that with the current version?

Thanks

**Comment by myflashlab** [comment]
Game requests has not been implemented in the ANE as we received not much interest in that part of the API. but adding support for Game requests is already in our to-do list. we are currently working on another huge ANE and as soon as it's finished, we will continue with the to-do list and adding game requests to the FB ANE is on it Thanks for the comments though.

**Comment by UmberFunk** [comment]
Hi @Jorjon,

We had same problem with gameRequests. I think it's very important feature.

I have found a way to implement it using StageWebView. You can see it here:
https://github.com/myflashlab/facebook-ANE/issues/3

I made a little more enhancements to the script after posting. Let me know if you'll need it.

Regards,
Irakli

**Comment by Guarionex** [comment]
Any news on when this feature will be released for the ANE?

**Comment by myflashlab** [comment]
Well, we'd love to add it but it has not received much interest based on votes here http://www.myflashlabs.com/flash-devs-voice/

**Comment by nanhuichen** [comment]
Hi,

Does any updates?

**Comment by myflashlab** [comment]
> We have updated the ANE to the latest SDK and a LOT has changed. for example like buttons and app invites have been deprecated but we have now added the GameRequest feature. Moreover, we have re-wrote the whole Actionscript part to be easier to work with. Please update yourself to the latest version and see how it goes. If you are still encountering any problem, please feel free to open a new issue and ask your questions. And by the way, when updating your app with the new ANE, make sure to read and follow the [new wiki documentations](https://github.com/myflashlab/facebook-ANE/wiki). Moreover, the asdoc has also moved to this package: http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/fb/package-detail.html

Also make sure to read the changelog to know what changes you need to make to your manifest. xml file.
