### ISSUE TITLE
Compilation failed while executing : ld64

### ISSUE THREAD

**Issue by UmberFunk** [myflashlab/facebook-ANE#35]
Hi,
I am sure you aren't glad to see my avatar again. :) I have luck to meet issues and bugs everywhere. Here's new one: **Compilation failed while executing : ld64**
This error shows up when building .IPA using AIR SDK 19 or 21 on windows. Didn't tested SDK 20.

As you know, currently AIR has a bug. You can't publish IPA built on windows using 20 and 21 SDK. SDK 19 is the latest version developers can use for IPAs on windows.

```
<extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID> - **Error on AIR SDK 19 and 21**
<extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID> - **Error on AIR SDK 19 and 21**
<extensionID>com.myflashlab.air.extensions.facebook</extensionID> - **Error on AIR SDK 19**
<extensionID>com.myflashlab.air.extensions.billing</extensionID> - **Error on AIR SDK 19**
```

Environment:
Windows 10;
Latest FlashDevelop;
MyFlashLabs ANEs from packageV11;

Regards,
Irakli

**Comment by 22Round** [comment]
@UmberFunk publish issue for IOS has been fixed in AIR 22 Beta

**Comment by UmberFunk** [comment]
Tested using 22 Beta. Same Error.

**Comment by UmberFunk** [comment]
Also, I simplified our SWF. Removed everything. Same error. The problem isn't related to our SWF.

**Comment by myflashlab** [comment]
> I am sure you aren't glad to see my avatar again. :)

NO! not at all :)

ABout your question, one of the recent reasons for the ```Compilation failed while executing : ld64``` error could be this: https://forums.adobe.com/message/8303441#8303441 We reported that problem a while ago and considering that you are using FlashDevelop, I guess this link will solve the problem for you.

**Comment by UmberFunk** [comment]
I'm really glad to see your high responsibility and desire to make your products better. This makes us confident in our choice to go with your products.

I'll try it and let you know about the results. Thanks!

**Comment by UmberFunk** [comment]
**-hideAneLibSymbols no** solved the issue for us.

Thanks a lot!
