### ISSUE TITLE
IOS Safari Issue

### ISSUE THREAD

**Issue by navdeepyadav** [myflashlab/facebook-ANE#36]
Hello, 

I have made the manifest same mentioned and whitelist Facebook app i tried in 3 version AIR sdk 19, AIR sdk 20 and the AIR SDK 21, but its opening the safari in all the 3 builds.

Can you please help

**Comment by myflashlab** [comment]
we'll have a look into this and update you as soon as possible. thanks.

**Comment by navdeepyadav** [comment]
Dear support 

Any update for this issue, Its more than two days but i got nothing from support

**Comment by myflashlab** [comment]
Please read the [changlong](https://github.com/myflashlab/facebook-ANE#changelog) and update to V4.11.0. then tell us if you have any questions. Thanks.
