### ISSUE TITLE
It takes too long to authenticate on iOS 9.3.1 on iPhone 4S + more issues

### ISSUE THREAD

**Issue by UmberFunk** [myflashlab/facebook-ANE#37]
It takes too long to authenticate on iOS 9.3.1 on iPhone 4S. ~20 seconds.

Also, Facebook app behaves strange when authenticating. Several pages are shown: wall, white screen, blue screen, then again white screen.Then it goes back to the game after ~20 secs. Bad experience for users.

Frequently while Facebook is authenticating, the game is removed from the background and when authentication is finished and application should show up at the same point where left, the app starts from the beginning.

Earlier, the connect on iOS was working very smooth. Maybe with iOS or Facebook updates something was changed and caused this issues. Hope you can fix it.

P.S. We haven't tested on other iOS devices. Only 4S.

Our code for connect:
```
public static function connect(callback:Function):void
{
	function onLoginSuccess(event:FBEvent): void {
		FB.logManager.removeEventListener(FBEvent.LOGIN_DONE, onLoginSuccess);
		FB.logManager.removeEventListener(FBEvent.LOGIN_CANCELED, onLoginCanceled);
		FB.logManager.removeEventListener(FBEvent.LOGIN_ERROR, onLoginError);
		B.Log("FB onLoginSuccess");
		callback(true);
	}
	function onLoginCanceled(event:FBEvent): void {
		FB.logManager.removeEventListener(FBEvent.LOGIN_DONE, onLoginSuccess);
		FB.logManager.removeEventListener(FBEvent.LOGIN_CANCELED, onLoginCanceled);
		FB.logManager.removeEventListener(FBEvent.LOGIN_ERROR, onLoginError);
		B.Log("FB onLoginCanceled");
		callback(false);
	}
	function onLoginError(event:FBEvent): void {
		FB.logManager.removeEventListener(FBEvent.LOGIN_DONE, onLoginSuccess);
		FB.logManager.removeEventListener(FBEvent.LOGIN_CANCELED, onLoginCanceled);
		FB.logManager.removeEventListener(FBEvent.LOGIN_ERROR, onLoginError);
		B.Log("FB onLoginError = " + event.param);
		callback(false);
	}
	
	FB.logManager.addEventListener(FBEvent.LOGIN_DONE, onLoginSuccess);
	FB.logManager.addEventListener(FBEvent.LOGIN_CANCELED, onLoginCanceled);
	FB.logManager.addEventListener(FBEvent.LOGIN_ERROR, onLoginError);
	
	FB.logManager.requestPermission(LogManager.WITH_READ_PERMISSIONS, Permissions.public_profile, Permissions.user_friends);
}
```

**Comment by UmberFunk** [comment]
We are using AIR 19 to build IPAs.

```
<![CDATA[
	
	<key>MinimumOSVersion</key>
	<string>7.1</string>
	
	<key>UIStatusBarStyle</key>
	<string>UIStatusBarStyleBlackOpaque</string>
	
	<key>UIRequiresPersistentWiFi</key>
	<string>NO</string>
	
	<!-- THERE WAS AN ERROR WITH IT WHEN UPLOADING TO APPSTORE -->
	<!-- So, we commented it -->
	<!--<key>UIFileSharingEnabled</key>
	<string>NO</string> -->
	
	<key>UIPrerenderedIcon</key>
	<true />
	
	<key>FacebookAppID</key>
	<string>458412101000468</string>
	
	<key>FacebookDisplayName</key>
	<string>Air Native Extension</string>
	
	<key>CFBundleURLTypes</key>
	<array> 
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>fb458412101000468</string>
				<string>air.com.doitflash.exfacebook2</string>
			</array>
		</dict>
	</array>
	
	<!-- To whitelist Facebook Apps -->
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>fbapi</string>
		<string>fbapi20130214</string>
		<string>fbapi20130410</string>
		<string>fbapi20130702</string>
		<string>fbapi20131010</string>
		<string>fbapi20131219</string>    
		<string>fbapi20140410</string>
		<string>fbapi20140116</string>
		<string>fbapi20150313</string>
		<string>fbapi20150629</string>
		<string>fbauth</string>
		<string>fbauth2</string>
		<string>fb-messenger-api20140430</string>
	</array>
	
	<key>UIDeviceFamily</key>
	<array>
		<string>1</string>
		<string>2</string>
	</array>
]]>

```

**Comment by myflashlab** [comment]
please make sure you have added the new requirements to your manifest explained here: https://github.com/myflashlab/facebook-ANE/issues/33#issuecomment-188128591

**Comment by UmberFunk** [comment]
We have it added already.
I have copied InfoAdditions part of our manifest. Please, take a look on it.

**Comment by UmberFunk** [comment]
Any updates?

**Comment by UmberFunk** [comment]
Any plans for fixing this issue?

**Comment by UmberFunk** [comment]
We tried a lot to find the reason of problem. Finally we found that the problem was caused by Facebook or iOS. We found a video where it was described how to repair Facebok performance on iOS. We made Network Settings reset and now it seems like the problem is solved.

Looks like the issue was not caused by your ANE, but anyway, it would have been great to see you supporting.

**Comment by myflashlab** [comment]
Glad to see the problem is fixed. would you please link to the video which has solved the issue. In the past month, as you might know, we have been busy working on the HUUGE Game Services ANE which is finally finished today and we are happy to be adding it to the club package. more than 20,000 lines of code and the whole team has been busy on making things work on that ANE which faded out our concentration on other tickets like this one. However, we're sure it worth it :)

**Comment by UmberFunk** [comment]
Awesome! I'm glad to hear from you again, especially with this great news!
We might be one of the first devs who will release a game with your GameCenter ANE.

Here's video:
https://www.youtube.com/watch?v=X1SO5yIdJWg&feature=youtu.be&t=75
