### ISSUE TITLE
Like a page in landscape, back and unlike buttons are off screen 

### ISSUE THREAD

**Issue by Selonie** [myflashlab/facebook-ANE#38]
Hi 
I don't know if this is an issue with Facebook, my code or the ANE, but if my app is in fixed landscape mode the web page / Facebook like page doesn't display correctly, it's as if the top notification bar is pushing the buttons partially off screen, has anyone else experienced this and if so is there a way to fix it. 
Edit: this is on an Android device.

**Comment by myflashlab** [comment]
The position of the like buttons are controlled from the Air side. you should listen to orientation changes and fix the position of any like button you might have on the screen when an orientation change happens. I hope this note helps.

**Comment by myflashlab** [comment]
Could you please update us about the status of this issue?

**Comment by Selonie** [comment]
It's not the position of the like buttons that is the problem; why do I have to listen for orientation changes as my app is fixed in landscape mode? When my app goes into the background and the Facebook dialogue box opens it is that box that doesn't fit the screen hence the UNLIKE and BACK buttons are off screen when in landscape.

Are you suggesting my fixed landscape app should switch into portrait mode when a user selects a like button just so the FB dialogue box displays correctly?

**Comment by myflashlab** [comment]
> We have updated the ANE to the latest SDK and a LOT has changed. for example like buttons and app invites have been deprecated but we have now added the GameRequest feature. Moreover, we have re-wrote the whole Actionscript part to be easier to work with. Please update yourself to the latest version and see how it goes. If you are still encountering any problem, please feel free to open a new issue and ask your questions. And by the way, when updating your app with the new ANE, make sure to read and follow the [new wiki documentations](https://github.com/myflashlab/facebook-ANE/wiki). Moreover, the asdoc has also moved to this package: http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/fb/package-detail.html

Also make sure to read the changelog to know what changes you need to make to your manifest. xml file.
