### ISSUE TITLE
Invite Error. Facebook don't return to APP after invite.

### ISSUE THREAD

**Issue by Gamezhero** [myflashlab/facebook-ANE#39]
Facebook don't back to APP after invite and reload my dashboard on facebook.
I have error on my iPhone 6 (9.3.1)

See video: https://www.youtube.com/watch?v=Xf5RS6NCDnE&feature=youtu.be

**Comment by Gamezhero** [comment]
I update my iPad 3 to 9.3.1. and got this error too.
I think it is critical issues for this ANE.

**Comment by myflashlab** [comment]
Please let us know if you have this problem with V4.11.0 also? it should be fixed now.

**Comment by Gamezhero** [comment]
Works great. Return!
