### ISSUE TITLE
Loading progress indicator circle jumps to side before disappearing

### ISSUE THREAD

**Issue by UmberFunk** [myflashlab/facebook-ANE#4]
We are using AIR 18.0.0.180 and Starling framework. Happens on Huawei G700. On Gallaxy Tab4 it doesn't jump. Will update info after we test on more devices.

**Comment by dr-andy** [comment]
same problem here. Using AIR 18 and starling.

**Comment by UmberFunk** [comment]
Is there any way to hide the loading process indicator? We have our own indicator and we'll show up it. Your ANE's circle doesn't fit our visual style.

**Comment by myflashlab** [comment]
try this: in your manifest, where you have 
```xml
<activity android:name="com.facebook.FacebookActivity" 			android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" 	android:theme="@style/Theme.Transparent" />
```
change 
```xml
android:theme="@style/Theme.Transparent"
```
to:
```xml
android:theme="@android:style/Theme.NoDisplay"
```
