### ISSUE TITLE
Crash App. Request Permission Error

### ISSUE THREAD

**Issue by Gamezhero** [myflashlab/facebook-ANE#40]
I need to use facebook score system and I can do it if have permission `Permissions.publish_actions` only.

I can't request permission with `LogManager.WITH_PUBLISH_PERMISSIONS` or `Permissions.publish_actions` becouse App crashed on Android and iOS

`FB.logManager.requestPermission(LogManager.WITH_PUBLISH_PERMISSIONS, Permissions.public_profile, Permissions.user_friends, Permissions.email);`

or 

`FB.logManager.requestPermission(LogManager.WITH_READ_PERMISSIONS, Permissions.public_profile, Permissions.user_friends, Permissions.email, Permissions.user_games_activity);`

It is second critical error in Facebook ANE. First #39 

P.S. Does ANE support POST in graph? 
http://prntscr.com/b08al6
I can't test it self while this BUG exist :(

**Comment by myflashlab** [comment]
We just released V4.11.0 please update yourself with this latest version and if you still have any problem, please post here including your error log.

**hint:** As suggested by Facebook, it's generally a good practice to request for ```FB.auth.requestPermission(Auth.WITH_READ_PERMISSIONS, Permissions.public_profile, Permissions.user_friends, Permissions.email);``` before asking for more permissions in your app.

**Comment by myflashlab** [comment]
>

yes, it does. the second parameter of the ```request``` method lets you set the URLRequestMethod
```actionscript
FB.graph.request("/me", URLRequestMethod.GET);
```

**Comment by Gamezhero** [comment]
Version V4.11.0 is crached with this code on iOS

`FB.auth.requestPermission(Auth.WITH_READ_PERMISSIONS, Permissions.public_profile, Permissions.user_friends, Permissions.email);`

Maybe need to change in manifest file?

**Comment by myflashlab** [comment]
There must be something going wrong on your intial setup. Please make sure
the manifest is set correctly based on samples we have put on GitHub. If
that doesn't ring a bell, post your manifest here so we can also have a
look. Don't worry we're here to help :)

On Monday, May 16, 2016, Gamezhero <notifications@github.com> wrote:

> Version V4.11.0 is crached with this code on iOS
>
> FB.auth.requestPermission(Auth.WITH_READ_PERMISSIONS,
> Permissions.public_profile, Permissions.user_friends, Permissions.email);
>
> Maybe need to change in manifest file?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/facebook-ANE/issues/40#issuecomment-219453171>
>


-- 
Sent from iPhone

**Comment by Gamezhero** [comment]
` <iPhone>
	    <InfoAdditions>
	        <![CDATA[
	        <key>MinimumOSVersion</key>
	        	<string>6.1</string>
	        <key>UIStatusBarStyle</key>
	        	<string>UIStatusBarStyleBlackOpaque</string>
	        <key>UIRequiresPersistentWiFi</key>
	        	<string>NO</string>
	        <key>UIFileSharingEnabled</key>
	        	<string>NO</string>
	        <key>UIPrerenderedIcon</key>
	        	<true />
	       
	        <key>FacebookAppID</key>
	        	<string>1091796000843299</string>
	        <key>FacebookDisplayName</key>
	        	<string>Crashzilla</string>
	       
	        
	        <key>CFBundleURLTypes</key>
	        <array>
	            <dict>
	                <key>CFBundleURLSchemes</key>
	                <array>
	                    <string>fb1091796000843299</string>
	                    <string>air.com.doitflash.exfacebook2</string>
	                </array>
	            </dict>
	        </array>
	       
	        <key>UIDeviceFamily</key>
	        <array>
	            <string>1</string>
	            <string>2</string>
	        </array>
	        ]]>
	    </InfoAdditions>
	    <requestedDisplayResolution>high</requestedDisplayResolution>
  	</iPhone>
<extensions>
	   	<extensionID>com.myflashlab.air.extensions.facebook</extensionID>
	    
    	<extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.drive</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.games</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.gcm</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.location</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.plus</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    </extensions>`

This manifest works great with previous vertsion ANE

**Comment by myflashlab** [comment]
Well, you have forgotten to white list facebook domain names. Please check
the demo manifest here
https://github.com/myflashlab/facebook-ANE/blob/master/README.md#air-xml-manifest

Note: you don't have to embed the google services dependency ANEs. Just the
override.ane and androidsupport.ane are needed. Please make sure to read
the documention completely. After you changed them, let us know how it went.

On Monday, May 16, 2016, Gamezhero <notifications@github.com> wrote:

> `
>
> <![CDATA[
> MinimumOSVersion
> 6.1
> UIStatusBarStyle
> UIStatusBarStyleBlackOpaque
> UIRequiresPersistentWiFi
> NO
> UIFileSharingEnabled
> NO
> UIPrerenderedIcon
>
>         <key>FacebookAppID</key>
>             <string>1091796000843299</string>
>         <key>FacebookDisplayName</key>
>             <string>Crashzilla</string>
>
>         
>         <key>CFBundleURLTypes</key>
>         <array>
>             <dict>
>                 <key>CFBundleURLSchemes</key>
>                 <array>
>                     <string>fb1091796000843299</string>
>                     <string>air.com.doitflash.exfacebook2</string>
>                 </array>
>             </dict>
>         </array>
>
>         <key>UIDeviceFamily</key>
>         <array>
>             <string>1</string>
>             <string>2</string>
>         </array>
>         ]]>
>     </InfoAdditions>
>     <requestedDisplayResolution>high</requestedDisplayResolution>
> </iPhone>
>
>
> com.myflashlab.air.extensions.facebook
>
>     <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
>     <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
>     <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
>     <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.drive</extensionID>
>     <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.games</extensionID>
>     <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.gcm</extensionID>
>     <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.location</extensionID>
>     <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.plus</extensionID>
>     <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
> </extensions>`
>
> This manifest works great with previous vertsion ANE
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/facebook-ANE/issues/40#issuecomment-219464954>
>


-- 
Sent from iPhone

**Comment by Gamezhero** [comment]
works with new manifest file.
