### ISSUE TITLE
ArgumentError: Error #3500: The extension context does not have a method with the name command.

### ISSUE THREAD

**Issue by redcodelabs** [myflashlab/facebook-ANE#45]
Dear @myflashlab,

Thanks for the support in building this ANE.
I am having issues in regard to setting up the sample you provide in the Readme.md with FlashBuilder Mobile Application Project.

I have already made a comment on https://github.com/myflashlab/facebook-ANE/issues/23 but since the ticket is marked as resolved it may be possible that it did not came to your attention.

Could you be kind and have a look at the comment I made and get back to me with hints on how I can solve the issue ?

Thanks in advance,
Adrian

**Comment by myflashlab** [comment]
sure, to download Air SDK 22, you need to check the beta channel [here](http://www.adobe.com/devnet/air/air-sdk-download.html) it's not an alpha release yet.

**Comment by myflashlab** [comment]
after updating to Air 22 and you still have a question, please feel free to re-open the issue and we'll try to help. Thanks.
