### ISSUE TITLE
Needs login for share & invite (iOs 9.3.2, iPhone 6)

### ISSUE THREAD

**Issue by Gamezhero** [myflashlab/facebook-ANE#46]
I logined and ANE return me true
`FB.logManager.isLogin; //true`

but if I try to share or invite I see login form again 
I dont login and close it and check 
`FB.logManager.isLogin; //true`
I am logined but why need to login in share & invite again?
I used last version from v20

It worked before, but now I see grey Safari in app (before was white)

What may be?

**Comment by Gamezhero** [comment]
I found https://discussions.apple.com/thread/5539165?tstart=0
self fixed :)
close it

**Comment by myflashlab** [comment]
https://discussions.apple.com/thread/5539165?tstart=0
> She has Private browsing on.
Close all the tabs and tap the word Private on the bottom left
