### ISSUE TITLE
App Events

### ISSUE THREAD

**Issue by PavelSyr** [myflashlab/facebook-ANE#5]
Hi,

Do have any plans to add App Events?
More info https://developers.facebook.com/docs/app-events

thx a lot

**Comment by myflashlab** [comment]
Thanks for your comment but we still don't have a schedule for AppEvents. we are more focused on interactive features as right now as they will be more needed by users. as an example, we will have AppInvite for the next release. yet, if you need AppEvents badly, you may contact us from our website directly.
