### ISSUE TITLE
The ANE doesn't store the login session

### ISSUE THREAD

**Issue by ionutmihaila** [myflashlab/facebook-ANE#50]
Hi guys,

Seems that this ANE doesn't store the login session.
Steps to reproduce:
1. Open app
2. Login on FB
3. Exit app
4. Turn off/on the handset (or wait couple of hours)
5. Reopen the app - here the login session is lost so you'll have to relogin, which is a bad experience.

Can you please fix this in next release or is there any workaround to avoid this?

Thank you,
Ionut

**Comment by ionutmihaila** [comment]
Got a fix, looks like you can call FB.graph.request to see if user it's logged in..
Cheers!

**Comment by myflashlab** [comment]
Moreover, have you checked FB.auth.token or FB.auth.isLogin commands? They
should help you with that. Let us know if you have trouble using them?

On Saturday, July 9, 2016, ionutmihaila <notifications@github.com> wrote:

> Closed #50 <https://github.com/myflashlab/facebook-ANE/issues/50>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/myflashlab/facebook-ANE/issues/50#event-717748640>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABnVFP62QZwyQaDFEkzk-A5lIdIEcGx5ks5qT2DVgaJpZM4JIk6Z>
> .
>


-- 
Sent from iPhone

**Comment by ionutmihaila** [comment]
Thank you :)
