### ISSUE TITLE
Can't get login screen to show up on Anndroid

### ISSUE THREAD

**Issue by Guarionex** [myflashlab/facebook-ANE#53]
So I made a demo project to try out this ANE for it's log in feature and it work greats! But now that I'm trying to add it to our main game project I can't get it to show up. 
I have it setup the exact same way as I did in my demo project; I called FB.getInstance, passed in our facebook app ID, I did the FB.hashKey, copy pasted it into Facebook app's settings on android platform, then add all the login listeners and call requestPermission. In the demo project I made, the dialog comes up right away, in our game project nothing happens. I don't know if it's an issue or not, but the two projects generated the same hashKey, sp I'm wondering if Facebook is getting confused that two separate apps are trying to access the Facebook app using the same hashKey. Maybe it is coming up, but it' behind my game? Any ideas?

**Comment by myflashlab** [comment]
Well, if you are trying this on two different apps, that would mean you are using different package names. And different package names need different cerificates which results in different keyHash values. If you are seeing the very same hashkey, you should recheck your configurations.

**Comment by Guarionex** [comment]
Which configurations should I be looking at? BTW thanks for the fast feedback

**Comment by myflashlab** [comment]
Let me put it this way, two apps, two different package names, two different.p12 cerificates and so, you will need two different Facebook apps you should create.

You have been able to make it work fine for the first time, I'm sure you can do that again if you start fresh on your other project without confusing the two projects with each other.

> BTW thanks for the fast feedback 

No problem :)

**Comment by Guarionex** [comment]
I just tried making a new facebook app and linking the game to that, but it still get nothing. Is there a different way to generate a hash key or could it just be something else entirely?

**Comment by myflashlab** [comment]
yes, there are. please read the official Facebook documentation where they have explained how to do it manually: https://developers.facebook.com/docs/android/getting-started#release-key-hash
It's a little complicated and that's why we did it inside the ANE. but that's the actual way to generate the key hash.

**Comment by Guarionex** [comment]
Well I'm able to generate a hash key in the manner the Facebook guide indicates; even makes a key different that the one made by FB.hashKey, but I'm still unable to connect to Faceboook. I tried making a second demo project with the exact same code as the working project, but with different certificate, to try an replicate the problem. The second project will also not connect with the FB.hashKey (which is still the same hash key) I tried generating the has key using the command line, which gave me a unique hash key, but still nothing :cry:

**Comment by Guarionex** [comment]
Is there a way to get a console log to see if there where any errors when trying to connect to Facebook?

**Comment by Guarionex** [comment]
Also does FB.hashKey not work when running the app normally (not in debug mode).

**Comment by myflashlab** [comment]
here are some hints:

1. If you are using FlashBuilder, you must be careful about the package name changes that FlashBuilder does automatically. i.e when you are running in debug mode, your package name has an extra ```.debug``` compared to when you are releasing. That might be the problem.

2. You may install Android Studio and open the logcat console and watch the logs. Watch the logs and you might find some answers there.

3. ```FB.hashKey``` always works!

4. If you are a club member, please send us your demo project by email so we can investigate this more.

**Comment by Guarionex** [comment]
Figured it out, nothing to do with hashKey, simply forgot the intent filters on the manifest. Thanks for helping me out though!
