### ISSUE TITLE
Facebook ANE getInstance() defaults to "00000000000"

### ISSUE THREAD

**Issue by veselekov** [myflashlab/facebook-ANE#54]
see
http://puu.sh/qn4PT/06a9a6c6a7.jpg

Not sure what is going on but for some reason the facebook ANE doesn't accept my app ID. I am using the commercial one too :/

**Comment by myflashlab** [comment]
Are you sure you have set your manifest settings correctly? please post your manifest .xml file here if your not sure. This link might also help you: https://github.com/myflashlab/facebook-ANE/issues/53

**Comment by veselekov** [comment]
Yes that seemed to be it! Thanks so much for the swift reply! FIXED
