### ISSUE TITLE
Retaining a facebook user

### ISSUE THREAD

**Issue by Guarionex** [myflashlab/facebook-ANE#55]
So currently my game is setup to have a guest user player account and a facebook player user account if a player presses a login button and then goes through this ANE's login in flow. As it stands every time a player starts the app, he/she will need to press the login button to get their facebook player account. Is there a way through your ANE to know that a player has already signed into facebook through my app before so that next time the person starts the app, it will log them in automatically?

**Comment by myflashlab** [comment]
Of course, there's a property that checks if you are logged in or not. ```FB.auth.isLogin``` check here for more details: https://github.com/myflashlab/facebook-ANE/blob/master/FD/src/Demo.as#L173-L185

**Comment by Guarionex** [comment]
That worked perfectly, thanks!
