### ISSUE TITLE
Inviting friends with custom dialog

### ISSUE THREAD

**Issue by Guarionex** [myflashlab/facebook-ANE#56]
Hello, I'm trying to make a way to invite friends using my own custom dialog. I know this ANE has it's own, but I want to be able to use an interface that works with our theme. I was reading on FB's documentation to make a graph api call using apprequest, but I can't find any documentation for the syntax of the request to pass into FB.graph.request. I tried passing in /me/apprequest?message=+message+&to="idList.join(",") with the method parameter set to "POST", but nothing happens Any help in how to properly send an apprequest to invite friends?

**Comment by Guarionex** [comment]
So I figured out a few things such as the correct usage of apprequests in graph is "/{idsOfFriendsToInvite}/apprequests?message="+message+"&action_type=INVITE" with the method parameter set to "POST", but now graph returns (#803) Some of the aliases you requested do not exist. Note I'm using the id token from the invitable_friends that I get from graph. I read somewhere that facebook doesn't allow to send invites through graph api, but it doesn't make sense, because Facebook's documentation says that if you use a custom dialog to use the graph api call to apprequests. Any help, light, or way to use my custom dialog with the ANE's way of doing friend invite?

**Comment by myflashlab** [comment]
hmm, we really don't know as we haven't tried that before. I think the best place you can ask these questions is iOS or Android forums (Stackoverflow). They might be able to help you better.

You see, with the ANE job, we are mirroring native functionality to ActionScript but how the native works deep inside is out of our help focus. Thanks.
