### ISSUE TITLE
Compiling for iOS results in "Compilation failed while executing : ld64"

### ISSUE THREAD

**Issue by gsemerdjiev** [myflashlab/facebook-ANE#58]
Hello,

Sorry for creating another issue for this. I looked at the other related issues i found (https://github.com/myflashlab/facebook-ANE/issues/43 and https://github.com/myflashlab/facebook-ANE/issues/35) but the solutions there does not help. I always get this error:

ld: framework not found FBSDKCoreKit
ld: framework not found FBSDKCoreKit
Compilation failed while executing : ld64

I'm using:
 FlashDevelop
 Flex 4.15.0
 AIR 23

The only extensions added are myflashlab extensions:
<extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
<extensionID>com.myflashlab.air.extensions.facebook</extensionID>

Please, can you help me fix this.

Best,
Georgi

**Comment by myflashlab** [comment]
Well, missing ```FBSDKCoreKit``` means that you have not copied the .framework files to your AIR SDK. Please [read section 3](https://github.com/myflashlab/facebook-ANE#requirements) of the requirements and you'll know where to put the framework files.

> The only extensions added are myflashlab extensions:
com.myflashlab.air.extensions.dependency.androidSupport
com.myflashlab.air.extensions.dependency.overrideAir
com.myflashlab.air.extensions.facebook

FYI: the dependency ANEs are only required on the Android side. On the iOS side, you will need the .framework files as explained above.

**Comment by myflashlab** [comment]
Will you update us about this issue? if you have more questions, please feel free to ask.

**Comment by gsemerdjiev** [comment]
Sorry, I've forgotten to update the issue.
Your suggestion solved the problem.
Thanks.
