### ISSUE TITLE
Regaining focus after Sharing

### ISSUE THREAD

**Issue by Guarionex** [myflashlab/facebook-ANE#59]
So I've implemented the sharing feature and it works great! However, when I'm done sharing and the dialog closes, the notification bar remains. The only solution I've found so far is: 
```ActionScript
Starling.current.nativeStage.displayState = StageDisplayState.FULL_SCREEN;
```
However, this will cause the app to blink (fade to a dark screen and fade back in). Are you guys familiar with a way to avoid the blinking or avoid the notification bar coming down to begin with when sharing?

**Comment by Guarionex** [comment]
Turns out I was using the activate and deactivate listeners incorrectly and I was setting the StageDisplayState to Normal and back to full screen in colliding times. Everything works great

**Comment by myflashlab** [comment]
Good! We really had no idea what to reply back :smile:
