### ISSUE TITLE
INSTALL_FAILED_CONFLICTING_PROVIDER

### ISSUE THREAD

**Issue by UmberFunk** [myflashlab/facebook-ANE#6]
Hello,

We need to have two versions of app on the device. We get INSTALL_FAILED_CONFLICTING_PROVIDER when installing second app on Android device.

Wouldn't it cause problems if we add something like 1234 to our Facebook app id?
FacebookContentProvider{APP_ID}1234

Regards,
Irakli

**Comment by myflashlab** [comment]
you can't have two different apps with only one FacebookApp! if you are building a new app, you have to create a new Facebook app too which will give you a new APP_ID of course.

**Comment by UmberFunk** [comment]
Sure? I added 1 to the end of (FacebookContentProvider{APP_ID}1) in descriptor and looks like it's working. I want to know if it can cause any problems.

I think you misunderstood something in my question.

**Comment by myflashlab** [comment]
well, although you may be able to compile the app with that trick but you can't be sure if all the FB SDK functionality would work as expected anymore because the FB app won't be able to link to your app if the content provider is invalid.

**Comment by UmberFunk** [comment]
Everything was working the same before we replaced zeroes with our APP ID yesterday. We didn't spotted any issues with FB linking. 

Let us know if you find out any info in this.
