### ISSUE TITLE
Collision with other ANE's?

### ISSUE THREAD

**Issue by siknasty106** [myflashlab/facebook-ANE#60]
Hello!  Currently we are trying to use your ANE for our facebook integration, but we ran into an interesting issue...It seems to have some sort of collision with android purchasing ANE's.  

I have tried using both FreshPlanet's InAppPurchaseANE as well as Milkmans android purchasing ANE.  Both ANE's have the same failure point when used in conjunction with this facebook ane.

IF one calls.  FB.getInstance("<appID>") before the android purchasing ANE is initialized, part of the functionality for the latter ANE does not work.  Reversing the order of operations, allows both to work.  The fact that the facebook ANE does this for two separate ANE's from two separate companies, seems to point that their might be something awry in this one.  Any thoughts or ideas?

**Comment by myflashlab** [comment]
Thanks for reporting this but we really can't guarantee how ANEs (from different providers) would work while using them all together. What we can guarantee is that you can use ALL our ANEs without seeing any conflict error messages. I wonder if you have tried our [in-app-billing ANE](https://github.com/myflashlab/inAppPayments-ANE/)? I have to close this issue as there's nothing we can do about it. The best we could do was to invite other ANE developers to use our [dependency ANEs](https://github.com/myflashlab/common-dependencies-ANE) to avoid such collisions.
