### ISSUE TITLE
Nothing happens after getting hash

### ISSUE THREAD

**Issue by arsyad** [myflashlab/facebook-ANE#61]
Hi,

I've sent an email on this issue as I joined as a club member but no response. By the way, we tried this ANE but it doesn't seem to work. Nothing happens after we do a Auth permissions request. I could see the hash but that's it.

Calls to FB.auth.requestPermission or FB.graph.request doesn't seem to fire any of the events.

**Comment by myflashlab** [comment]
Hi @arsyad there could be many reasons but we need more information about this to be able to provide a helpful answer.

The first thing you should make sure is that if you have set the AIR manifest settings correctly. Then, connect your device to your computer and send us logcat for Android or xcode logs for iOS. Maybe with more information about the problem we would be able to help better.

**Comment by arsyad** [comment]
Hi,

I've sent the manifest file over in my email to the direct club support.
Are you able to get it from there?

Regards,
Arsyad

**Comment by myflashlab** [comment]
Aha, thanks for letting us know that. Well, just checked your manifest file and I did find the problem. Here's an example: you have ```com.smashingclicks.smashingheroes.facebook.sharing.MyShare``` This is wrong.

To fix the problem, please go through the [manifest reference](https://github.com/myflashlab/facebook-ANE#air-xml-manifest) once again but this time make sure you are replacing any app name starting with ```air.....``` to your own package name but keep everything else the same.

As an example, ```com.doitflash.facebook.sharing.MyShare``` is actually a class name we are using natively to reference the share window and you must keep the address as it is with no change.

**Comment by arsyad** [comment]
It works now. Actually, the issue was me putting in some of the manifest additions outside of the <application> tag. That's pretty silly.

Now I have another problem. The compiler doesn't compile for iOS. It complains "error 105: application.iPhone.InfoAdditions contains an invalid value".

I don't know if there's any typo but I went through it and cannot detect it. It compiles for iOS if I remove this whole chunk:

```
<key>NSAppTransportSecurity</key>
            <dict>
                <key>NSExceptionDomains</key>
                <dict>
                    <key>facebook.com</key>
                    <dict>
                        <key>NSIncludesSubdomains</key>
                        <true/>
                        <key>NSExceptionRequiresForwardSecrecy</key>
                        <false/>
                    </dict>
                    <key>fbcdn.net</key>
                    <dict>
                        <key>NSIncludesSubdomains</key>
                        <true/>
                        <key>NSExceptionRequiresForwardSecrecy</key>
                        <false/>
                    </dict>
                    <key>akamaihd.net</key>
                    <dict>
                        <key>NSIncludesSubdomains</key>
                        <true/>
                        <key>NSExceptionRequiresForwardSecrecy</key>
                        <false/>
                    </dict>
                </dict>
            </dict>
```

**Comment by myflashlab** [comment]
Hmm, It looks all good, Please make sure you are using the latest AIR SDK. Please take this manifest file as a reference and see how it goes: https://github.com/myflashlab/facebook-ANE/blob/master/FD/application.xml

**Comment by arsyad** [comment]
I tried with the latest AIR SDK version 23.0.0.257 but still getting that error.

**Comment by arsyad** [comment]
I've managed to compile. I realised there was another NSAppTransportSecurity tag inserted before those lines. Thanks for the help. We can close this now.
