### ISSUE TITLE
(Send Dialog) Available?

### ISSUE THREAD

**Issue by mrgoonie** [myflashlab/facebook-ANE#63]
Just asking, is the Send Dialog feature available in this ANE?

FYI: https://developers.facebook.com/docs/sharing/ios/send-button

Thanks,

**Comment by myflashlab** [comment]
We do have plans to add that in future updates. I just marked this question and will update it as soon as it is available. Thanks.

**Comment by myflashlab** [comment]
> We have updated the ANE to the latest SDK and a LOT has changed. for example like buttons and app invites have been deprecated but we have now added the GameRequest feature. Moreover, we have re-wrote the whole Actionscript part to be easier to work with. Please update yourself to the latest version and see how it goes. If you are still encountering any problem, please feel free to open a new issue and ask your questions. And by the way, when updating your app with the new ANE, make sure to read and follow the [new wiki documentations](https://github.com/myflashlab/facebook-ANE/wiki). Moreover, the asdoc has also moved to this package: http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/fb/package-detail.html

Also make sure to read the changelog to know what changes you need to make to your manifest. xml file.
