### ISSUE TITLE
Like Button is not working in AIR 24 (Android)

### ISSUE THREAD

**Issue by ionutmihaila** [myflashlab/facebook-ANE#65]
Hi guys,

Like button is not working in AIR 24 on Android. It's tring to open the screen with "You now like...", but fails and nothing happens. Tested on Android 6.0.1

Can you please check?

Thank you,
Ionut

**Comment by myflashlab** [comment]
hmm, do you think this link can be related to your question: http://stackoverflow.com/questions/30071536/like-button-for-android-only-works-for-administrator-of-app if so, let us know how it goes.

**Comment by ionutmihaila** [comment]
You're right, without FB approval, Like button works only for app admin. Many thanks!
