### ISSUE TITLE
error for IOS

### ISSUE THREAD

**Issue by amihanya** [myflashlab/facebook-ANE#67]
(flashDevelop)
ld: framework not found FBSDKCoreKit
ld: framework not found FBSDKCoreKit
Compilation failed while executing : ld64

if i set:
hideAneLibSymbols yes

i get only this error:
Compilation failed while executing : ld64

i do this: https://github.com/myflashlab/facebook-ANE#requirements

but stile get the error.

**Comment by amihanya** [comment]
ok i download from here: https://developers.facebook.com/docs/ios
ths facebook sdk and put the folder on lib\aot\stub and its work.

**Comment by myflashlab** [comment]
to download the exact frameworks compatible with the ANE, try downloading them from here: https://github.com/myflashlab/facebook-ANE/blob/master/FB_SDK_FRAMEWORKS.zip
