### ISSUE TITLE
Compile errors from the Sample files.

### ISSUE THREAD

**Issue by mmiinnovations** [myflashlab/facebook-ANE#68]
I purchased the Club but I'm having problems getting the ANE's to work.

On the FB ANE I'm getting compile errors from the Sample files.

Here are the errors when compiling the SampleLogin.as  (I'm testing the movie from inside Adobe Animate CC IDE):

/MyFlashLabClub_ANEs_packageV34/ANEs/facebook/facebook-ANE-master/FD/src/SampleLogin.as, Line 176, Column 34	1046: Type was not found or was not a compile-time constant: FBEvent.

/MyFlashLabClub_ANEs_packageV34/ANEs/facebook/facebook-ANE-master/FD/src/SampleLogin.as, Line 185, Column 35	1046: Type was not found or was not a compile-time constant: FBEvent.

/MyFlashLabClub_ANEs_packageV34/ANEs/facebook/facebook-ANE-master/FD/src/SampleLogin.as, Line 194, Column 32	1046: Type was not found or was not a compile-time constant: FBEvent.

So I can't get it to work at all and the documentation doesn't help much with starting use of the ANE's.

What now? And is this how I'm supposed to get support?

**Comment by myflashlab** [comment]
> What now? And is this how I'm supposed to get support?

Yes, posting questions on GitHub is a great way to get support as we are monitoring the issues and try to answer them as fast as possible. This will help others to solve their own problems with similar issues. For club members though, you have the option to email us directly also but we do appreciate if you keep the tech questions on GitHub so everyone can see them.

So, the error messages you are seeing means that the ANEs have not been correctly embedded in your project. That might happen if you are trying to run the ANE on a simulator. to solve the problem, try running on a real device. If you are running on a real device and still see this error messages, then you must have missed to implement the ANE in the AIR manifest .xml file. I suggest you to watch these videos as they will help you in embedding the ANEs: https://www.youtube.com/playlist?list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O

Moreover, we have an [ANE inspector tool](http://www.myflashlabs.com/a-tool-to-make-ane-integration-into-your-air-apps-a-breeze/) which can help you in implementing our ANEs in your projects.

**Comment by mmiinnovations** [comment]
The inspector tool won't work either. I followed your tutorial video but it still won't work. Is there a better tutorial somewhere with better English?

**Comment by myflashlab** [comment]
Have you added ANEs in your projects before? This is not a different thing! Take your time and read the documentations/watch the videos, always use the latest AIR SDK (24 at the moment) and you'll be fine. Many AIR devs are using these ANEs. If you still see that error message, post your AIR manifest .xml file so we can have a look.

**Comment by mmiinnovations** [comment]
No this is new to me. I'm just now coming back to Flash game dev after leaving it in 2010 because of Apple. Now I'm back and trying to learn to compile for mobile.

I'm no rookie programmer but I'm missing something. No matter what I do it won't compile even using the simple samples you've added. I don't have an Android device to test with so I'm using iphone 6.

I'm using the xml manifest from the sample files and using AnimateCC. The file is attached here.

I guess I’m missing the proper testing workflow for working on a device. This seems really slow way to test an app compiling each time to the device. I have a very fast computer (new iMac with maxed RAM and processor available) but it still takes over a minute to compile and THEN throws errors. This is a very slow process. There's no way I'm doing this right. It would take years to develop an app this way.

**Comment by myflashlab** [comment]
First of all, welcome back :) we are sure you will love coding in AIR again like old Flash times. Alright, I just had a look at your .xml manifest and it's no wonder why it won't compile. There are a lot of missing parts in it. While I'm saying that, you don't need to be scared at all. once you get familiar with how the manifest in AIR works, you will be able to easily embed ANY ANE into your projects.

To help you out, I'd suggest you to drop us an email from www.myflashlabs.com/contact/ while referencing to this discussion we've had hear so my colleagues can help you more. We are trying to keep the issues' pages restricted to direct ANE tech questions rather than general ANE questions. Thanks.
