### ISSUE TITLE
Starling + AIR SDK 24 + Facebook ANE = Android black screen + Starling loss context

### ISSUE THREAD

**Issue by majidatidrai** [myflashlab/facebook-ANE#69]
I already tried all the possible solutions but it doesn't seems to work. 
This problem only happens on Android (in my case: Samsung J7 Prime - Android 6.0.1)

When I used Facebook ANE v.4.11 in my app before, it's totally fine with AIR SDK 23, until I upgrade into AIR SDK 24 and use the new Facebook ANE 4.17, when I login it only show the rotating preloader with the black background behind (instead of the app screen like the previous version). In the console, it said "[Starling] Context restored." a few times - so I guess Starling has lost the context because starling has lost its focus. 

After logged in successfully, the black screen disappear, if I got lucky, the blank white scene show up, and the app start rendering very-very-slow each elements, sometime the black screen doesn't disappear at all, it was just getting stuck right there and crash the app. 

I'm thinking might be this line in the manifest that causing the black screen issue:
```
<!-- This is required for logging in -->
<activity android:name="com.facebook.FacebookActivity" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:theme="@android:style/Theme.Translucent.NoTitleBar" />
<activity android:name="com.doitflash.facebook.access.MyLogin" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:theme="@style/Theme.Transparent" />
```
But if I use the old tag from the Facebook ANE version V4.11, it will crash the app. 

I know it's too much to ask, but let get back to the slowly rendering after logged in, the Starling context was lost and when it goes back focus to the app, it start to render again (but very slow - likely one by one). Since "Starling.handleLostContext = true" is not available anymore, may I ask if someone faced this issue before and have the solution for it?

I got stuck on this one for hours :( please help!

A bunch of thanks!!!

**Comment by myflashlab** [comment]
I didn't know ```Starling.handleLostContext = true``` is not available anymore! We have not played with Starling (especially V2) for a while but we are interested to see this new black screen problem. If you can prepare a very simple **FlashDevelop** project for us so we can duplicate the problem here locally, we'll try to find a solution for this. (Make sure you are not sending over the licensed ANEs in the sample project you are creating)

**Comment by myflashlab** [comment]
> We have updated the ANE to the latest SDK and a LOT has changed. for example like buttons and app invites have been deprecated but we have now added the GameRequest feature. Moreover, we have re-wrote the whole Actionscript part to be easier to work with. Please update yourself to the latest version and see how it goes. If you are still encountering any problem, please feel free to open a new issue and ask your questions. And by the way, when updating your app with the new ANE, make sure to read and follow the [new wiki documentations](https://github.com/myflashlab/facebook-ANE/wiki). Moreover, the asdoc has also moved to this package: http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/fb/package-detail.html

Also make sure to read the changelog to know what changes you need to make to your manifest. xml file.
