### ISSUE TITLE
Incorrect Facebook log-in screen size when there is no Facebook app installed on a device

### ISSUE THREAD

**Issue by UmberFunk** [myflashlab/facebook-ANE#7]
Hello again,

See the images and you will understand the issue:

Nexus 10
http://i.imgur.com/NbKc3nf.png

Huawei G700
http://i.imgur.com/FXxwLgB.png

This issue is very problematic for our project. Hope you can fix it soon.

Regards,
Irakli

**Comment by myflashlab** [comment]
Seems like a nice game :) make sure to give back the link when it's on app store.

anyway, I didn't see any problem in the screenshots. it is correct that when the FB app is not installed, a webView will open automatically.

if you are asking about the size difference. that's not in our hands at all. it's the Facebook SDK which decides about that internally.

**Comment by UmberFunk** [comment]
Glad you like it. :) We'll notify you as soon as we'll put it in the app stores.

That's a huge problem. There should be a way to fix it. 

We have webView for game requests in our application and it's opening in full screen without any problems. 
webView.viewPort = new Rectangle( 0, 0, stage.stageWidth, stage.stageHeight); 
Facebook mobile webpage is scaled automatically according to webView dimensions.

P.S. You told you have game requests feature on the way. Is there any updates?

**Comment by myflashlab** [comment]
> P.S. You told you have game requests feature on the way. Is there any updates?

We released V3.0 yesterday which now supports App invites. game requests is next in our list.

**Comment by UmberFunk** [comment]
Please add me to the mailing list. I didn't knew there was a new version. 

I thought Facebook invites is same as Game Requests. Facebook Game Requests are used for invites. Maybe you divided it for some case in your ANE.

Please, update me on log-in screen size issue. That is very important and I'm sure it is very easily solvable.

**Comment by myflashlab** [comment]
> Please add me to the mailing list

We don't have a mailing list yet but we are working on myappsnippet.com and will soon move to a new server with a new look, new features, etc. till then, you can follow us on Twitter and facebook

> Please, update me on log-in screen size issue

I don't think we can do anything about it as I said it's being managed by Facebook SDK internally. but I'll ask the dev guys to have a closer look into it.

**Comment by UmberFunk** [comment]
It's early to close this issue.

As I thought and you said, it is webView. WebView size can't be managed by Facebook SDK.

**Comment by UmberFunk** [comment]
I'll be disappointed very much with your product and team if you can't fix such important and easy to fix issue.

**Comment by myflashlab** [comment]
> I'll be disappointed very much with your product and team if you can't fix such important and easy to fix issue.

I don't think we can do anything about it as I said it's being managed by Facebook SDK internally. but I'll ask the dev guys to have a closer look into it.

**Comment by UmberFunk** [comment]
We made a research. Checked multiple games from big publishers (Rovio, King, Gameloft, SGN) and looks like even they can't manage to fix it. 

Sorry guys for pushing on you. I misunderstood about webView. Thought it was Flash StageWebView frequently refereed as webView. Didn't knew if Facebook webView existed. 

Best,
Irakli
