### ISSUE TITLE
Runtime error using facebook-ANE with AIR24

### ISSUE THREAD

**Issue by yuhengh** [myflashlab/facebook-ANE#70]
Hi, 

I am getting this error when running the demo project

[AIR Debug Launcher]: Error: The extension com.myflashlab.air.extensions.facebook has either a namespace version or library.swf with a version that is incompatible with the applications namespace or root SWF.

I'm using AIR24 and compile with IntelliJ IDEA.

Any idea? Thanks.

**Comment by lerpinglemur** [comment]
I have this same error. I can't do a thing with the plugin. Other plugins I have are working fine.

**Comment by lerpinglemur** [comment]
First problem was the Min. OS version is 8.0, but I was following the online tutorial which said it was 6.1. Then Chartboost had told me to set swf-version=33 compiler option, but this is way outdated, and if you have the latest AIRSDK you can leave it out.

**Comment by reyco1** [comment]
I'm having the same problem. I am trying to use it in conjunction with the Firebase Auth ANE in order to allow users to login with Facebook but I'm getting the same error.

**Comment by reyco1** [comment]
Ok, this was fixed by updating to Flex SDK 25 and setting the compiler option -swf-version=35

**Comment by myflashlab** [comment]
> We have updated the ANE to the latest SDK and a LOT has changed. for example like buttons and app invites have been deprecated but we have now added the GameRequest feature. Moreover, we have re-wrote the whole Actionscript part to be easier to work with. Please update yourself to the latest version and see how it goes. If you are still encountering any problem, please feel free to open a new issue and ask your questions. And by the way, when updating your app with the new ANE, make sure to read and follow the [new wiki documentations](https://github.com/myflashlab/facebook-ANE/wiki). Moreover, the asdoc has also moved to this package: http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/fb/package-detail.html

Also make sure to read the changelog to know what changes you need to make to your manifest. xml file.
