### ISSUE TITLE
(AppInvite) Support Promotional Codes?

### ISSUE THREAD

**Issue by mrgoonie** [myflashlab/facebook-ANE#71]
Refer to this link: https://developers.facebook.com/docs/app-invites/ios#Support_Promotional_Codes

Let say that I want to send the app invite to my friends on Facebook, I would like to receive a promo code if one of my friends installed the app. 

Can I do this with the current Facebook ANE at the moment? How can I handle the callback link?

Thanks,

**Comment by myflashlab** [comment]
> We have updated the ANE to the latest SDK and a LOT has changed. for example like buttons and app invites have been deprecated but we have now added the GameRequest feature. Moreover, we have re-wrote the whole Actionscript part to be easier to work with. Please update yourself to the latest version and see how it goes. If you are still encountering any problem, please feel free to open a new issue and ask your questions. And by the way, when updating your app with the new ANE, make sure to read and follow the [new wiki documentations](https://github.com/myflashlab/facebook-ANE/wiki). Moreover, the asdoc has also moved to this package: http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/fb/package-detail.html

Also make sure to read the changelog to know what changes you need to make to your manifest. xml file.
