### ISSUE TITLE
Can't logout in iOS

### ISSUE THREAD

**Issue by PatrickJen** [myflashlab/facebook-ANE#72]
I'm using Facebook-ANE v4.11 because I can't get my app to compile with Air SDK24 which v4.17 requires.

On Android everything works fine as expected. When I call FB.auth.logout() and then call FB.auth.requestPermission(...) I have to login to FB with username and password. But on iOS it won't logout and when I call FB.auth.requestPermission(...) it bypasses the login screen and goes straight to the confirm screen. The same thing happens on my iPhone5 and iPad2 both with latest versions of iOS. Please check into this issue. Thanks.

**Comment by chanra** [comment]
I have the same issue with the latest version V4.17.0
For both iOS and Android, logout doesn't works. Once the logout button is clicked i call this FB.auth.logout(), after i clicked login again, it suppose to ask user for enter the username and password but it didn't. Please check and advise me to fix this issue. Thanks.

**Comment by chanra** [comment]
If possible could you give me an example of using Facebook Login/Logout properly?

**Comment by myflashlab** [comment]
> We have updated the ANE to the latest SDK and a LOT has changed. for example like buttons and app invites have been deprecated but we have now added the GameRequest feature. Moreover, we have re-wrote the whole Actionscript part to be easier to work with. Please update yourself to the latest version and see how it goes. If you are still encountering any problem, please feel free to open a new issue and ask your questions. And by the way, when updating your app with the new ANE, make sure to read and follow the [new wiki documentations](https://github.com/myflashlab/facebook-ANE/wiki). Moreover, the asdoc has also moved to this package: http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/fb/package-detail.html

Also make sure to read the changelog to know what changes you need to make to your manifest. xml file.
