### ISSUE TITLE
Cant get iOS to work!

### ISSUE THREAD

**Issue by FrogDigital** [myflashlab/facebook-ANE#73]
Ive just downloaded, installed and setup the ANE to work with my Facebook app.
I followed all the instructions but I cannot get my iOS Air app to log in to my Facebook app.
Ive no idea what I have missed.

Your tutorials and documentation arent very good if you dont have any previous experience using ANE's as they assume alot of knowledge already.

Currently, I can get the FB.getInstance() call to return **TRUE**, but when I then call 
FB.auth.requestPermission(Auth.WITH_READ_PERMISSIONS, Permissions.public_profile, Permissions.user_friends, Permissions.email) it always returns **FALSE**.

I have tried this publishing and running directly from with Adobe Animate (latest version) and also from the installed iOS app (on iPhone 4s)

Can you advice where I may have gone wrong?

THanks.

**Comment by FrogDigital** [comment]
Still no joy to get this to work. Ive double checked things like my manifest.xml file and I think its correct.
I am only building for Air for iOS (no Android) so I thought it was straight forward?
Can anyone help me please as this is for a commercial product.
Thank you.

**Comment by myflashlab** [comment]
The first thing I noticed is that you are trying on an iPhone 4s. Are you sure it has iOS version > 8.0? because iOS 8 is the oldest iOS version which can run this ANE. This has been mentioned here: https://github.com/myflashlab/facebook-ANE#requirements

Could you trace out the ```FB.os``` and make sure it is returning "iOS"?

And finally, send us your manifest .xml file so we can have a look at your settings.

**Comment by FrogDigital** [comment]
Thanks.

- iPhone4s supports iOS 9 so its definitely compatible.

- FB.os is returning "iOS"

- MANIFEST.ZIP is attached...
[manifest.zip](https://github.com/myflashlab/facebook-ANE/files/776678/manifest.zip)

When I compile and preview the application in Adobe Animate, the ANE doesnt seem to connect at all.
However, when I run it from the iPhone, then I get a message saying "this is a demonstration version of the ANE..." so it looks like the ANE is instantiating and running correctly.

BUt it just returns FALSE from the FB.getInstance() call.

**Comment by myflashlab** [comment]
> We have updated the ANE to the latest SDK and a LOT has changed. for example like buttons and app invites have been deprecated but we have now added the GameRequest feature. Moreover, we have re-wrote the whole Actionscript part to be easier to work with. Please update yourself to the latest version and see how it goes. If you are still encountering any problem, please feel free to open a new issue and ask your questions. And by the way, when updating your app with the new ANE, make sure to read and follow the [new wiki documentations](https://github.com/myflashlab/facebook-ANE/wiki). Moreover, the asdoc has also moved to this package: http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/fb/package-detail.html

Also make sure to read the changelog to know what changes you need to make to your manifest. xml file.
