### ISSUE TITLE
Can I call logPurchase method?

### ISSUE THREAD

**Issue by ze0nni** [myflashlab/facebook-ANE#74]
I am using logEvent method in facebook-ANE to push players event on facebook.
I also use nAppPayments-ANE for payments. 
Facebok ap provides logPurchase method for push events about in-app payments. Can I call it with facebook-ANE?

**Comment by vietpv** [comment]
someone help, I have the same problem

**Comment by ze0nni** [comment]
I think you can just call `FB.logEvent("fb_mobile_purchase", ...)`
I look at [js-implementation](https://connect.facebook.net/en_US/sdk/debug.js) and it contains several special constants.

**Comment by myflashlab** [comment]
Now you can, please update to the latest version of the ANE.

> We have updated the ANE to the latest SDK and a LOT has changed. for example like buttons and app invites have been deprecated but we have now added the GameRequest feature. Moreover, we have re-wrote the whole Actionscript part to be easier to work with. Please update yourself to the latest version and see how it goes. If you are still encountering any problem, please feel free to open a new issue and ask your questions. And by the way, when updating your app with the new ANE, make sure to read and follow the [new wiki documentations](https://github.com/myflashlab/facebook-ANE/wiki). Moreover, the asdoc has also moved to this package: http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/fb/package-detail.html

Also make sure to read the changelog to know what changes you need to make to your manifest. xml file.
