### ISSUE TITLE
Is there a Deferred AppLink support?

### ISSUE THREAD

**Issue by MaksBrainiac** [myflashlab/facebook-ANE#75]
> In order to receive a deep link after install, your app needs to call AppLinkData.fetchDeferredAppLinkData in the Facebook SDK method when starting up.

Is this possible via this ANE?

**Comment by myflashlab** [comment]
Nope, we have [Firebase Dynamic links](http://www.myflashlabs.com/product/dynamic-links-firebase-air-native-extension/) for this reason.
