### ISSUE TITLE
Is it possible to send game requests?

### ISSUE THREAD

**Issue by MaksBrainiac** [myflashlab/facebook-ANE#76]
SDK Reference
https://developers.facebook.com/docs/games/services/gamerequests

**Comment by UmberFunk** [comment]
At that moment when I was researching, the ANE had no such feature.

You can look at this thread: https://github.com/myflashlab/facebook-ANE/issues/3

**Comment by myflashlab** [comment]
We will be releasing V4.30.0 tomorrow. This feature is added to the new version.
