### ISSUE TITLE
Adobe Air 25 CameraUI/CameraRoll conflict Android

### ISSUE THREAD

**Issue by tufik2** [myflashlab/facebook-ANE#78]
I am developing an app with Facebook and Default CameraUI/CameraRoll.....
The ANE work but when I load this ANE my CameraUI/CameraRoll broken or don't work properly.
Are there any solution or example that work or I need to load extra ANES for compatibility?

Devices testing: Nexus 6P (Android 7.1.2)/ Galaxy S3 (Android 4.3)
Testing.......
When I call FB.getInstance("00000000"); the CameraUI/CameraRoll stop working. 
I try to fix this problem calling FB.dispose() after login with facebook, but don't work....
I am loading the next ANES:
<extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
<extensionID>com.myflashlab.air.extensions.facebook</extensionID>

**Comment by myflashlab** [comment]
Please update yourself with the latest release and tell us how it goes?

**Comment by Deepak34** [comment]
Hi there. I am having this same problem too. Did you end up fixing it or finding some kind of work around?

**Comment by ifalo-apps** [comment]
Hi,
If this code < FB.getInstance("00000000"); > is executed,
My CameraRoll  instance call browseForImage is fine.
But all of event is not throwed. (ex: MediaEvent.SELECT, Event.CANCEL)
It is a big problem for me. Please check this out, thanks.

Example code:
protected var _mediaSource:CameraRoll;
private function onTrigger():void 
{
	_mediaSource = new CameraRoll();
	if (CameraRoll.permissionStatus != PermissionStatus.GRANTED)
	{
		_mediaSource.addEventListener(PermissionEvent.PERMISSION_STATUS, onPermissionStatus);
		_mediaSource.requestPermission();
	}
	else
	{
		_mediaSource.browseForImage();
		_mediaSource.addEventListener(MediaEvent.SELECT, imageSelected);
		_mediaSource.addEventListener(Event.CANCEL, browseCanceled);
		_mediaSource.addEventListener(ErrorEvent.ERROR, browseErrored);
	}
}
private function onPermissionStatus(e:PermissionEvent):void 
{
	_mediaSource.removeEventListener(PermissionEvent.PERMISSION_STATUS, onPermissionStatus);
	if (e.status == PermissionStatus.GRANTED)
	{
		_mediaSource.browseForImage();
		_mediaSource.addEventListener(MediaEvent.SELECT, imageSelected);
		_mediaSource.addEventListener(Event.CANCEL, browseCanceled);
		_mediaSource.addEventListener(ErrorEvent.ERROR, browseErrored);
	}
	else
	{
		//
	}
}

protected function imageSelected(event:MediaEvent):void
{
	trace("[EasyCameraRoll] Image selected...");
	//no fired.
}
protected function browseCanceled(event:Event):void
{
	trace("[EasyCameraRoll] Image browse canceled.");
	//no fired.
}
protected function browseErrored(event:ErrorEvent):void
{
	trace("[EasyCameraRoll] Image browse Errored.");
}

**Comment by myflashlab** [comment]
> We have updated the ANE to the latest SDK and a LOT has changed. for example like buttons and app invites have been deprecated but we have now added the GameRequest feature. Moreover, we have re-wrote the whole Actionscript part to be easier to work with. Please update yourself to the latest version and see how it goes. If you are still encountering any problem, please feel free to open a new issue and ask your questions. And by the way, when updating your app with the new ANE, make sure to read and follow the [new wiki documentations](https://github.com/myflashlab/facebook-ANE/wiki). Moreover, the asdoc has also moved to this package: http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/fb/package-detail.html

Also make sure to read the changelog to know what changes you need to make to your manifest. xml file.
