### ISSUE TITLE
What's the difference between Purchased version and trial version

### ISSUE THREAD

**Issue by daksamedia** [myflashlab/facebook-ANE#8]
Hi @MyFlashLab,

Firstly, I'm so interesting to come here after I watched your video on youtube. It help me to develop my mobile game easily. But I have 1 question on my mind, what's difference does it make between purchased & trial version? What kind of limitation you will give to me on this trial version?

Once again, I appreciate you to make this Native Extension.
Thank  you in advanced.

Daksa Media.

**Comment by myflashlab** [comment]
You're welcome @daksamedia well, there's no limitation at all. all functions work on both versions accept for the fact that you will not be able to use it in a real/commercial project
