### ISSUE TITLE
SHARING imageURL - Deprecated! WTF????

### ISSUE THREAD

**Issue by MyMyGames** [myflashlab/facebook-ANE#80]
http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/facebook/sharing/ShareLink.html

Property Detail
contentDescription	property
public var contentDescription:String
Deprecated, it will no longer be able to set these param manually

contentTitle	property	 
public var contentTitle:String
Deprecated, it will no longer be able to set these param manually

contentURL	property	 
public var contentURL:String
imageURL	property	 
public var imageURL:String
Deprecated, it will no longer be able to set these param manually

**Comment by myflashlab** [comment]
Yep, we were also surprised to see Facebook has deprecated those. it seems like they want to make sure that shared links have description/image/etc read automatically based on the content available on links. That's their decision anyway.
