### ISSUE TITLE
can i to share a local photo? 

### ISSUE THREAD

**Issue by iindieboy** [myflashlab/facebook-ANE#81]
Hello! i want to share a photo, how i can to do it?

Thanks!

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
