### ISSUE TITLE
Missing some standard event constants

### ISSUE THREAD

**Issue by JakobXScape** [myflashlab/facebook-ANE#85]
Hey! Some Standard Events, such as EVENT_NAME_PURCHASED seem to be omitted from AppEventConstants. Is there a reason for this?

**Comment by myflashlab** [comment]
Anything missing might be available if you pass the value as Strings.

> We have updated the ANE to the latest SDK and a LOT has changed. for example like buttons and app invites have been deprecated but we have now added the GameRequest feature. Moreover, we have re-wrote the whole Actionscript part to be easier to work with. Please update yourself to the latest version and see how it goes. If you are still encountering any problem, please feel free to open a new issue and ask your questions. And by the way, when updating your app with the new ANE, make sure to read and follow the [new wiki documentations](https://github.com/myflashlab/facebook-ANE/wiki). Moreover, the asdoc has also moved to this package: http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/fb/package-detail.html

Also make sure to read the changelog to know what changes you need to make to your manifest. xml file.
