### ISSUE TITLE
Duplicated symbols issue.

### ISSUE THREAD

**Issue by amakovii** [myflashlab/facebook-ANE#86]
Hello.
I am using your ANE and have got  an error when was tring to add new ANE(not from myflashlabs) while packaging the application:
duplicate symbol _didFailToRegisterForRemoteNotificationsWithError in:
 /.../libcom.myflashlab.air.extensions.dependency.overrideAir.a(exOverrideNative.o)
    /...PushNotification.a(CTAppController+APNAdditions.o)
duplicate symbol _didReceiveRemoteNotification in:
 /.../libcom.myflashlab.air.extensions.dependency.overrideAir.a(exOverrideNative.o)
    /...PushNotification.a(CTAppController+APNAdditions.o)
duplicate symbol _didRegisterForRemoteNotificationsWithDeviceToken in:
 /.../libcom.myflashlab.air.extensions.dependency.overrideAir.a(exOverrideNative.o)
    /...PushNotification.a(CTAppController+APNAdditions.o)
ld: 3 duplicate symbols for architecture arm64

As I understand my code and yours invoke overridden functions from AppDelegate with the same name. How can I handle this issue? Maybe myflashlabs can offer some ready solutions for local notifications? In your site, I found firebase libs with remote notification, but I need just a small piece of functionality.
Thanks.

**Comment by myflashlab** [comment]
Well, if you have developed the other ANE, why don't you use override.ane only and receive the notification events in your ANE, through the overridAir ANE?

We have developed overridAir and our other dependency ANEs to be able to easily bypass the duplicate problem. You can use them with no problem.

If you want to know where to start to implement overridAir, create an issue in https://github.com/myflashlab/common-dependencies-ANE I'd be happy to help you step by step. feel free to ask.
