### ISSUE TITLE
cannot compile os IOS even after copy .framework 

### ISSUE THREAD

**Issue by hengway1989** [myflashlab/facebook-ANE#87]
Hi, as subject, can please on above issue?
Already copy the fb sdk to \lib\aot\stub
<img width="1632" alt="stub_and_problem_occurred_and_flash_-_echo-v1_0_0-dev_src_com_enconcept_myecho_screens_splashscreen_as_-_flash_builder_-__work_flex_workspace" src="https://user-images.githubusercontent.com/13148479/28618156-92eb1eb2-722d-11e7-8d91-ee27fbd16eda.png">

But when debug on device still show error, please advice

**Comment by myflashlab** [comment]
Are you sure your IDE is using the AIR SDK which you copied the frameworks to? That error happens ONLY if the frameworks are not available. There is no other explanation for this.

**Comment by hengway1989** [comment]
Found the issue, because when I compile IOS, I will put in IOS sdk, so need to move the framework file to IOS SDK instead of AIRSDK folder

<img width="1141" alt="item-0_and_item-0_and_item-0_and_item-0_and_applebluetoothextra_and_airportextra_and_displaysextra_and_applevolumeextra_and_batteryextra" src="https://user-images.githubusercontent.com/13148479/28813265-be8cafe2-76c2-11e7-8d1c-c65921231a40.png">

Just reference for other
