### ISSUE TITLE
Issue with facebook invite notification.

### ISSUE THREAD

**Issue by anupamverma170191** [myflashlab/facebook-ANE#88]
I have purchased this Facebook ANE. Now in my application, i want the facebook invite feature to be used.
So for the invite feature, i have created the App Link URL using the Facebook's Mobile Hosting API.  I have also added to URL to the **FB.appInvite("https://fb.me/4458********9",imgURl,func)**. Now everything is working fine, I am even getting the response also after invite that "onInviteSuccess". But the issue is that am not able to get the notification on the FACEBOOK app for the invite. So please help me out I need this feature in my app. Thanks in advance. Waiting for a quick response.

**Comment by myflashlab** [comment]
please read this by Facebook: https://developers.facebook.com/docs/app-invites/overview#receive_invite

> Invites eventually expire and will no longer appear in this area over time. People can also find their invitation inbox by a mobile bookmark in the Facebook app. If the person already has the app installed or has already received an invite, they will not receive any further notifications.

you may also find Firebase Invite interesting: http://www.myflashlabs.com/product/invites-firebase-air-native-extension/

**Comment by vietpv** [comment]
I use appinvite and returns onInviteSuccess but my friend does not receive the notification from facebook, plz check it

**Comment by myflashlab** [comment]
Consider using GameRequests. we have released a new version of  this ANE yesterday. Invites are deprecated.

**Comment by myflashlab** [comment]
> We have updated the ANE to the latest SDK and a LOT has changed. for example like buttons and app invites have been deprecated but we have now added the GameRequest feature. Moreover, we have re-wrote the whole Actionscript part to be easier to work with. Please update yourself to the latest version and see how it goes. If you are still encountering any problem, please feel free to open a new issue and ask your questions. And by the way, when updating your app with the new ANE, make sure to read and follow the [new wiki documentations](https://github.com/myflashlab/facebook-ANE/wiki). Moreover, the asdoc has also moved to this package: http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/fb/package-detail.html

Also make sure to read the changelog to know what changes you need to make to your manifest. xml file.
