### ISSUE TITLE
Issue with like button IOS

### ISSUE THREAD

**Issue by msmpro** [myflashlab/facebook-ANE#89]
Hi!

I'm using like button (FB.createLikeBtn) on Android and its work perfectly.
But on IOS, the Safari tab is opened (the Facebook app not loaded, but nothing to do for this right?) and the Like button stay visible over browser content.
On Android I'm listening on the view to "deactivate" event to remove/dispose the button, but on IOS this events is not fired.
Any way to know when the Like button is clicked to remove it?

Thanks in advance.

**Comment by msmpro** [comment]
Sorry,

AIR 25 + Facebook ANE 4.17.1 + IOS 9.3.5

**Comment by myflashlab** [comment]
V4.22.3 now includes a callback to let you know when the like button is clicked. https://github.com/myflashlab/facebook-ANE#changelog

**Comment by msmpro** [comment]
;)

Thank you!
