### ISSUE TITLE
ios publish error creating files

### ISSUE THREAD

**Issue by flashomer** [myflashlab/facebook-ANE#9]
hi,
İos publishing error and no framework files  this error
http://prntscr.com/8rpx3c

and copy framework files in "AIR18.0\lib\aot\stub" this error
http://prntscr.com/8rpwxn
http://prntscr.com/8rpwsk

help me please.

**Comment by myflashlab** [comment]
you need to set "-hideAneLibSymbols yes" when compiling .ipa. Read here for more instruction https://github.com/myflashlab/common-dependencies-ANE#how-to-use-commondependencies-ane
