### ISSUE TITLE
Facebook relogin problem after latest version upgrade

### ISSUE THREAD

**Issue by tfnsyl** [myflashlab/facebook-ANE#91]
Hi, 

I was having the [issue](https://github.com/myflashlab/facebook-ANE/issues/90) and after I upgraded to the latest version, it seems fixed for now. But everytime I open the app, a safari window opens forcing to relogin. 

`FB.auth.isLogin` always returns `false` and `FB.auth.token` always returns `null`. Previous version of ANE didn't have this problem, but for the [issue#90](https://github.com/myflashlab/facebook-ANE/issues/90) I can't retry it.

Anyone having this problem?

**Comment by myflashlab** [comment]
Can't duplicate this. give us more info on how this happens?

**Comment by tfnsyl** [comment]
I am using exactly the same sample on your repository.

```
if (FB.auth.isLogin)
{
	trace("You have logged in before. getUserGraph");
	toGraph();
}
else
{
	FB.auth.addEventListener(FBEvent.LOGIN_DONE, onLoginSuccess);
	FB.auth.addEventListener(FBEvent.LOGIN_CANCELED, onLoginCanceled);
	FB.auth.addEventListener(FBEvent.LOGIN_ERROR, onLoginError);
	FB.auth.requestPermission(Auth.WITH_READ_PERMISSIONS, Permissions.public_profile, Permissions.user_friends, Permissions.email);
	trace("Please wait...");
}
```
`

For the first time login process is being completed with no error, and after that I can see in console that `FB.auth.token` has a value and `FB.auth.isLogin` returns true.

The problem is that if I close application and reopen, `FB.auth.isLogin` returns false again. So everytime I open the app, a Safari window is opening.

I am using AIR SDK 26, testing on an iPad mini.

**Comment by iamgowan** [comment]
I'm having problems with this, too. isLogin returns false immediately after a FB.getInstance() (where it before had an immediate true value if the app had connected to Facebook a previous time).

Eventually, the ANE will re-login, and isLogin will be true, but there is no way of knowing when this will happen, as the LOGIN_DONE event will not dispatch after an automatic re-login.

**Comment by tfnsyl** [comment]
Hi, as a workaround, I solved it by initing `FB.getInstance(XXXXX)` on the very beginning of the application and gave it some timeout to get `FB.auth.isLogin`. By this way it always returns as expected, but that doesn't seem to be the best solution. You may need to recheck if FB.auth.isLogin is really set by the ANE.

**Comment by iamgowan** [comment]
Hi tfnsyl, yes, I also now check after a delayed call, but you're right, this is not a great way to go about knowing FB's status.

**Comment by josephdecarie** [comment]
I'm having the same problem. Using AIR 28.

**Comment by myflashlab** [comment]
> We have updated the ANE to the latest SDK and a LOT has changed. for example like buttons and app invites have been deprecated but we have now added the GameRequest feature. Moreover, we have re-wrote the whole Actionscript part to be easier to work with. Please update yourself to the latest version and see how it goes. If you are still encountering any problem, please feel free to open a new issue and ask your questions. And by the way, when updating your app with the new ANE, make sure to read and follow the [new wiki documentations](https://github.com/myflashlab/facebook-ANE/wiki). Moreover, the asdoc has also moved to this package: http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/fb/package-detail.html

Also make sure to read the changelog to know what changes you need to make to your manifest. xml file.
