### ISSUE TITLE
Is it possible to check when user clicked the Like button?

### ISSUE THREAD

**Issue by ionutmihaila** [myflashlab/facebook-ANE#92]
Hi guys,

Can you please tell me if it is possible to check when user clicked the Like button?

Many thanks!
Ionut

**Comment by myflashlab** [comment]
We are putting this in our to-do list. it would be a handy feature. Thanks for suggesting this.

**Comment by myflashlab** [comment]
V4.22.3 now includes a callback to let you know when the like button is clicked. https://github.com/myflashlab/facebook-ANE#changelog

**Comment by ionutmihaila** [comment]
Awesome, thank you, guys!
