### ISSUE TITLE
Validate token

### ISSUE THREAD

**Issue by ze0nni** [myflashlab/facebook-ANE#93]
If after login with _facebook.ane_ I will go to _facebook.com -> settings -> apps -> %myapp%_ and remove it from list when `FB.auth.isLogin` is still return `true`. Tere any mechanisms to validate token right after call `FB.getInstance(XXX)` next time?

**Comment by myflashlab** [comment]
good question. the thing is that the graph API is your best friend when you wish to do such things. check out this question: https://stackoverflow.com/questions/8605703/how-to-verify-facebook-access-token

**Comment by ze0nni** [comment]
I can work with graph api, but question about facebook-ANE I was think it deal to validate token. Now I see [commen ](http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/facebook/access/Auth.html#token) about token. But I stil find it not very convenient. Thanks!
