### ISSUE TITLE
Missing Push Notification Entitlement

### ISSUE THREAD

**Issue by Elegarret** [myflashlab/facebook-ANE#95]
After I submited my app to itunes connect via apploader I received letter from apple about "Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service..."
It appeared after I included facebook.ane into the build. My app doesn't use pushes at all, but for some reason apple think it does.. I uploaded the same project to the testflight before and there wasn't such warning. The only changes is included facebook.ane, overrideAIR.ane and dependent changes to plist described in your readme...

It is just a warning from apple, but some people in the internet say that it may cause rejection. Anyway warning is not good.

**Comment by myflashlab** [comment]
That's interesting. Considering that this is very likely to be related to the overrideAir ANE and how apple watches the ipa files, we have created a new issue [here](https://github.com/myflashlab/common-dependencies-ANE/issues/13) so we can better track this problem. please share with us your experience about this on the linked page. Thanks.
