### ISSUE TITLE
Is it possible to open a facebook page?

### ISSUE THREAD

**Issue by avradu1984** [myflashlab/facebook-ANE#96]
Can a facebook page be opened using this ANE? 

I would like users to be able to press a button in my app and be redirected (using their native Facebook app) to my facebook page, so they can read or post messages.

Thank you!

**Comment by myflashlab** [comment]
you may find this information useful: https://stackoverflow.com/questions/12107627/open-facebook-page-in-native-facebook-ios-app-via-simple-url-sheme-issue
