### ISSUE TITLE
Lite version of AndroidSupport ANE?

### ISSUE THREAD

**Issue by msmpro** [myflashlab/facebook-ANE#97]
Hi!

I'm updating Facebook ANE from v. 4.17.1 to 4.22.3 and I have two questions about AndroidSupport ANE:
- Why its passed from 2.5Mb to 4Mb (lite version and 6Mb for full version)?
- The Facebook ANE is fully functional with lite version?

Thanks.

**Comment by myflashlab** [comment]
you should try the full version for Facebook to work properly. If your question is about size of the new versions, well, that's how Android works :) the new versions have introduced new libraries.

side note: ANE size does not means that your final app size will also increase as much. it will increase the size a little of course but you should not think that the size will be increased according to the size of the ANE. Let me know if you have more questions?

**Comment by msmpro** [comment]
Thank you for the quick response! 
Now all it's clear.
