### ISSUE TITLE
FB.share function not working

### ISSUE THREAD

**Issue by babakasol** [myflashlab/facebook-ANE#98]
Hello,
I am using your latest facebook ANE and i see FB.share function is not working.
I have been using the previous versions also and it was working fine. Its happening with the new one

## Environment ##
* AIR SDK Version: 26

## Problem Description ##
When calling the FB.share function of facebook ANE, it dosen't gives response or error, even there is not status event if the sharing is cancelled.

Thankyou

**Comment by myflashlab** [comment]
1. is this happening on Android or iOS or both?
2. have you checked out the latest changes in the changelog?
3. any possible error log or something you can share with us?

> When using sharing a URL with FB.share(shareModel, onSharingResult);, the shareModel object can only have the contentURL property. Other properties are deprecated: (contentDescription, contentTitle and imageURL)

**Comment by myflashlab** [comment]
Closing the issue due to inactivity.
