### ISSUE TITLE
Crash on iOS

### ISSUE THREAD

**Issue by Igazine** [myflashlab/facebook-ANE#99]
## Environment ##
* iOS Version: 10.3.3
* AIR SDK Version: 27

## Problem Description ##

> FB.auth.requestPermission( Auth.WITH_READ_PERMISSIONS, Permissions.public_profile, Permissions.email, Permissions.user_friends, Permissions.user_birthday );

crashes on iOS while I'm testing the app with FB login. The same procedure works fine on Android.

Notes:

*  the device does not have Facebook app installed, so the authentication happens in Safari
*  the FB app name, my account name, permission requests appear properly
*  I can log in to my FB account, on the next screen it asks if I want to continue. If I tap Continue it loads for a few seconds then the entire app crashes with no more trace messages in Terminal
*  If I cancel the event by tapping Done instead of Continue, the Cancel event fires properly and the app can be used
*  I tried both the commercial and the free version of the facebook.ane, both produce the same result
*  application XML is properly set, we're using other ANEs as well, so if it's a compatibility issue, I can't point out which one can be the issue
*  Facebook SDK framework is copied onto AIRSDK
*  the code works perfectly fine on Android without any further hacks whatsoever

Here's what relevant logs I could dig up from macOS console, maybe it helps:

> <FBApplicationProcess: 0x827d8c0; appname; pid: 2124> crashed.

> Process exited: <FBApplicationProcess: 0x827d8c0; appname; pid: -1> -> <FBApplicationProcessExitContext: 0x8ad8250; exitReason: crash; terminationReason: (none)>

> -CMSessionMgr- cmsmHandleApplicationStateChange: CMSession: Client com.app.id with pid '2124' is now Terminated. Background entitlement: NO

Thank you

**Comment by Igazine** [comment]
Update: having the Facebook app installed it still uses Safari, and the app still crashes :(

**Comment by myflashlab** [comment]
**Side note** Facebook has officially dropped support for fast-app-switching feature on iOS apps built with newer FB SDKs. https://developers.facebook.com/blog/post/2015/10/29/Facebook-Login-iOS9/

post your manifest here.

**Comment by Igazine** [comment]
```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<application xmlns="http://ns.adobe.com/air/application/26.0">
	<id>@TEMPLATE.APPID@</id>
	<filename>@TEMPLATE.FILENAME@</filename>
	<name>@TEMPLATE.APPNAME@</name>
	<versionNumber>@TEMPLATE.APPVERSION@</versionNumber>
	<copyright>@TEMPLATE.COPYRIGHT@</copyright>
	<initialWindow>
		<content>@TEMPLATE.SWF@</content>
		<aspectRatio>portrait</aspectRatio>
		<renderMode>direct</renderMode>
		<depthAndStencil>true</depthAndStencil>
		<softKeyboardBehavior>pan</softKeyboardBehavior>
		<autoOrients>false</autoOrients>
		<fullScreen>true</fullScreen>
		<visible>true</visible>
	</initialWindow>
	<!-- <supportedLanguages>en de cs es fr it ja ko nl pl pt ru sv tr zh</supportedLanguages> -->
	<icon>
		<image16x16>@TEMPLATE.ICONDIR@/icon16.png</image16x16>
		<image29x29>@TEMPLATE.ICONDIR@/icon29.png</image29x29>
		<image32x32>@TEMPLATE.ICONDIR@/icon32.png</image32x32>
		<image36x36>@TEMPLATE.ICONDIR@/icon36.png</image36x36>
		<image40x40>@TEMPLATE.ICONDIR@/icon40.png</image40x40>
		<image48x48>@TEMPLATE.ICONDIR@/icon48.png</image48x48>
		<image50x50>@TEMPLATE.ICONDIR@/icon50.png</image50x50>
		<image57x57>@TEMPLATE.ICONDIR@/icon57.png</image57x57>
		<image58x58>@TEMPLATE.ICONDIR@/icon58.png</image58x58>
		<image60x60>@TEMPLATE.ICONDIR@/icon60.png</image60x60>
		<image72x72>@TEMPLATE.ICONDIR@/icon72.png</image72x72>
		<image76x76>@TEMPLATE.ICONDIR@/icon76.png</image76x76>
		<image80x80>@TEMPLATE.ICONDIR@/icon80.png</image80x80>
		<image96x96>@TEMPLATE.ICONDIR@/icon96.png</image96x96>
		<image100x100>@TEMPLATE.ICONDIR@/icon100.png</image100x100>
		<image114x114>@TEMPLATE.ICONDIR@/icon114.png</image114x114>
		<image120x120>@TEMPLATE.ICONDIR@/icon120.png</image120x120>
		<image128x128>@TEMPLATE.ICONDIR@/icon128.png</image128x128>
		<image144x144>@TEMPLATE.ICONDIR@/icon144.png</image144x144>
		<image152x152>@TEMPLATE.ICONDIR@/icon152.png</image152x152>
	</icon>
	<iPhone>
		<InfoAdditions>
			<![CDATA[
			
				<key>MinimumOSVersion</key>
        		<string>8.0</string>
        		
        		<key>UIStatusBarStyle</key>
        		<string>UIStatusBarStyleBlackOpaque</string>
        		
        		<key>UIRequiresPersistentWiFi</key>
		        <string>NO</string>
		       
		        <key>UIFileSharingEnabled</key>
		        <string>NO</string>
		        
		        <key>UIPrerenderedIcon</key>
        		<true />
        		
				<key>UIApplicationExitsOnSuspend</key>
				<false />
				
				<key>UIViewControllerBasedStatusBarAppearance</key>
				<false/>
				<key>UIDeviceFamily</key>
				<array>
					<string>1</string>
				</array>

				<key>CFBundleURLTypes</key>
				<array>
					<dict>
						<key>CFBundleURLSchemes</key>
						<array>
						  <string>fb@TEMPLATE.FACEBOOKID@</string>
						  <string>@TEMPLATE.URLSCHEME@</string>
						  <string>@TEMPLATE.URLSCHEME2@</string>
						</array>
						<key>CFBundleURLName</key>
						<string>@TEMPLATE.URLNAME@</string>
					</dict>
				</array>

				<key>FacebookAppID</key>
				<string>@TEMPLATE.FACEBOOKID@</string>
				<key>FacebookDisplayName</key>
				<string>@TEMPLATE.FACEBOOKNAME@</string>
				
                <key>LSApplicationQueriesSchemes</key>
                <array>
                    <string>fbapi</string>
                    <string>fb-messenger-api</string>
                    <string>fbauth2</string>
                    <string>fbshareextension</string>
                </array>

				<!--rquired by iOS 10, without permission description app will crashed-->
                <key>NSLocationUsageDescription</key>
                <string>To allow us to accurately calculate distance, please turn your location services on.</string>
                <key>NSLocationAlwaysUsageDescription</key>
				<string>To allow us to accurately calculate distance, please turn your location services on.</string>
				<key>NSLocationWhenInUseUsageDescription</key>
				<string>Allow geolocation when application is in foreground</string>
                <key>NSCameraUsageDescription</key>
                <string>To allow QR scanner, please enable camera access</string>
                <key>NSPhotoLibraryUsageDescription</key>
                <string>To allow update user avatar, please enable photo library access</string>    
                <!--required by Tapjoy, some add may access user calendar-->
                <key>NSCalendarsUsageDescription</key>
                <string>Some ad content may access calendar</string>

                <!--required by iOS 9 ATS issue-->
				<key>NSAppTransportSecurity</key>
				<dict>
					<key>NSAllowsArbitraryLoads</key>
					<true/>
                    <!--required by Tapjoy, show content cached on device-->
                    <!--to avoid Tapjoy stream all content from server-->
                    <key>NSExceptionDomains</key>
                    <dict>
                       <key>localhost</key>
                       <dict>           
                           <key>NSExceptionAllowsInsecureHTTPLoads</key>
                           <true/>
                       </dict>
                    </dict>
				</dict>
			]]>
		</InfoAdditions>
		<requestedDisplayResolution>high</requestedDisplayResolution>
	</iPhone>

	<extensions>
		<extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
		<extensionID>com.myflashlab.air.extensions.facebook</extensionID>
		<extensionID>com.sbhave.nativeExtensions.zbar</extensionID>
		<extensionID>com.milkmangames.extensions.GAnalytics</extensionID>
		<extensionID>com.milkmangames.extensions.GAIDFAAccess</extensionID>
		<extensionID>com.milkmangames.extensions.EasyPush</extensionID>
		<extensionID>com.milkmangames.extensions.CoreMobile</extensionID>
		<extensionID>com.appsflyer.adobeair</extensionID>
		<extensionID>com.tapjoy.extensions</extensionID>
		<extensionID>com.freshplanet.AirImagePicker</extensionID>
		<extensionID>com.freshplanet.AirNativeShare</extensionID>
		<extensionID>com.freshplanet.AirNetworkInfo</extensionID>
		<extensionID>com.freshplanet.ane.AirDeviceId</extensionID>
	</extensions>
</application>

```

**Comment by Igazine** [comment]
please note that i'm using ant to compile and build the app, no IDE is involved, that's why you can see @something@ at places that are filled in by ant, but i can assure you, all of the template ids are in place correctly in the generated app xml

**Comment by myflashlab** [comment]
Try to send us the crash logs from xcode console which might include more information. The logs you already sent does not include much helpful information.

Also try to use the ANE alone first by removing other ANEs. To make sure they are not causing weird conflicts. Let us know how it goes.

**Comment by subdan** [comment]
I have the same issue. My app crashes on iOS when I try to request permissions: 
`FB.auth.requestPermission(Auth.WITH_PUBLISH_PERMISSIONS, Permissions.public_profile);`

**Comment by PippoApps** [comment]
Same issue. I opened a new issue with all info.

**Comment by myflashlab** [comment]
@subdan please note that ```Permissions.public_profile``` is not a ```Auth.WITH_PUBLISH_PERMISSIONS```!

it's a ```Auth.WITH_READ_PERMISSIONS```

**Comment by myflashlab** [comment]
> We have updated the ANE to the latest SDK and a LOT has changed. for example like buttons and app invites have been deprecated but we have now added the GameRequest feature. Moreover, we have re-wrote the whole Actionscript part to be easier to work with. Please update yourself to the latest version and see how it goes. If you are still encountering any problem, please feel free to open a new issue and ask your questions. And by the way, when updating your app with the new ANE, make sure to read and follow the [new wiki documentations](https://github.com/myflashlab/facebook-ANE/wiki). Moreover, the asdoc has also moved to this package: http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/fb/package-detail.html

Also make sure to read the changelog to know what changes you need to make to your manifest. xml file.
